### ISSUE TITLE
DataStoreException if the app is closed while datastore is syncing or a query is running

### ISSUE THREAD

**Issue by anymeshsingh** [aws-amplify/amplify-flutter#1194]
So the issue is only for Android and in release mode. If the app is closed while a datastore query is running or while the datastore is syncing, then datastore got corrupt. And after that whenever the app is opened every datastore method (i.e query, start, clear, etc.) is throwing this error.

Could be related to this [issue](https://github.com/aws-amplify/amplify-android/issues/802) on the amplify-android Github repo.

```
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: Failed to start datastore with error: 
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: DataStoreException{message=Failed to start DataStore., cause=DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}, recoverySuggestion=Retry.}
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at com.amplifyframework.datastore.AWSDataStorePlugin.F(Unknown Source:6)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at com.amplifyframework.datastore.C.accept(Unknown Source:4)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.observers.CallbackCompletableObserver.onError(Unknown Source:2)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(Unknown Source:2)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(Unknown Source:2)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.disposables.EmptyDisposable.error(Unknown Source:5)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletableError.subscribeActual(Unknown Source:2)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.core.Completable.subscribe(Unknown Source:14)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(Unknown Source:9)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(Unknown Source:23)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(Unknown Source:2)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout$TimeOutObserver.onComplete(Unknown Source:17)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(Unknown Source:24)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.core.Completable.subscribe(Unknown Source:14)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout.subscribeActual(Unknown Source:38)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.core.Completable.subscribe(Unknown Source:14)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(Unknown Source:2)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Unknown Source:9)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(Unknown Source:0)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at java.lang.Thread.run(Thread.java:923)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: Caused by: DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at com.amplifyframework.datastore.syncengine.Orchestrator.performSynchronized(Unknown Source:51)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at com.amplifyframework.datastore.syncengine.Orchestrator.start(Unknown Source:6)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at com.amplifyframework.datastore.AWSDataStorePlugin.start(Unknown Source:6)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.onStart(Unknown Source:27)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.onMethodCall(Unknown Source:77)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at j.a.d.a.w.a(Unknown Source:17)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.flutter.embedding.engine.o.h.e(Unknown Source:17)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at android.os.MessageQueue.next(MessageQueue.java:335)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at android.os.Looper.loop(Looper.java:183)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at android.app.ActivityThread.main(ActivityThread.java:8030)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at java.lang.reflect.Method.invoke(Native Method)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
12-08 17:39:54.113 26392 21689 E amplify:flutter:datastore: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

I am using the following configurations:
```
amplify_flutter: ^0.2.10
amplify_api: ^0.2.10
amplify_datastore: ^0.2.10
amplify_auth_cognito: ^0.2.10
amplify_storage_s3: ^0.2.10

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 2.14.4
```

**Comment by HuiSF** [comment]
Thanks for opening this issue @anymeshsingh . 

Have you tried the solution recommended in the linked amplify-android issue? In amplify-flutter, the equivalent should be:

https://github.com/aws-amplify/amplify-flutter/blob/75264e817a2d5aba97979443541106bacb475a6b/packages/amplify_datastore/example/lib/main.dart#L153-L158

In addition, amplify-flutter now provides a [new API `observeQuery`](https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/#observe-query-results-in-real-time), which allow querying without waiting for the `ready` event.

**Comment by HuiSF** [comment]
Also, "if the App is closed", do you mean put the App into background or quit the App completely?

**Comment by anymeshsingh** [comment]
> Also, "if the App is closed", do you mean put the App into background or quit the App completely?

**Comment by anymeshsingh** [comment]
> Thanks for opening this issue @anymeshsingh .
> 
> Have you tried the solution recommended in the linked amplify-android issue? In amplify-flutter, the equivalent should be:
> 
> https://github.com/aws-amplify/amplify-flutter/blob/75264e817a2d5aba97979443541106bacb475a6b/packages/amplify_datastore/example/lib/main.dart#L153-L158
> 
> In addition, amplify-flutter now provides a [new API `observeQuery`](https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/#observe-query-results-in-real-time), which allow querying without waiting for the `ready` event.

Hi @HuiSF,
Thanks for the solution, it worked for me. But since the ready event is returned through a StreamSubscription and not as a Future I can not await for it. So what I'm doing is running a while loop at launch and checking if it is ready and showing a loader to the user for the mean while. I don't know why DataStore is taking 3 to 4 sec to get ready on every app launch.

Also, Is there a way to get this ready event as a Future? Because that would make my code way simpler.

**Comment by anymeshsingh** [comment]
> > Also, "if the App is closed", do you mean put the App into background or quit the App completely?

I mean quit the app completely.

**Comment by HuiSF** [comment]
Thanks for following up @anymeshsingh .

> Also, Is there a way to get this ready event as a Future? Because that would make my code way simpler.

I think you can wrap your own login inside the `runQueries` in the example, so the logic will only be executed when the `ready` event comes back. (sort of equivalent to await Future)

Reading more your use case, I highly recommend you to check out the `observeQuery` API, you can start query anytime without waiting for the `ready` event, and it will setup a stream for you, so if any new records get synced from cloud, it will update the query result. 

In the meantime, I will try to reproduce the exception you described in the original post.

**Comment by anymeshsingh** [comment]
@HuiSF thanks for the suggestion. Currently all my Amplify dependent services uses  `async await` to query DataStore. But when I'll refactor my codebase I'll keep in mind to use the `observeQuery` API.

**Comment by HuiSF** [comment]
Update: I couldn't reproduce this issue while killing the App process during initial sync...

How many models do you have in the App, @anymeshsingh ? And roughly how many records the initial sync needs to download from cloud? There is [an issue](https://github.com/aws-amplify/amplify-android/issues/1403) in android-amplify repo looks similar.

**Comment by offlineprogrammer** [comment]
Hi @anymeshsingh 

Following up on this if you can get back to us please with the details as per @HuiSF comment above

Regards
Mo
