### ISSUE TITLE
**I'm getting this error in iOS. Working fine with android. I'm not testing in web**

### ISSUE THREAD

**Issue by savadmv** [aws-amplify/amplify-flutter#1228]
**I'm getting this error in iOS. Working fine with android. I'm not testing in web** 

```dart
void configureAmplify() async {
    // Add Pinpoint and Cognito Plugins, or any other plugins you want to use

    AmplifyAnalyticsPinpoint analyticsPlugin = AmplifyAnalyticsPinpoint();
    AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
    await Amplify.addPlugins([authPlugin, analyticsPlugin]);

    // Once Plugins are added, configure Amplify
    // Note: Amplify can only be configured once.

    try {
      await Amplify.configure(amplifyconfig);
    } on AmplifyAlreadyConfiguredException {
      print(
          "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    } on AmplifyException catch (e) {
      throw AmplifyException(e.message);
    }
  }

```
**_pubspec.yaml_**

```dart
  amplify_flutter: ^0.2.10
  amplify_auth_cognito: ^0.2.10
  amplify_analytics_pinpoint: ^0.2.10

```

```
flutter: Amplify plugin was not added
flutter: Amplify plugin was not added
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: AmplifyException(message: Amplify plugin AmplifyAuthCognito was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: MissingPluginException(No implementation found for method addPlugin on channel com.amazonaws.amplify/auth_cognito))
#0      AmplifyClass.addPlugin (package:amplify_flutter/amplify.dart:101:9)
<asynchronous suspension>
#1      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#2      AmplifyImpl.configureAmplify (package:xxxx_xxxx_xxx/core/init/amplify_init.dart:18:5)
<asynchronous suspension>
```

_Originally posted by @savadmv in https://github.com/aws-amplify/amplify-flutter/issues/302#issuecomment-979817949_

**Comment by HuiSF** [comment]
Hi @savadmv could you explain what's the configuration for the `auth` category? 
Could you also paste the content of `amplifyconfiguration.dart`? (please be sure to mask sensitive data fields)

**Comment by savadmv** [comment]
Hi, @HuiSF  Thanks for asking. But I later found out that the issue was with the way I build the iOS app. The **_GeneratedPluginRegistrant.m_** was outside the **_Runner_** folder (I really don’t know how). The same issue I got from **_Firebase SDK_**  enlightened my brain. Thanks again. 

Anyone who gets the same issue. Please check your ios folder. if **_GeneratedPluginRegistrant.m_** is there outside the Runner folder, You have a problem  there
