### ISSUE TITLE
App crash on android because of Fatal Exception: java.lang.NoClassDefFoundError In Amplify Datastore

### ISSUE THREAD

**Issue by nimisharanipabacancy** [aws-amplify/amplify-flutter#1239]
I am using Amplify Datastore plugin. I facing repetitive crash in android (LGE - Nexus 5X - Android 6.0.1 ). Below is crash log.

```
Fatal Exception: java.lang.NoClassDefFoundError: com.amplifyframework.datastore.syncengine.SyncProcessor$$ExternalSyntheticLambda13
       at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$syncModel$13(SyncProcessor.java:249)
       at com.amplifyframework.datastore.syncengine.SyncProcessor.$r8$lambda$2cJLxw0MiDnoj5SD1yHgXEAXleg(SyncProcessor.java)
       at com.amplifyframework.datastore.syncengine.SubscriptionProcessor$$InternalSyntheticLambda$0$dad4a5859176b69f01dda9628153ddd3768e4a48c8c9943a26aea231e4ca30ff$3.test$bridge(SubscriptionProcessor.java)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableTakeUntilPredicate$InnerSubscriber.onNext(FlowableTakeUntilPredicate.java:60)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:92)
       at io.reactivex.rxjava3.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.innerNext(FlowableConcatMap.java:204)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapInner.onNext(FlowableConcatMap.java:559)
       at io.reactivex.rxjava3.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:133)
       at io.reactivex.rxjava3.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java:62)
       at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
       at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$null$14(SyncProcessor.java:291)
       at com.amplifyframework.datastore.syncengine.SyncProcessor.$r8$lambda$5f0_vnPDKFWgAo9MA_Vt3rfcC74(SyncProcessor.java)
       at com.amplifyframework.datastore.syncengine.SyncProcessor$$InternalSyntheticLambda$0$64a9d437439bf1e4420b2ce4f2eb752d556c88cae3c2dcae6edeb915977805d3$0.accept$bridge(SyncProcessor.java)
       at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0(AppSyncClient.java:117)
       at com.amplifyframework.datastore.appsync.AppSyncClient.$r8$lambda$-37xmeMO4UPqA1gVwRa15COBIjo(AppSyncClient.java)
       at com.amplifyframework.datastore.AWSDataStorePlugin$$InternalSyntheticLambda$0$5e2d5e49292ec57d19d466a7a19209bd0d8138629831c97476e39b0664f837eb$0.accept$bridge(AWSDataStorePlugin.java)
       at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:153)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

I used following amplify dependancies:
  amplify_flutter: ^0.2.2
  amplify_api: ^0.2.2
  amplify_auth_cognito: ^0.2.2
  amplify_datastore: ^0.2.10

**Comment by haverchuck** [comment]
@nimisharanipabacancy Are you setting `minifyEnabled true` in your gradle file?

**Comment by HuiSF** [comment]
Could you try to build again with the same version of amplify-flutter packages?
You are using 0.2.10 of DataStore while using 0.2.2 of other packages, the underlying dependencies may be out of sync.

**Comment by nimisharanipabacancy** [comment]
> @nimisharanipabacancy Are you setting `minifyEnabled true` in your gradle file?

Yes. minifyEnabled true in gradle

**Comment by nimisharanipabacancy** [comment]
By changing, all Amplify package to 0.2.10. Still facing this issue.

**Comment by haverchuck** [comment]
@nimisharanipabacancy Can you see what happens when you change `minifyEnabled` to false?

**Comment by nimisharanipabacancy** [comment]
@haverchuck I have tried with setting `minifyEnabled` to false still facing same issue.

**Comment by HuiSF** [comment]
Hi @nimisharanipabacancy sorry for the delayed follow up, is this issue still happening to you?

**Comment by ugill123** [comment]
> Hi @nimisharanipabacancy sorry for the delayed follow up, is this issue still happening to you?

Hi, @HuiSF I am facing this issue on the oppo f1s(API 22) physical device. 
I tested my app on Samsung s21(in released mode)  and Nexus 5 emulator and it works fine. 
dependencies I am using:
  amplify_flutter: ^0.4.0
  amplify_datastore: ^0.4.0
  amplify_api: ^0.4.0
  amplify_auth_cognito: ^0.4.0

**Comment by ugill123** [comment]
yes, I tested my app on Samsung s21 in release mode and Nexus 5 emulator in debug mode, and it works fine. In the case of Oppo f1s(API 22), the app is crashed in both debug and release mode.

**Comment by HuiSF** [comment]
Hello @ugill123 @nimisharanipabacancy 

Sorry for the delayed response. I think I've identified the root cause that the DataStore implementation of amplify-android uses a few APIs that are only available on Android API 24+. E.g. [the spot](https://github.com/aws-amplify/amplify-android/blob/880a182814514f9bce2c914ced44756f8af52f40/aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java#L248-L250) that caused the crash described in this issue.

I've filed an issue for amplify-android https://github.com/aws-amplify/amplify-android/issues/1693.

While we are waiting for a fix, we would need to build and run the APK on API level 24+ device/emulators, sorry for the inconvenience.

**Comment by tylerjroach** [comment]
The issue here is not related to `minifyEnabled`. Java8 and desugaring need to be enabled in build.gradle as shown in the Android documentation here.
https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android/#install-amplify-libraries

Specifically these lines:


Add the following dependencies to your app build.gradle file and click "Sync Now" when asked:
```
dependencies {
    implementation 'com.amplifyframework:aws-datastore:1.37.5'

    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}
```
At the top of the same file, add compileOptions to support the Java 8 features used by Amplify:
```
android {
    compileOptions {
        // Support for Java 8 features
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
