### ISSUE TITLE
After the signup not able to get the idToken. Getting session expired.

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#1278]
**Steps:**

1. After entering email id and password click on signup with the following code;

```
SignUpResult res = await Amplify.Auth.signUp(
          username: emailController.text.trim(),
          password: passwordController.text.trim(),
          options: CognitoSignUpOptions(userAttributes: userAttributes));
```

2. Enter confirmation code.
3. Redirect to a new screen. Try to get an idToken;

```
      AuthSession res = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      );
      idToken = (res as CognitoAuthSession).userPoolTokens!.idToken;
      log('idToken: $idToken');

```
4. Getting error as session expired.

**Expected Result:**
Should be able to get a idToken without making logout.

**Note:**
In signin there is no issue with idToken. 

**Flutter details:**
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (3 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

**Cognito versions:**
```
amplify_flutter: ^0.2.10
amplify_auth_cognito: ^0.2.10
```

**Comment by dnys1** [comment]
Hi @Sunsiha - sorry you are experiencing this issue. Can you please share whether this is on iOS or Android and any logs which show the error (preferably from running the app in either Xcode or Android Studio).

**Comment by Sunsiha** [comment]
@dnys1 
**In android** 

```
com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: xxxxxx)
W/AWSMobileClient(17647): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient(17647): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient(17647): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(17647): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient(17647): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient(17647): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient(17647): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3997)
W/AWSMobileClient(17647): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
W/AWSMobileClient(17647): 	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
W/AWSMobileClient(17647): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
W/AWSMobileClient(17647): 	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:398)
W/AWSMobileClient(17647): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:443)
W/AWSMobileClient(17647): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:440)
W/AWSMobileClient(17647): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
W/AWSMobileClient(17647): 	at java.lang.Thread.run(Thread.java:920)
E/amplify:flutter:auth_cognito(17647): SessionExpiredException
E/amplify:flutter:auth_cognito(17647): SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareCognitoSessionFailure(AuthCognito.kt:594)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:385)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:86)
E/amplify:flutter:auth_cognito(17647): 	at com.amplifyframework.auth.cognito.MobileClientSessionAdapter$1.onError(MobileClientSessionAdapter.java:74)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:47)
E/amplify:flutter:auth_cognito(17647): 	at java.lang.Thread.run(Thread.java:920)
I/flutter (17647): Your session has expired.
```

**In iOS**

Something like - flutter: There is no user signed in to retreive user sub

```
2022-01-19 20:13:22.129852+0530 Runner[45784:583686] [boringssl] boringssl_metrics_log_metric_block_invoke(144) Failed to log metrics
2022-01-19 20:13:22.501131+0530 Runner[45784:583100] [AuthErrorHandler] The operation couldn’t be completed. (Amplify.AuthError error 6.)
2022-01-19 20:13:22.517119+0530 Runner[45784:578786] flutter: There is no user signed in to retreive user sub
2022-01-19 20:13:22.746532+0530 Runner[45784:578786] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: AmplifyAlreadyConfiguredException(message: Amplify has already been configured and adding plugins after configure is not supported., recoverySuggestion: Check if Amplify is already configured using Amplify.isConfigured., underlyingException: null)
#0      AmplifyClass.addPlugin (package:amplify_flutter/amplify.dart:109:7)
#1      _SignInState._initAmplifyFlutter (package:dsaas/cognito/signin_screen.dart:65:13)
#2      _SignInState.initState (package:dsaas/cognito/signin_screen.dart:58:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4805:57)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#29     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6333:36)
#30     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6344:32)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#45     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#59     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#70     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#81     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#88     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#91     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#100    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#104    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#120    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#124    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#127    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#139    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#140    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#143    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#144    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#148    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#159    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#160    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#161    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#162    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#163    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#167    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#168    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#169    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#170    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#171    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#175    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#176    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#177    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#178    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#179    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#180    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#182    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195:14)
#183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#184    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#187    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#188    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#189    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#190    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#192    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#193    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#196    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#198    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#199    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#200    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#201    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#202    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#204    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6333:36)
#205    Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#206    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5758:32)
#207    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6356:17)
#208    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#210    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#211    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#212    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#213    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#215    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#216    ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#217    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#219    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#220    ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#221    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
#222    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#223    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#227    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#228    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#229    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#230    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#232    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#233    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#235    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#236    ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#239    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#241    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#242    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#243    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#244    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#245    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#246    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#247    _rootRun (dart:async/zone.dart:1428:13)
#248    _CustomZone.run (dart:async/zone.dart:1328:19)
#249    _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#250    _invoke (dart:ui/hooks.dart:166:10)
#251    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#252    _drawFrame (dart:ui/hooks.dart:129:31)
2022-01-19 20:13:22.769233+0530 Runner[45784:578786] flutter: Amplify was already configured. Looks like app restarted on android/iOS.
```

**Comment by dnys1** [comment]
Hi @Sunsiha - thanks for sharing.

I missed this before, but you are calling signUp and then fetchAuthSession, but before calling fetchAuthSession, you must call signIn. So, signUp -> signIn -> fetchAuthSession is the correct workflow.

On iOS, you have an uncaught exception for trying to reconfigure Amplify. It's recommended that you wrap your `Amplify.configure` call in a try/catch block and only call it once from an `initState` call or similar mechanism.

**Comment by Sunsiha** [comment]
> Hi @Sunsiha - thanks for sharing.
> 
> I missed this before, but you are calling `signUp` and then `fetchAuthSession`, but before calling `fetchAuthSession`, you must call `signIn`. So, `signUp` -> `signIn` -> `fetchAuthSession` is the correct workflow.
> 
> On iOS, you have an uncaught exception for trying to reconfigure Amplify. It's recommended that you wrap your `Amplify.configure` call in a try/catch block and only call it once from an `initState` call or similar mechanism.

Yes I have done like ```signUp``` ->```confirmSignUp``` ->```signIn``` ->```fetchAuthSession```.

Now it's working as I expected. I was checking without signin will it work or not. I was aware this flow will work. Thanks.

**Comment by dnys1** [comment]
Glad to hear it!
