### ISSUE TITLE
Update password is not working, throwing error like failed since user is not authorized.

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#1282]
I have to change the password so am using the following code;
```
  await Amplify.Auth.updatePassword(
        newPassword: newPasswordController.text.trim().toString(),
        oldPassword: oldPasswordController.text.trim().toString(),
      );
```
Whenever I call this API am getting 'Failed since user is not authorized. Why it is happening like this?

```
NotAuthorizedException{message=Failed since user is not authorized., cause=com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: xxxxxx), recoverySuggestion=Check whether the given values are correct and the user is authorized to perform the operation.}
E/amplify:flutter:auth_cognito(17647): 	at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:103)
E/amplify:flutter:auth_cognito(17647): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$14.onError(AWSCognitoAuthPlugin.java:804)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.mobile.client.AWSMobileClient$19$1.onFailure(AWSMobileClient.java:2620)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.changePassword(CognitoUser.java:1391)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.mobile.client.AWSMobileClient$19.run(AWSMobileClient.java:2609)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito(17647): 	at java.lang.Thread.run(Thread.java:920)
E/amplify:flutter:auth_cognito(17647): Caused by: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: f17e8e16-e26b-491f-b21c-1a4c0870da47)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6779)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.changePassword(AmazonCognitoIdentityProviderClient.java:2352)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.changePasswordInternal(CognitoUser.java:1409)
E/amplify:flutter:auth_cognito(17647): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.changePassword(CognitoUser.java:1388)
E/amplify:flutter:auth_cognito(17647): 	... 3 more
I/flutter (17647): NotAuthorizedException(message: Failed since user is not authorized., recoverySuggestion: Check whether the given values are correct and the user is authorized to perform the operation., underlyingException: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID:xxxxxxx))
```
**Flutter details:**
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (3 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
````
**Cognito versions:**
```
amplify_flutter: ^0.2.10
amplify_auth_cognito: ^0.2.10
```

**Comment by dnys1** [comment]
Hi @Sunsiha  - can you confirm the user is signed in before calling this method, i.e. you have called `signIn` and the result returned showed success?

**Comment by Sunsiha** [comment]
> Hi @Sunsiha - can you confirm the user is signed in before calling this method, i.e. you have called `signIn` and the result returned showed success?

Yes already logged in. And using with that current token am able to call the other API's of ours. But when I call this change password am getting like this.

**Comment by Sunsiha** [comment]
@dnys1 weird now it's working. But I didn't do any changes in my code.

**Comment by Sunsiha** [comment]
@dnys1 related with this Update password when we update password is it possible to logout from all the devices if we logged in other device means?

**Comment by dnys1** [comment]
It is possible to logout all devices using global sign out: 

```dart
await Amplify.Auth.signOut(options: SignOutOptions(globalSignOut: true));
```

**Comment by Sunsiha** [comment]
> @dnys1 weird now it's working. But I didn't do any changes in my code.

@dnys1 sometime it's throwing error. Don't know which scenario. Like am doing the testing like used to login both mobile and web.

**Comment by Sunsiha** [comment]
> It is possible to logout all devices using global sign out:
> 
> ```dart
> await Amplify.Auth.signOut(options: SignOutOptions(globalSignOut: true));
> ```
```
AuthException{message=Failed to sign out globally, cause=java.lang.Exception: You must be signed-in with Cognito Userpools to be able to use getTokens, recoverySuggestion=See attached exception for more details}
at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$20.onError(AWSCognitoAuthPlugin.java:1099)
E/amplify:flutter:auth_cognito(27877): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:47)
E/amplify:flutter:auth_cognito(27877): 	at java.lang.Thread.run(Thread.java:920)
E/amplify:flutter:auth_cognito(27877): Caused by: java.lang.Exception: You must be signed-in with Cognito Userpools to be able to use getTokens
E/amplify:flutter:auth_cognito(27877): 	at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1915)
E/amplify:flutter:auth_cognito(27877): 	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
E/amplify:flutter:auth_cognito(27877): 	at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1875)
E/amplify:flutter:auth_cognito(27877): 	at com.amazonaws.mobile.client.AWSMobileClient$9.run(AWSMobileClient.java:1629)
E/amplify:flutter:auth_cognito(27877): 	at com.amazonaws.mobile.client.AWSMobileClient$9.run(AWSMobileClient.java:1624)
E/amplify:flutter:auth_cognito(27877): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
E/amplify:flutter:auth_cognito(27877): 	... 1 more
```

**Comment by dnys1** [comment]
You'll need to be signed in to be able to call that method. If you're wanting to sign out all devices without being signed in, you can use the AWS SDK.

**Comment by dnys1** [comment]
> > @dnys1 weird now it's working. But I didn't do any changes in my code.
> 
> @dnys1 sometime it's throwing error. Don't know which scenario. Like am doing the testing like used to login both mobile and web.

Are you still experiencing the error when calling `updatePassword`?

**Comment by dnys1** [comment]
Closing for now. Please let me know if you continue to experience this issue.
