### ISSUE TITLE
InvalidSmsRoleTrustRelationshipException import auth using custom user pools

### ISSUE THREAD

**Issue by dfourcfive** [aws-amplify/amplify-flutter#1328]
i have set up my own cognito user pool 
created the identity pools
set up my own roles and policies for authenticated and unauthenticated users
and used the user pool with amplify import auth
and when i do call the confirm sign up i encounter this error

note : i have edited the trust relationship to the following json 
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "cognito-idp.amazonaws.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "cognito-identity.amazonaws.com:aud": "*"
        },
        "ForAnyValue:StringLike": {
          "cognito-identity.amazonaws.com:amr": "authenticated"
        }
      }
    }
  ]
}
```
and added this sns policy 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sns:publish"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
```debug
E/amplify:flutter:auth_cognito(30931): AuthException{message=Sign up failed, cause=com.amazonaws.services.cognitoidentityprovider.model.InvalidSmsRoleTrustRelationshipException: Role does not have a trust relationship allowing Cognito to assume the role (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidSmsRoleTrustRelationshipException; Request ID: 502a9ae2-186f-47f6-bb40-71706adba9af), recoverySuggestion=See attached exception for more details.}
E/amplify:flutter:auth_cognito(30931): 	at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:126)
E/amplify:flutter:auth_cognito(30931): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onError(AWSCognitoAuthPlugin.java:315)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```• No issues found!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.0)
[√] Android Studio
[√] VS Code (version 1.63.2)
[√] Connected device (4 available)```

</details>



**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi note 9 pro]

**Comment by cshfang** [comment]
Hiya @dfourcfive. Are you able to reproduce this error in any other platform besides Android through Flutter? Could you also help me understand how you configured Amplify as well? Did you import your user pool via the CLI (https://docs.amplify.aws/lib/auth/existing-resources/q/platform/flutter/) or manually configure your `amplifyconfiguration.dart` file?

**Comment by dfourcfive** [comment]
@cshfang  no i haven't tested in other platform(only android) and not willing to , yes i have used the user pool via the CLI as i mentioned in the issue using 'Amplify import auth' and then selecting user pool with identity pool and selected the one i created .

**Comment by HuiSF** [comment]
Hi @dfourcfive 

After you making the userpool by yourself, have you tested and validated the roles, policies are actually working as your expectation in general (e.g. without Amplify)?

I did some research on this specific error, this specific error is mostly caused by misconfiguration on the roles. Amplify just follows your configuration and doesn't do anything else.

**Comment by dfourcfive** [comment]
@HuiSF  i have tested the policies using the simulation tool provided in the console , i added the different policies for the authenticated and unauthenticated users and made sure to include cognito,sns,datastore,api policies , i am not sure what I'm missing for the moment.

**Comment by HuiSF** [comment]
I found some relevant post,  give it try you haven't yet.
https://stackoverflow.com/questions/56595273/aws-cognito-iam-invalidsmsroletrustrelationshipexception-role-does-not-have-a

**Comment by Jordan-Nelson** [comment]
@dfourcfive - Have you had a chance to look at @HuiSF's suggestion above? Please let us know if you are still experiencing this issue.
