### ISSUE TITLE
JSON-Parsing of PasswordProtectionSettings does not work.

### ISSUE THREAD

**Issue by CoachBenedetto** [aws-amplify/amplify-flutter#1358]
**Description**

When trying to initialize Amplify and add the AmplifyAuthCognito Plugin, an error occurs in reading the passwordPolicyMinLength value from the config JSON.

This is caused by the value being stored as a String within config JSONs but the autogenerated converter class expects an Int? value instead. Therefore, either the converter/class has to be fixed or the value has to be stored as an Int.

Based on the problem being dependent on auto-generated JSON converters, it is likely that comparable problems may occur in other cases, too.

**Output/Log**

`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'String' is not a subtype of type 'int?' in type cast
#0      _$PasswordProtectionSettingsFromJson (package:amplify_flutter/src/config/auth/cognito/password_protection_settings.g.dart:27:64)
#1      new PasswordProtectionSettings.fromJson (package:amplify_flutter/src/config/auth/cognito/password_protection_settings.dart:39:7)
#2      _$CognitoAuthConfigFromJson (package:amplify_flutter/src/config/auth/cognito/auth.g.dart:45:40)
#3      new CognitoAuthConfig.fromJson (package:amplify_flutter/src/config/auth/cognito/auth.dart:76:7)
#4      _$CognitoPluginConfigFromJson.<anonymous closure> (package:amplify_flutter/src/config/auth/cognito_config.g.dart:49:37)
#5      _$AWSConfigMapFromJson.<anonymous closure> (package:amplify_flutter/src/config/config_map.g.dart:30:40)
#6      MapMixin.map (dart:collection/maps.dart:170:28)
#7      _$AWSConfigMapFromJson (package:amplify_flutter/src/config/config_map.g.dart:29:49)
#8      new AWSConfigMap.fromJs<…>`

**To Reproduce**

1. Set up flutter amplify project with AmplifyAuthCognito
2. Initialize Amplify in App and add AmplifyPlugin AmplifyAuthCognito
3. Run App so it calls the implemented Amplify Initialization

**Expected behavior**

Correct parsing of the configuration.

**Platform**

[x] Android
[x] iOS

**Comment by CoachBenedetto** [comment]
Already fixed through Pull Request
