### ISSUE TITLE
Cannot SignUp (AMPLIFY_SIGNUP_FAILED)

### ISSUE THREAD

**Issue by deimantasa** [aws-amplify/amplify-flutter#144]
**Describe the bug**
After running into issues in #142 and #143, trying to SignUp and receiving null-pointer.

**To Reproduce**
1. Run the app;
2. Execute SignUp
3. Receive error
```
E/amplify:flutter:auth_cognito( 8525): AmplifyException {message=Sign up failed, cause=java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(java.lang.String, java.lang.String, com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserAttributes, java.util.Map, java.util.Map, com.amazonaws.mobileconnectors.cognitoidentityprovider.handlers.SignUpHandler)' on a null object reference, recoverySuggestion=See attached exception for more details}
E/amplify:flutter:auth_cognito( 8525): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onError(AWSCognitoAuthPlugin.java:275)
E/amplify:flutter:auth_cognito( 8525): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito( 8525): 	at com.amazonaws.mobile.client.internal.InternalCallback.access$000(InternalCallback.java:34)
E/amplify:flutter:auth_cognito( 8525): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:103)
E/amplify:flutter:auth_cognito( 8525): 	at java.lang.Thread.run(Thread.java:919)
E/amplify:flutter:auth_cognito( 8525): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(java.lang.String, java.lang.String, com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserAttributes, java.util.Map, java.util.Map, com.amazonaws.mobileconnectors.cognitoidentityprovider.handlers.SignUpHandler)' on a null object reference
E/amplify:flutter:auth_cognito( 8525): 	at com.amazonaws.mobile.client.AWSMobileClient$13.run(AWSMobileClient.java:2003)
E/amplify:flutter:auth_cognito( 8525): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito( 8525): 	... 1 more
```

**Expected behavior**
There shouldn't be an exception.

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Smartphone (please complete the following information):**
OnePlus 6

**Additional context**
I expect this issue is related to issues received in #142 and/or #143 and once these are fixed - this also will be fixed. I tried to debug internally, but couldn't see exactly why `nullpointer` is thrown.

**Comment by rubana28** [comment]
@deimantasa  hey! do you have any update on this issue? have you found out the reason behind this issue and the solution ? kindly can you share with me?

**Comment by deimantasa** [comment]
Hello @rubana28 , no, unfortunately. We've decided to drop AWS Amplify as it was not up-to our expectation.

**Comment by veve90** [comment]
I have the same error here , I would be keen to understand why

**Comment by abdallahshaban557** [comment]
@veve90  - Can you please submit a new issue for us to investigate what is happening with you rapp?
