### ISSUE TITLE
[Feedback]The ToDo App can't build as release

### ISSUE THREAD

**Issue by SamuelAc1011** [aws-amplify/amplify-flutter#1547]
**Page**: [`/start/getting-started/nextsteps/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/flutter)

```
E/AndroidRuntime(13643): FATAL EXCEPTION: RxCachedThreadScheduler-6
E/AndroidRuntime(13643): Process: com.example.todo_app, PID: 13643
E/AndroidRuntime(13643): g.b.a.c.i: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.IllegalAccessError: Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'g.b.a.e.e.e.i' (declaration of 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' appears in base.apk)
E/AndroidRuntime(13643):        at g.b.a.g.a.f(:2)
E/AndroidRuntime(13643):        at g.b.a.a.p.run(Unknown Source:19)
E/AndroidRuntime(13643):        at g.b.a.e.g.n.run(Unknown Source:21)
E/AndroidRuntime(13643):        at g.b.a.e.g.n.call(Unknown Source:0)
E/AndroidRuntime(13643):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(13643):        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AndroidRuntime(13643):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(13643):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(13643):        at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(13643): Caused by: java.lang.IllegalAccessError: Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'g.b.a.e.e.e.i' (declaration of 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' appears in base.apk)
E/AndroidRuntime(13643):        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.l(Unknown Source:41)
E/AndroidRuntime(13643):        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.m(Unknown Source:0)
E/AndroidRuntime(13643):        at com.amplifyframework.datastore.syncengine.U0.a(Unknown Source:11)
E/AndroidRuntime(13643):        at g.b.a.e.e.e.j.r(Unknown Source:10)
E/AndroidRuntime(13643):        at g.b.a.a.k.f(Unknown Source:5)
E/AndroidRuntime(13643):        at g.b.a.e.e.e.l.r(Unknown Source:17)
E/AndroidRuntime(13643):        at g.b.a.a.k.f(Unknown Source:5)
E/AndroidRuntime(13643):        at g.b.a.e.e.e.J.run(Unknown Source:6)
E/AndroidRuntime(13643):        at g.b.a.a.p.run(Unknown Source:9)
```

**Comment by cshfang** [comment]
@SamuelAc1011 @miguemcunha we've updated the sample Todo App referenced by the link above. Could someone try it out? I believe there was a bug that was fixed and the updated app should contain that fix now.

**Comment by SamuelAc1011** [comment]
> @SamuelAc1011 @miguemcunha we've updated the sample Todo App referenced by the link above. Could someone try it out? I believe there was a bug that was fixed and the updated app should contain that fix now.

Sure, I'll check it out in a few hours.

**Comment by SamuelAc1011** [comment]
@cshfang  I finished the Todo tutorial and everything is fine now, the release version is working in flutter 2.10.3, there's some issues in the tutorial explanation but nothing that can't solve with the debug console messages.
