### ISSUE TITLE
extending FlutterFragmentActivity crashes App on reopen

### ISSUE THREAD

**Issue by Rayv1** [aws-amplify/amplify-flutter#168]
Hi,

iam using the [local_auth](https://pub.dev/packages/local_auth) Plugin from flutter Team, which requires FlutterFragmentActivity instead of FlutterActivity in the MainAcitivity.kt File. When extending this Class the first Open of the App works fine.  
When putting the app in the Background (not full close) and reopen it, its crashing with the following Error:
```
D/AndroidRuntime(23077): Shutting down VM
E/AndroidRuntime(23077): FATAL EXCEPTION: main
E/AndroidRuntime(23077): Process: com.example.test2, PID: 23077
E/AndroidRuntime(23077): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(23077): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
E/AndroidRuntime(23077): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(23077): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(23077): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23077): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(23077): 	... 1 more
E/AndroidRuntime(23077): Caused by: AmplifyException {message=Category auth has already been configured or is configuring., cause=null, recoverySuggestion=Make sure that you have added all plugins before attempting configuration.}
E/AndroidRuntime(23077): 	at com.amplifyframework.core.category.Category.addPlugin(Category.java:152)
E/AndroidRuntime(23077): 	at com.amplifyframework.core.Amplify.updatePluginRegistry(Amplify.java:202)
E/AndroidRuntime(23077): 	at com.amplifyframework.core.Amplify.addPlugin(Amplify.java:159)
E/AndroidRuntime(23077): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.onAttachedToEngine(AuthCognito.kt:92)
E/AndroidRuntime(23077): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java:133)
E/AndroidRuntime(23077): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:16)
E/AndroidRuntime(23077): 	at com.example.test2.MainActivity.configureFlutterEngine(MainActivity.kt:11)
E/AndroidRuntime(23077): 	at io.flutter.embedding.android.FlutterFragment.configureFlutterEngine(FlutterFragment.java:950)
E/AndroidRuntime(23077): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:181)
E/AndroidRuntime(23077): 	at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:582)
E/AndroidRuntime(23077): 	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2574)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:828)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
D/EGL_emulation(23077): eglMakeCurrent: 0xea97fb80: ver 2 0 (tinfo 0xd770f530)
D/AndroidRuntime(23077): Shutting down VM
E/AndroidRuntime(23077): FATAL EXCEPTION: main
E/AndroidRuntime(23077): Process: com.example.test2, PID: 23077
E/AndroidRuntime(23077): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(23077): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
E/AndroidRuntime(23077): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
E/AndroidRuntime(23077): 	at android.app.Activity.performStart(Activity.java:7825)
E/AndroidRuntime(23077): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
E/AndroidRuntime(23077): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(23077): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(23077): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(23077): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(23077): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(23077): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(23077): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(23077): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(23077): 	... 3 more
```

This Bug happens not if using FlutterActivity.

**To Reproduce**
Just added this Code with Default APP:

```
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_core/amplify_core.dart';
import 'package:flutter/material.dart';

import 'amplifyconfiguration.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Amplify amplify = Amplify();

  void initState() {
    // TODO: implement initState
    super.initState();
    _initAmplifyFlutter();
  }

  void _initAmplifyFlutter() async {
    if (!mounted) return;
    print("init amplify");
    AmplifyAuthCognito auth = AmplifyAuthCognito();

    amplify.addPlugin(
      authPlugins: [auth],
    );
    // Initialize AmplifyFlutter
    try {
      await amplify.configure(amplifyconfig);
    } catch (e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) => Scaffold(body: Text("test"));
}
```
Pubspec.yaml dependencies only contains:
  amplify_core: ^0.0.1-dev.3 
  amplify_auth_cognito: ^0.0.1-dev.

**Platform**

[x] Android (Happens on different Hardware and virtual Device )
[] iOS

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S8]
 - OS: [Android 9 ]

If you need more Information, just let me know.

**Comment by Rayv1** [comment]
My MainActivity.kt:

```
package com.example.test2
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

**Comment by fjnoyp** [comment]
Hi @Rayv1 it looks like the exception is caused by calling Amplify.configure a second time.  Can you try adding a boolean "isInitialized" that is set to true once you call configure, this way your code shouldn't call it a second time and trigger the exception.

**Comment by Rayv1** [comment]
@fjnoyp i will check it later and give you a short Feedback

**Comment by Rayv1** [comment]
Yep, i checked if amplify is already configured and the error is gone
