### ISSUE TITLE
Cannot redirect back to my app after signing in in Google with signInWithWebUI

### ISSUE THREAD

**Issue by ben-the-developer** [aws-amplify/amplify-flutter#2013]
Hi there, I am having an issue of redirecting back to my app after signing in with social sign in (google in particular) in Android emulator. I searched in the issues but could not find any related questions so I guess there is some configuration issues I could not figure out. I hope I can get some clue to identify/fix the issue.

I tried version 0.6.5 and 1.0.0-next.0+1. My flutter version is 3.0.5. I do not setup the amplify backend in AWS. I define my own awsconfiguration.json file manually with an existing cognito user pool and identify pool

The observation I have is as follow. 

![image](https://user-images.githubusercontent.com/106507310/183272119-c9725f48-be1c-40ad-8858-c9cee5575256.png)

**How did I get this image?**

1. Wipe data of an Android emulator with Android Studio
2. Run my app
3. Click the `Sign In With Google` button, which will call `signInWithWebUI` function.
4. The google web page is shown and asks me to enter my credential
5. I enter my user email and password and click the next button after entering the password

**Configuration Files**

awsconfiguration.json file

```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
      "plugins": {
          "awsCognitoAuthPlugin": {
              "IdentityManager": {
                  "Default": {}
              },
              "CredentialsProvider": {
                  "CognitoIdentity": {
                      "Default": {
                          "PoolId": "<pool-id>",
                          "Region": "<region>"
                      }
                  }
              },
              "CognitoUserPool": {
                  "Default": {
                      "PoolId": "$podId",
                      "AppClientId": "$appClientId",
                      "Region": "<region>"
                  }
              },
              "GoogleSignIn": {
                  "Permissions": "email,profile,openid",
                  "ClientId-WebApp": "<client-id-webapp>.apps.googleusercontent.com",
                  "ClientId-iOS": "<client-id-ios>.apps.googleusercontent.com",
                  "ClientId-Android": "<client-id-android>.apps.googleusercontent.com"
              },
              "Auth": {
                  "Default": {
                      "OAuth": {
                            "WebDomain": "<user-pool-url-without-https>",
                            "AppClientId": "$appClientId",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                      },
                      "authenticationFlowType": "USER_SRP_AUTH"
                  }
              }
          }
      }
  }
}
```

AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="package-name">
<queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>
   <application
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:requestLegacyExternalStorage="true">
        ...
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:exported="true">
            ...
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp" />
            </intent-filter>
        </activity>
   </application>
   ...
</manifest>
```

Cognito user pool App client settings

![image](https://user-images.githubusercontent.com/106507310/183272427-082916e5-7b2e-4875-a168-953b1e367e70.png)

**Comment by dnys1** [comment]
Hi @ben-the-developer, sorry you are facing this issue. Can you confirm in your amplifyconfiguration you have `myapp://` listed for the redirect URIs? The config listed above shows `mypp://`

**Comment by ben-the-developer** [comment]
Hi @dnys1 , sorry for the typo. I just confirmed it's `myapp` in `awsconfiguration.json`, `AndroidManifest.xml` and cognito.

**Comment by Jordan-Nelson** [comment]
Hi @ben-the-developer - Can you confirm you have followed all the steps [here](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/) for Google sign-in to configure this in the Google cloud console?

**Comment by ben-the-developer** [comment]
Hi @Jordan-Nelson , I believe I have followed all the steps, except for running the `amplify add auth`. I do not use the backend in AWS. The reason is because after I get stuck in the following image

![image](https://user-images.githubusercontent.com/106507310/183442445-39d6b5ac-b4d2-4e36-a0f3-9a647f827d71.png)

I tried to restart the application (terminate the application in vscode and restart again without wiping data), I can then get the detail of the user I just signed in (I guess in this scenario, the redirection works? or maybe there is no redirection in this scenario?).

Some important configuration in the Google
![image](https://user-images.githubusercontent.com/106507310/183443076-4d14318d-3571-41dd-9cb3-2c8d605a8a4b.png)
![image](https://user-images.githubusercontent.com/106507310/183443269-638d2a72-96ea-40dd-b135-d60a74fdc956.png)
![image](https://user-images.githubusercontent.com/106507310/183443879-46325379-e666-4a59-ba16-3258036c5ab4.png)

**Comment by ben-the-developer** [comment]
Hi @Jordan-Nelson , got some more information. I inspect the web browser in the emulator and got this. Not sure if this could be the cause. But not sure how to unblock.

![image](https://user-images.githubusercontent.com/106507310/183467900-e23d05ba-9bd7-42e7-a797-6a464bccdfb5.png)

**Comment by dnys1** [comment]
Which Amplify version is that for? In order for this to work on the stable version (0.6.5), the AndroidManifest.xml needs to be slightly different, as specified [here](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/#android-platform-setup) (the intent-filter is on a different activity). However, for the dev-preview release (1.0.0-next.0+1), the AndroidManifest you posted above looks correct.

**Comment by dnys1** [comment]
In the dev-preview version, there should be several debug messages printed in the console which look like this:

```
D/AmplifyHostedUiPlugin( 5195): onNewIntent: Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=myapp:// flg=0x14000000 cmp=com.amazonaws.amplify.amplify_auth_cognito_example/.MainActivity (has extras) }
D/AmplifyHostedUiPlugin( 5195): onActivityResult: 8888, 0
D/AmplifyHostedUiPlugin( 5195): cancelCurrentOperation
```

Would you be able to post your full logs here so we can see if those provide any insight?

**Comment by ben-the-developer** [comment]
Hi @dnys1 , I am using the dev preview version.

Here is the log for two scenarios. I find the debug message at the end of the second scenario (after signing in), rather than the first one.

<details>
  <summary>Sign in for the first time after wiping data</summary>
  
```
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
√  Built build\app\outputs\flutter-apk\app-development-debug.apk.
D/FlutterGeolocator( 7101): Attaching Geolocator to activity
W/FlutterActivityAndFragmentDelegate( 7101): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
D/FlutterGeolocator( 7101): Creating service.
D/FlutterGeolocator( 7101): Binding to location service.
D/FlutterGeolocator( 7101): Geolocator foreground service connected
D/FlutterGeolocator( 7101): Initializing Geolocator services
Connecting to VM Service at ws://127.0.0.1:53285/veB2qFLXjHs=/ws
[GETX] Instance "EnvironmentVariableService" has been created
[GETX] Instance "EnvironmentVariableService" has been initialized
[GETX] Instance "CognitoUserPool" has been created
[GETX] Instance "AmplifyWrapperService" has been created
[GETX] Instance "AmplifyWrapperService" has been initialized
W/ch.myapp( 7101): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/AndroidKeysetManager( 7101): keyset not found, will generate a new one
W/AndroidKeysetManager( 7101): java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
W/AndroidKeysetManager( 7101): 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:123)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.EncryptedKeyValueRepository.getSharedPreferences(EncryptedKeyValueRepository.kt:48)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.EncryptedKeyValueRepository.get(EncryptedKeyValueRepository.kt:38)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.AmplifySecureStoragePlugin.read(AmplifySecureStoragePlugin.kt:46)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.Messages$AmplifySecureStorageApi.lambda$setup$0(Messages.java:88)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.-$$Lambda$Messages$AmplifySecureStorageApi$RsoTfIgCCtZTCpE1-9pwaCvjCVU.onMessage(Unknown Source:2)
W/AndroidKeysetManager( 7101): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0$DartMessenger$SerialTaskQueue(DartMessenger.java:163)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$SerialTaskQueue$F0iXMzLdPiwUET1ugdCo3vpOFvI.run(Unknown Source:2)
W/AndroidKeysetManager( 7101): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/AndroidKeysetManager( 7101): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/AndroidKeysetManager( 7101): 	at java.lang.Thread.run(Thread.java:764)
W/AndroidKeysetManager( 7101): keyset not found, will generate a new one
W/AndroidKeysetManager( 7101): java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_value_keyset__ does not exist
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
W/AndroidKeysetManager( 7101): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
W/AndroidKeysetManager( 7101): 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:128)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.EncryptedKeyValueRepository.getSharedPreferences(EncryptedKeyValueRepository.kt:48)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.EncryptedKeyValueRepository.get(EncryptedKeyValueRepository.kt:38)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.AmplifySecureStoragePlugin.read(AmplifySecureStoragePlugin.kt:46)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.Messages$AmplifySecureStorageApi.lambda$setup$0(Messages.java:88)
W/AndroidKeysetManager( 7101): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.-$$Lambda$Messages$AmplifySecureStorageApi$RsoTfIgCCtZTCpE1-9pwaCvjCVU.onMessage(Unknown Source:2)
W/AndroidKeysetManager( 7101): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0$DartMessenger$SerialTaskQueue(DartMessenger.java:163)
W/AndroidKeysetManager( 7101): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$SerialTaskQueue$F0iXMzLdPiwUET1ugdCo3vpOFvI.run(Unknown Source:2)
W/AndroidKeysetManager( 7101): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/AndroidKeysetManager( 7101): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/AndroidKeysetManager( 7101): 	at java.lang.Thread.run(Thread.java:764)
I/EngineFactory( 7101): Provider GmsCore_OpenSSL not available
[GETX] Instance "CognitoService" has been created
[GETX] Instance "CognitoService" has been initialized
[GETX] Instance "NotificationService" has been created
[GETX] Instance "Client" has been created
[GETX] GetDelegate is created !
[GETX] GetInformationParser is created !
[GETX] GetInformationParser: route location: /
[GETX] GOING TO ROUTE /
[GETX] Instance "LandingPageController" has been created
[GETX] Instance "LandingPageController" has been initialized
D/eglCodecCommon( 7101): setVertexArrayObject: set vao to 0 (0) 0 0
[GETX] GOING TO ROUTE /settings
[GETX] "LandingPageController" onDelete() called
[GETX] "LandingPageController" deleted from memory
[GETX] GOING TO ROUTE /settings-home
[GETX] Instance "SettingsPageService" has been created
[GETX] Instance "SettingsPageService" has been initialized
[GETX] Instance "SettingsPageController" has been created
[GETX] Instance "UserService" has been created
[GETX] Instance "UserService" has been initialized
[GETX] Instance "SettingsPageController" has been initialized
[GETX] "ViewInListWidgetController" onDelete() called
[GETX] "ViewInListWidgetController" deleted from memory
[GETX] GOING TO ROUTE /sign-in
[GETX] Instance "SignInPageController" has been created
[GETX] Instance "SignInPageController" has been initialized
I/ch.myapp( 7101): Background concurrent copying GC freed 64279(3MB) AllocSpace objects, 18(872KB) LOS objects, 34% free, 11MB/17MB, paused 4.115ms total 156.368ms
D/EGL_emulation( 7101): eglMakeCurrent: 0xd0da24a0: ver 2 0 (tinfo 0xd0d253e0)
```
</details>


<details>
  <summary>Restart the app and sign in again without wiping data</summary>
```
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
√  Built build\app\outputs\flutter-apk\app-development-debug.apk.
D/FlutterGeolocator(14573): Attaching Geolocator to activity
W/FlutterActivityAndFragmentDelegate(14573): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
D/FlutterGeolocator(14573): Creating service.
D/FlutterGeolocator(14573): Binding to location service.
D/FlutterGeolocator(14573): Geolocator foreground service connected
D/FlutterGeolocator(14573): Initializing Geolocator services
Connecting to VM Service at ws://127.0.0.1:56998/gyJePI1BOxE=/ws
[GETX] Instance "EnvironmentVariableService" has been created
[GETX] Instance "EnvironmentVariableService" has been initialized
[GETX] Instance "CognitoUserPool" has been created
[GETX] Instance "AmplifyWrapperService" has been created
[GETX] Instance "AmplifyWrapperService" has been initialized
W/ch.myapp(14573): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
I/EngineFactory(14573): Provider GmsCore_OpenSSL not available
[GETX] Instance "CognitoService" has been created
[GETX] Instance "CognitoService" has been initialized
[GETX] Instance "NotificationService" has been created
[GETX] Instance "Client" has been created
[GETX] GetDelegate is created !
[GETX] GetInformationParser is created !
[GETX] GetInformationParser: route location: /
[GETX] GOING TO ROUTE /
[GETX] Instance "LandingPageController" has been created
[GETX] Instance "LandingPageController" has been initialized
D/eglCodecCommon(14573): setVertexArrayObject: set vao to 0 (0) 0 0
[GETX] GOING TO ROUTE /settings
[GETX] "LandingPageController" onDelete() called
[GETX] "LandingPageController" deleted from memory
[GETX] GOING TO ROUTE /settings-home
[GETX] Instance "SettingsPageService" has been created
[GETX] Instance "SettingsPageService" has been initialized
[GETX] Instance "SettingsPageController" has been created
[GETX] Instance "UserService" has been created
[GETX] Instance "UserService" has been initialized
[GETX] Instance "SettingsPageController" has been initialized
[GETX] "ListPostsPageController" onDelete() called
[GETX] "ListPostsPageController" deleted from memory
[GETX] "ViewInListWidgetController" onDelete() called
[GETX] "ViewInListWidgetController" deleted from memory
[GETX] GOING TO ROUTE /sign-in
[GETX] Instance "SignInPageController" has been created
[GETX] Instance "SignInPageController" has been initialized
I/ch.myapp(14573): Background concurrent copying GC freed 67259(3MB) AllocSpace objects, 22(824KB) LOS objects, 35% free, 11MB/17MB, paused 418us total 200.474ms
D/EGL_emulation(14573): eglMakeCurrent: 0xc582a960: ver 2 0 (tinfo 0xc8f32ea0)
E/eglCodecCommon(14573): goldfish_dma_create_region: could not obtain fd to device! fd 0 errno=11
D/AmplifyHostedUiPlugin(14573): onActivityResult: 8888, 0
D/AmplifyHostedUiPlugin(14573): onNewIntent: Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=myapp://?code=8f33ead3-63ba-4943-94bb-0c4db4c0cdd8&state=Cc1RdC380NF-4gVk3PRJF2hItKe8EfW0 flg=0x14000000 cmp=au.com.bayestech.myapps/.MainActivity (has extras) }
D/EGL_emulation(14573): eglMakeCurrent: 0xe80c0ba0: ver 2 0 (tinfo 0xe0eddb30)
D/EGL_emulation(14573): eglMakeCurrent: 0xe80c0ba0: ver 2 0 (tinfo 0xe0eddb30)
D/EGL_emulation(14573): eglMakeCurrent: 0xc582a960: ver 2 0 (tinfo 0xc8f32ea0)
D/AmplifyHostedUiPlugin(14573): cancelCurrentOperation
```
</details>

**Comment by dnys1** [comment]
Interesting, thanks for sharing that. Which version of Android is your emulator running? And is this with the Chrome browser on the emulator?

**Comment by ben-the-developer** [comment]
I am using Pixel 4 API 28 and Nexus 10 API 30.

**Comment by ben-the-developer** [comment]
Hi @dnys1 , while investigating the issue, I come across this article https://stackoverflow.com/questions/46727850/navigation-is-blocked-error-in-chrome-61-on-android?noredirect=1&lq=1. The chrome version in Pixel 4 API 28 in the emulator is 69. I created another emulator Pixel 4 API 33 with chrome 101, seems like it's working.

One more observation, in my AndroidManifest.xml, originally, I have

```
<queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>
```

and there is no error for Pixel 4 API 28.

When I use Pixel 4 API 33, I got an error saying only one action is allowed in intent. So I changed it to
```
<queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>
```

Seems like it's Chrome bug?

**Comment by dnys1** [comment]
Oh wow, great find! Thank you! I'll dig in some more to see if we can get a workaround in place for older Chromes.

**Comment by ben-the-developer** [comment]
Thank you @dnys1. It will be great to see amplify flutter works with older Chromes. I will leave this issue open until you get some more insights. Or feel free to close the issue if it is considered as solved based on your policy.

**Comment by dnys1** [comment]
So I've tried now with a few different emulators going back to API level 24 and haven't been able to reproduce it yet. Would you be willing to send me your full AndroidManifest.xml? I wonder if there's some other setting which might be interfering with the redirect on older platforms.

**Comment by ben-the-developer** [comment]
Hi @dnys1 , thank you for helping to investigate it. Here is the full AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myapp">
    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>
   <application
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:requestLegacyExternalStorage="true">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:exported="true">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <!--TODO: Add this filter, if you want to support sharing images into your app-->
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="image/*" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.SEND_MULTIPLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="image/*" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="myapp" />
            </intent-filter>
        </activity>
       <activity
           android:name="com.yalantis.ucrop.UCropActivity"
           android:screenOrientation="portrait"
           android:theme="@style/Theme.AppCompat.Light.NoActionBar"
           android:exported="false"/>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    <meta-data android:name="com.google.android.geo.API_KEY"
               android:value="my-google-api-key"/>
    </application>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-feature android:name="android.hardware.camera" android:required="true" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
</manifest>
```

**Comment by dnys1** [comment]
I was able to finally reproduce this. This seems to only be an error for Chrome versions <71 and Google Sign In, since it depends on how the OAuth provider is handling the redirect. For example, Login with Amazon works on all versions of Chrome with no problems. There is a small issue I discovered with Android 7 which I put up a fix for, but this was related to Android itself not necessarily Chrome.

Since Chrome 71+ is available on Android 9 (API 28), I think simply updating Chrome is the preferred fix. From what I could find, there is no real fix for this since it is an issue in Chrome itself :/

Hope this helps, and thank you for all your help getting to the bottom of this!

**Comment by ben-the-developer** [comment]
Thank you @dnys1 for spending time to investigate the issue. Your recommendation definitely helps. Thanks again for your patient and advice.

**Comment by saswat-pcode** [comment]
Hi we have multiple sign in url.
<img width="701" alt="Screenshot 2022-09-01 at 11 04 18 AM" src="https://user-images.githubusercontent.com/110592349/187842002-4ba73951-ea67-42dd-a23d-d0611c3dba82.png">

when i am trying with google login it is through the error 

https://imgur.com/a/BqMN46f

aws config file

https://imgur.com/eCTPXmn

Android manifest file

https://imgur.com/I8VxRoi


How to resolve this issue ?
For single url that is working.
