### ISSUE TITLE
ERROR | SignInStateMachine | Emitted error: Tried to build class "CognitoUser" but nested builder for field "deviceSecrets" threw: Tried to construct class "CognitoDeviceSecrets" with null field "deviceGroupKey". This is forbidden; to allow it, mark "deviceGroupKey" with @nullable.

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#2029]
### Description

Upto yesterday  evening I was able to login through web and mobile. Today when am trying to login in flutter web and mobile am getting this kind of error. 
```
  amplify_flutter: ^1.0.0-next.0+1
  amplify_auth_cognito: ^1.0.0-next.0+2
  amplify_api: ^1.0.0-next.0+1
```
```
I/s.ai.enterpris( 8905): Waiting for a blocking GC ProfileSaver
I/s.ai.enterpris( 8905): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 20.695ms
I/flutter ( 8905): ERROR | SignInStateMachine | Emitted error: Tried to build class "CognitoUser" but nested builder for field "deviceSecrets" threw: Tried to construct class "CognitoDeviceSecrets" with null field "deviceGroupKey". This is forbidden; to allow it, mark "deviceGroupKey" with @nullable.
I/flutter ( 8905): #0      CognitoUserBuilder._build (package:amplify_auth_cognito_dart/src/model/cognito_user.g.dart:188:9)
I/flutter ( 8905): #1      CognitoUserBuilder.build (package:amplify_auth_cognito_dart/src/model/cognito_user.g.dart:160:26)
I/flutter ( 8905): #2      SignInStateMachine._processChallenge (package:amplify_auth_cognito_dart/src/state/machines/sign_in_state_machine.dart:725:39)
I/flutter ( 8905): <asynchronous suspension>
I/flutter ( 8905): #3      SignInStateMachine.run (package:amplify_auth_cognito_dart/src/state/machines/sign_in_state_machine.dart:633:23)
I/flutter ( 8905): <asynchronous suspension>
I/flutter ( 8905): #4      SignInStateMachine.resolve (package:amplify_auth_cognito_dart/src/state/machines/sign_in_state_machine.dart:804:9)
I/flutter ( 8905): <asynchronous suspension>
I/flutter ( 8905): #5      StateMachine._listenForEvents (package:amplify_core/src/state_mac
E/flutter ( 8905): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Tried to build class "CognitoUser" but nested builder for field "deviceSecrets" threw: Tried to construct class "CognitoDeviceSecrets" with null field "deviceGroupKey". This is forbidden; to allow it, mark "deviceGroupKey" with @nullable.
E/flutter ( 8905): #0      CognitoUserBuilder._build (package:amplify_auth_cognito_dart/src/model/cognito_user.g.dart:188:9)
E/flutter ( 8905): #1      CognitoUserBuilder.build (package:amplify_auth_cognito_dart/src/model/cognito_user.g.dart:160:26)
E/flutter ( 8905): #2      SignInStateMachine._processChallenge (package:amplify_auth_cognito_dart/src/state/machines/sign_in_state_machine.dart:725:39)
E/flutter ( 8905): <asynchronous suspension>
E/flutter ( 8905): #3      SignInStateMachine.run (package:amplify_auth_cognito_dart/src/state/machines/sign_in_state_machine.dart:633:23)
E/flutter ( 8905): <asynchronous suspension>
E/flutter ( 8905): #4      SignInStateMachine.resolve (package:amplify_auth_cognito_dart/src/state/machines/sign_in_state_machine.dart:804:9)
E/flutter ( 8905): <asynchronous suspension>
E/flutter ( 8905): #5      StateMachine._listenForEvents (package:amplify_core/src/state_machine/state_machine.dart:171:9)
E/flutter ( 8905): <asynchronous suspension>
E/flutter ( 8905): 
```

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.2)
[✓] Connected device (3 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

### Dependencies

```bash
Dart SDK 2.17.5
Flutter SDK 3.0.4
dsaas 1.0.0+1

dependencies:
- amplify_api 1.0.0-next.0+1 [amplify_api_android amplify_api_ios amplify_core amplify_flutter aws_common collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 1.0.0-next.0+4 [amplify_auth_cognito_android amplify_auth_cognito_dart amplify_auth_cognito_ios amplify_core amplify_flutter amplify_secure_storage async flutter flutter_web_plugins meta path plugin_platform_interface]
- amplify_flutter 1.0.0-next.0+1 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_secure_storage aws_common collection flutter meta plugin_platform_interface]
- bloc 7.2.1 [meta]
- chewie 1.3.4 [cupertino_icons flutter provider video_player wakelock]
- connectivity_plus 2.3.6+1 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- device_info 2.0.3 [flutter device_info_platform_interface]
- dio 4.0.6 [http_parser path]
- dotted_border 2.0.0+2 [flutter path_drawing]
- dropdown_button2 1.7.1 [flutter]
- equatable 2.0.3 [collection meta]
- file_picker 5.0.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.4.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 7.3.3 [flutter bloc provider]
- flutter_email_sender 5.1.0 [flutter]
- flutter_html 3.0.0-alpha.5 [html csslib collection numerus flutter]
- flutter_inappwebview 5.4.3+7 [flutter]
- flutter_local_notifications 9.7.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_phone_direct_caller 2.1.1 [flutter]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_screenutil 5.5.3+2 [flutter]
- flutter_styled_toast 2.1.3 [flutter flutter_localizations]
- flutter_svg 1.1.3 [flutter meta path_drawing vector_math xml]
- flutter_typeahead 3.2.7 [flutter flutter_keyboard_visibility]
- google_place 0.4.7 [http]
- html_editor_enhanced 2.5.0 [flutter flutter_inappwebview visibility_detector flutter_keyboard_visibility flex_color_picker file_picker numberpicker pointer_interceptor pedantic meta]
- http 0.13.5 [async http_parser meta path]
- intl 0.17.0 [clock path]
- jaguar_jwt 3.0.0 [auth_header crypto]
- lottie 1.4.1 [archive flutter path vector_math]
- mime 1.0.2
- open_filex 3.4.0 [flutter ffi]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 8.3.0 [flutter meta permission_handler_platform_interface]
- share_plus 4.0.10+1 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.4.6 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]

dependency overrides:
- cupertino_icons 1.0.5
- firebase_messaging_platform_interface 3.5.2 [firebase_core flutter meta plugin_platform_interface]

transitive dependencies:
- amplify_api_android 1.0.0-next.0 [flutter]
- amplify_api_ios 1.0.0-next.0 [amplify_core flutter]
- amplify_auth_cognito_android 1.0.0-next.0+1 [flutter]
- amplify_auth_cognito_dart 0.1.4 [amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value collection convert crypto fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid worker_bee]
- amplify_auth_cognito_ios 1.0.0-next.0+1 [amplify_core flutter]
- amplify_core 1.0.0-next.0 [async aws_common aws_signature_v4 collection http intl json_annotation logging meta uuid]
- amplify_datastore_plugin_interface 1.0.0-next.0 [amplify_core collection flutter meta]
- amplify_flutter_android 1.0.0-next.0 [flutter]
- amplify_flutter_ios 1.0.0-next.0 [amplify_core flutter]
- amplify_secure_storage 0.1.0 [amplify_secure_storage_dart flutter]
- amplify_secure_storage_dart 0.1.0 [aws_common built_collection built_value ffi js meta win32 worker_bee]
- archive 3.3.1 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- auth_header 3.0.1
- aws_common 0.2.2 [async collection http logging meta stream_transform uuid]
- aws_signature_v4 0.2.1 [async aws_common collection convert crypto http json_annotation meta path]
- boolean_selector 2.1.0 [source_span string_scanner]
- built_collection 5.1.1
- built_value 8.4.0 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.4 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.3 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- convert 3.0.2 [typed_data]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- dbus 0.7.7 [args ffi meta xml]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.3.0 [clock collection]
- ffi 2.0.1
- file 6.1.2 [meta path]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_web 2.4.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.1
- flex_color_picker 2.5.0 [flutter material_color_utilities]
- flutter_keyboard_visibility 5.3.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_linux 0.5.1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- infinite_listview 1.1.0 [flutter]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- numberpicker 2.1.1 [flutter infinite_listview]
- numerus 1.1.1
- oauth2 2.0.0 [collection crypto http http_parser]
- path 1.8.1
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.18 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.2 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointer_interceptor 0.9.3+2 [flutter]
- process 4.2.4 [file path platform]
- provider 6.0.3 [collection flutter nested]
- quiver 3.1.0 [matcher]
- retry 3.1.0
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.0.3 [flutter meta mime plugin_platform_interface]
- share_plus_web 3.0.1 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.1 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.3.2 [async collection http_parser path stack_trace stream_channel]
- sky_engine 0.0.99
- smithy 0.1.0 [aws_common built_collection built_value collection convert crypto fixnum http http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.1.1 [aws_common aws_signature_v4 built_collection built_value collection crclib http intl json_annotation meta path smithy xml]
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- tuple 2.0.0 [quiver]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- video_player_android 2.3.8 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.5 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.4 [flutter plugin_platform_interface]
- video_player_web 2.0.12 [flutter flutter_web_plugins video_player_platform_interface]
- visibility_detector 0.3.3 [flutter]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- win32 2.7.0 [ffi]
- worker_bee 0.1.0 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
```

### Device

N/A

### OS

N/A

### CLI Version

7.6.4

**Comment by Jordan-Nelson** [comment]
Hi @Sunsiha - Thanks for reporting the issue. Do you have [device tracking](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html) enabled in your Cognito user pool?

**Comment by Sunsiha** [comment]
@dnys1 Yes I have identity pool

**Comment by dnys1** [comment]
Thanks, @Sunsiha. Sorry you faced this issue - it is a regression in our latest release. I have a fix in PR and will release it as soon as it's approved!

**Comment by Sunsiha** [comment]
@dnys1 May I know then how it was working upto yesterday?

**Comment by dnys1** [comment]
It was, unfortunately, caused by another fix which was released yesterday. Apologies again. We will be implementing measures to make sure these kinds of regressions do not pass review in the future.

**Comment by Sunsiha** [comment]
> Thanks, @Sunsiha. Sorry you faced this issue - it is a regression in our latest release. I have a fix in PR and will release it as soon as it's approved!

When can I expect this release? Since for me it's a big blocker. Not able to continue my next steps because of this.

**Comment by dnys1** [comment]
Understood. You can expect a release within the next hour.

**Comment by Sunsiha** [comment]
> Understood. You can expect a release within the next hour.

Thanks alot.

**Comment by dnys1** [comment]
It's been released - please run `flutter pub upgrade` to get the latest changes :)
