### ISSUE TITLE
AuthException{message=Sign-in with web UI failed, cause=java.lang.Exception: showSignIn called without HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}

### ISSUE THREAD

**Issue by YawarOsman** [aws-amplify/amplify-flutter#2062]
**Describe the bug**
I am trying to LogIn with Google to my app in `Flutter` but it show this error:
```
E/amplify:flutter:auth_cognito(10680): AuthException
E/amplify:flutter:auth_cognito(10680): AuthException{message=Sign-in with web UI failed, cause=java.lang.Exception: showSignIn called without HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}
E/amplify:flutter:auth_cognito(10680): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$23.onError(AWSCognitoAuthPlugin.java:1275)
E/amplify:flutter:auth_cognito(10680): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(10680): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito(10680): 	at com.amazonaws.mobile.client.AWSMobileClient$25.run(AWSMobileClient.java:3274)
E/amplify:flutter:auth_cognito(10680): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito(10680): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:auth_cognito(10680): Caused by: java.lang.Exception: showSignIn called without HostedUI options in awsconfiguration.json
E/amplify:flutter:auth_cognito(10680): 	... 3 more
I/flutter (10680): Sign-in with web UI failed
```

**To Reproduce**
A code sample:
```
  try {
      final result = await Amplify.Auth.signInWithWebUI(provider: AuthProvider.google);
      print('Result: $result');
       } on AmplifyException catch (e) {
           print('${e.message}');
       }
```

**Expected behavior**
I expect to see google login page but this error is showed up.

I have used AWS Amplify LogIn with email and password before and it works without any error, i don't know what is wrong now.

**Environment Information (please complete the following information):**
 - Device: [Android Emultor]
 - Android Version: [android 11.0 x86]
 - Specific to simulators: [Yes]

**pubspec.yaml**
```
  amplify_flutter: ^0.6.5
  amplify_auth_cognito: ^0.6.5
  amplify_analytics_pinpoint: ^0.6.5
  amplify_api: ^0.6.5
  amplify_datastore: ^0.6.5
  amplify_storage_s3: ^0.6.5
```

**Comment by haverchuck** [comment]
@sktimalsina Can you post your `amplifyconfiguration.dart` file? Feel free to redact values - we just want to see the keys. Specifically, we should confirm that your config has the following block:

```
"OAuth": {
  "WebDomain": "mydomain.auth.us-west-2.amazoncognito.com",
  "AppClientId": "myclient",
   "SignInRedirectURI": "myapp://",
   "SignOutRedirectURI": "myapp://",
    "Scopes": [
      "phone",
       "email",
       "openid",
       "profile",
       "aws.cognito.signin.user.admin"
     ]
},
```

**Comment by dnys1** [comment]
Hi @YawarOsman - this appears to be a misconfiguration issue. Were you able to resolve it by following the docs Sunil posted? If not, can you provide the information @haverchuck requested?

**Comment by Jordan-Nelson** [comment]
Hi @YawarOsman - Please let us know if you were able to resolve this, or provide the config as requested above. Thanks.
