### ISSUE TITLE
[amplify_auth_cognito] fetchAuthSession extremely slow after upgrade to flutter 3.3 stable

### ISSUE THREAD

**Issue by BerndWessels** [aws-amplify/amplify-flutter#2088]
### Description

I just updated to flutter 3.3 and now `fetchAuthSession` is taking more than a minute - no code changes in my app. Before it took only about a second.

```dart
      final session = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      );
```

Seems like the `amplify_auth_cognito` plugin gets stuck connecting to Cognito - no idea how a flutter upgrade could cause that though.

A bit faster on a real device but extremely slow on the Android Studio Android Emulator.

Is this just me, or do others experience this too?

```
I/amplify:flutter:auth_cognito( 6006): Added Auth plugin
D/AWSMobileClient( 6006): Using the SignInProviderConfig from `awsconfiguration.json`.
D/AWSMobileClient( 6006): initialize: Cognito HostedUI client detected
D/AWSMobileClient( 6006): Inspecting user state details
I/amplify:flutter:auth_cognito_hub_evnet_stream_handler( 6006): AuthPlugin successfully initialized
D/AWSMobileClient( 6006): Inspecting user state details
I/TetheringManager( 6006): registerTetheringEventCallback:com.sass.sass_app
D/AWSMobileClient( 6006): Inspecting user state details
D/AWSMobileClient( 6006): waitForSignIn: userState:SIGNED_OUT

<--------- stuck here for more than a minute ---------------->

W/AWSMobileClient( 6006): getCredentials: Failed to getCredentials from Cognito Identity
W/AWSMobileClient( 6006): com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 3299ef18-7b10-438b-b36b-5e6a93e4e70a)
W/AWSMobileClient( 6006): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient( 6006): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient( 6006): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient( 6006): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient( 6006): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient( 6006): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient( 6006): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:4078)
W/AWSMobileClient( 6006): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
W/AWSMobileClient( 6006): 	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
W/AWSMobileClient( 6006): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
W/AWSMobileClient( 6006): 	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:400)
W/AWSMobileClient( 6006): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:445)
W/AWSMobileClient( 6006): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:442)
W/AWSMobileClient( 6006): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
W/AWSMobileClient( 6006): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:auth_cognito( 6006): SignedOutException
E/amplify:flutter:auth_cognito( 6006): SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
E/amplify:flutter:auth_cognito( 6006): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareCognitoSessionFailure(AuthCognito.kt:631)
E/amplify:flutter:auth_cognito( 6006): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.onFetchAuthSession$lambda-18(AuthCognito.kt:387)
E/amplify:flutter:auth_cognito( 6006): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.$r8$lambda$uu-F3NQTLN2zVTYaQlc45ppd10Q(Unknown Source:0)
E/amplify:flutter:auth_cognito( 6006): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$$ExternalSyntheticLambda30.accept(Unknown Source:8)
E/amplify:flutter:auth_cognito( 6006): 	at com.amplifyframework.auth.cognito.MobileClientSessionAdapter$1.onError(MobileClientSessionAdapter.java:74)
E/amplify:flutter:auth_cognito( 6006): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:47)
E/amplify:flutter:auth_cognito( 6006): 	at java.lang.Thread.run(Thread.java:923)
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1889], locale en-NZ)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

my pubspec.yaml
```
name: sass_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  amplify_auth_cognito: ^0.6.6
  amplify_flutter: ^0.6.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_easyloading: ^3.0.3
  flutter_signin_button: ^2.0.0
  get: ^4.6.5
  graphql: ^5.1.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  logger: ^1.1.0
  mime: ^1.0.2
  path_provider: ^2.0.11

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

flutter `3.3 stable` and amplify_auth_cognito `^0.6.6`

```dart
      final session = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      );
```

takes more than a minute :(

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Android Device/Emulator API Level

API 30

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1889], locale en-NZ)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.18.0
Flutter SDK 3.3.0
sass_app 1.0.0+1

dependencies:
- amplify_auth_cognito 0.6.6 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_in
terface]
- amplify_flutter 0.6.6 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter met
a plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_easyloading 3.0.5 [flutter flutter_spinkit]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- get 4.6.5 [flutter]
- graphql 5.1.1 [meta path gql gql_exec gql_link gql_http_link gql_transform_link gql_error_link gql_dedupe_link hive normalize http collection web_so
cket_channel stream_channel rxdart uuid]
- http 0.13.5 [async http_parser meta path]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- logger 1.1.0
- mime 1.0.2
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_
provider_windows]

transitive dependencies:
- amplify_auth_cognito_android 0.6.6 [flutter]
- amplify_auth_cognito_ios 0.6.6 [amplify_core flutter]
- amplify_core 0.6.6 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.6 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.6 [flutter]
- amplify_flutter_ios 0.6.6 [amplify_core flutter]
- async 2.9.0 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- characters 1.2.1
- clock 1.1.1
- collection 1.16.0
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- ffi 2.0.1
- file 6.1.4 [meta path]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- font_awesome_flutter 9.2.0 [flutter]
- gql 0.13.1 [collection meta source_span]
- gql_dedupe_link 2.0.2 [async gql_exec gql_link meta]
- gql_error_link 0.2.2 [async gql_exec gql_link meta]
- gql_exec 0.4.0 [collection gql meta]
- gql_http_link 0.4.2 [gql gql_exec gql_link http http_parser meta]
- gql_link 0.4.2 [gql gql_exec meta]
- gql_transform_link 0.2.2 [gql_exec gql_link]
- hive 2.2.3 [meta crypto]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- material_color_utilities 0.1.5
- meta 1.8.0
- normalize 0.6.0+1 [gql collection]
- path 1.8.2
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.2 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- rxdart 0.27.5
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- sqflite 2.0.3+1 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.1 [source_span]
- synchronized 3.0.0+2
- term_glyph 1.2.1
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- web_socket_channel 2.2.0 [async crypto stream_channel]
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
```

### Device

N/A

### OS

N/A

### Deployment Method

Amplify CLI

### Amplify Config

{}

**Comment by haverchuck** [comment]
@BerndWessels Just to clarify - all other APIs are performing reasonably, including signIn and signOut?

**Comment by BerndWessels** [comment]
@haverchuck yes, that's right.
I can try to extract the necessary bits and create an example repo, that might help to reproduce it, but it will take me a day or two.
Cheers

**Comment by dnys1** [comment]
Hi @BerndWessels, `fetchAuthSession` is known to be slow in certain conditions (e.g. spotty networks) due to retry behavior in the underlying SDK. Our recommendation is to set a timeout on the call and handle that the same way you would handle a failure for other reasons: https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter/#setting-a-timeout-for-fetchauthsession

**Comment by dnys1** [comment]
If your application and timeframe allow for it, I would recommend checking out the developer preview version of our libraries which feature a full rewrite in Dart of the Authentication category. While it is not production ready, we are much more easily able to prioritize fixes or features related to issues like this.

https://pub.dev/packages/amplify_auth_cognito/versions/1.0.0-next.0+4
