### ISSUE TITLE
Amplify DataStore stops working after an internet reconnection

### ISSUE THREAD

**Issue by ZubairAkber** [aws-amplify/amplify-flutter#2373]
### Description

Simply start the Amplify and set Observer on any of the table, when it gets ready and you receive the ready event simply disconnect your internet then you will see the exception that i have attached below, the problem starts when internet gets back and you didn't keep getting events and updates from Amplify 

Websocket connection failed.
                 java.net.SocketException: Software caused connection abort
                 	at java.net.SocketInputStream.socketRead0(Native Method)
                 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
                 	at java.net.SocketInputStream.read(SocketInputStream.java:176)
                 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
                 	at okio.InputStreamSource.read(JvmOkio.kt:90)
                 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
                 	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
                 	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
                 	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
                 	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
                 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
                 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
                 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
                 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:923)
17:03:19.440  W  API sync failed - transitioning to LOCAL_ONLY.
                 DataStoreException{message=Error during subscription., cause=ApiException{message=Subscription failed., cause=java.net.SocketException: Software caused connection abort, recoverySuggestion=Check your Internet connection. Is your device online?}, recoverySuggestion=Evaluate details.}
                 	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:328)
                 	at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$797ziDK0io-qXODzROLOA77stS8.accept(Unknown Source:4)
                 	at com.amplifyframework.api.aws.SubscriptionOperation.lambda$null$1$SubscriptionOperation(SubscriptionOperation.java:87)
                 	at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$l9lC7Ew6niNmyszMXQSUKS6YhwE.accept(Unknown Source:4)
                 	at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchError(SubscriptionEndpoint.java:432)
                 	at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:233)
                 	at com.amplifyframework.api.aws.SubscriptionEndpoint.access$100(SubscriptionEndpoint.java:61)
                 	at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onFailure(SubscriptionEndpoint.java:528)
                 	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
                 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:197)
                 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:923)
                 Caused by: ApiException{message=Subscription failed., cause=java.net.SocketException: Software caused connection abort, recoverySuggestion=Check your Internet connection. Is your device online?}
                 	at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:233) 
                 	at com.amplifyframework.api.aws.SubscriptionEndpoint.access$100(SubscriptionEndpoint.java:61) 
                 	at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onFailure(SubscriptionEndpoint.java:528) 
                 	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592) 
                 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:197) 
                 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                 	at java.lang.Thread.run(Thread.java:923) 
                 Caused by: java.net.SocketException: Software caused connection abort
                 	at java.net.SocketInputStream.socketRead0(Native Method)
                 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
                 	at java.net.SocketInputStream.read(SocketInputStream.java:176)
                 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
                 	at okio.InputStreamSource.read(JvmOkio.kt:90)
                 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
                 	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
                 	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
                 	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
                 	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
                 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
                 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
                 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
                 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                 	at java.lang.Thread.run(Thread.java:923) 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Simply start the Amplify and set Observer on any of the table
2. When it gets ready and you receive the ready event simply disconnect your internet
3. Then you will see the exception that i have attached in description
4. The problem starts when internet gets back and you didn't keep getting events and updated from Amplify

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Not Flutter
```

### Dependencies

```bash
// Amplify dependencies
    implementation 'com.amplifyframework:core:1.30.0'
    implementation 'com.amplifyframework:aws-api:1.30.0'
    implementation 'com.amplifyframework:aws-datastore:1.30.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.30.0'
    implementation 'com.amplifyframework:aws-storage-s3:1.30.0'
```

### Device

Samsung S21 ultra

### OS

Android 12

### Deployment Method

Amplify CLI

### Amplify Config

{}

**Comment by HuiSF** [comment]
Hello @ZubairAkber Thanks for opening this issue.

DataStore sync engine doesn't actively detect network reconnection and to re-establish model subscriptions, rather, it attempts to re-sync on any DataStore API calls such as `save`, `delete`, `start`. Have your App invoked any of the APIs after reconnection?

I personally use `connectivity_plus` to watch network state, , and invoke `Amplify.DataStore.start()` on reconnection.

**Comment by HuiSF** [comment]
Also @ZubairAkber could you confirm if you are using amplify-android or amplify-android?

**Comment by ZubairAkber** [comment]
@HuiSF Thanks for your response, i am using [amplify-android ](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android/) okay i will start it once internet is back but i think better if library handle this scenario and auto reconnect on internet availability

**Comment by HuiSF** [comment]
No worries @ZubairAkber  I will forward this issue to amplify-android repo for now. And we are actively looking into the improvements around DataStore reconnection. Please stay tuned.
