### ISSUE TITLE
CognitoUserSession is not valid because idToken is null in flutter

### ISSUE THREAD

**Issue by sagar-esmagico** [aws-amplify/amplify-flutter#2391]
Hello, developer

I have implemented authentication flow in my application using aws. And used following versions for this.

```
# Authentication :
amplify_flutter: ^0.6.10
amplify_auth_cognito: ^0.6.10
```

It's working fine in all cases. But in some case it showing me the following issues and exception. Find console print i am getting while executing code. Please, give me solution ASAP as my app is live and users are coming but some are not able to create account. So... please sort out for me.

```
E/amplify:flutter:auth_cognito(22273): LambdaException
E/amplify:flutter:auth_cognito(22273): AuthException{message=Sign up failed, cause=com.amazonaws.services.cognitoidentityprovider.model.InvalidLambdaResponseException: Unrecognizable lambda output (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidLambdaResponseException; Request ID: bd86f8fc-470a-4fec-b3db-c5caafd39ca3), recoverySuggestion=See attached exception for more details.}
E/amplify:flutter:auth_cognito(22273): 	at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:131)
E/amplify:flutter:auth_cognito(22273): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onError(AWSCognitoAuthPlugin.java:316)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.AWSMobileClient$14$1.onFailure(AWSMobileClient.java:2225)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:510)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.AWSMobileClient$14.run(AWSMobileClient.java:2194)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito(22273): 	at java.lang.Thread.run(Thread.java:1012)
E/amplify:flutter:auth_cognito(22273): Caused by: com.amazonaws.services.cognitoidentityprovider.model.InvalidLambdaResponseException: Unrecognizable lambda output (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidLambdaResponseException; Request ID: bd86f8fc-470a-4fec-b3db-c5caafd39ca3)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6837)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.signUp(AmazonCognitoIdentityProviderClient.java:5782)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUpInternal(CognitoUserPool.java:561)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:505)
E/amplify:flutter:auth_cognito(22273): 	... 3 more
E/amplify:flutter:auth_cognito(22273): AuthException
E/amplify:flutter:auth_cognito(22273): AuthException{message=Sign up failed, cause=com.amazonaws.services.cognitoidentityprovider.model.InvalidLambdaResponseException: Unrecognizable lambda output (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidLambdaResponseException; Request ID: bd86f8fc-470a-4fec-b3db-c5caafd39ca3), recoverySuggestion=See attached exception for more details.}
E/amplify:flutter:auth_cognito(22273): 	at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:131)
E/amplify:flutter:auth_cognito(22273): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onError(AWSCognitoAuthPlugin.java:316)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.AWSMobileClient$14$1.onFailure(AWSMobileClient.java:2225)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:510)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.AWSMobileClient$14.run(AWSMobileClient.java:2194)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito(22273): 	at java.lang.Thread.run(Thread.java:1012)
E/amplify:flutter:auth_cognito(22273): Caused by: com.amazonaws.services.cognitoidentityprovider.model.InvalidLambdaResponseException: Unrecognizable lambda output (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidLambdaResponseException; Request ID: bd86f8fc-470a-4fec-b3db-c5caafd39ca3)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6837)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.signUp(AmazonCognitoIdentityProviderClient.java:5782)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUpInternal(CognitoUserPool.java:561)
E/amplify:flutter:auth_cognito(22273): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:505)
E/amplify:flutter:auth_cognito(22273): 	... 3 more
I/flutter (22273): LambdaException in registerUser --> Sign up failed
I/flutter (22273): LambdaException in registerUser --> See attached exception for more details.
I/flutter (22273): LambdaException in registerUser --> com.amazonaws.services.cognitoidentityprovider.model.InvalidLambdaResponseException: Unrecognizable lambda output (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidLambdaResponseException; Request ID: bd86f8fc-470a-4fec-b3db-c5caafd39ca3)
```

**Comment by dnys1** [comment]
Hi @sagar-esmagico, sorry you are facing this issue. I will need some more information in order to properly assist you.

The error thrown is coming from one of your Lambda triggers registered in your project. Since it is happening at the registration step, it means either your pre-sign up, post confirmation, or migrate user Lambda triggers. One of these seems to be throwing an exception that is not being dealt with in the trigger.

Can you share the CloudWatch logs for your Lambda trigger to see what error is being thrown there? That will give us the information we need to understand what is happening.
