### ISSUE TITLE
[api] Multiple subscriptions cannot be established synchronously

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#2493]
In vNext API, multiple subscriptions cannot be established synchronously, e.g.

```dart
void setupSubscriptions() {
  final request1 = GraphQLRequest(...);
  final subscription1 = Amplify.API.subscribe(request1).listen(...);
  final request2 = GraphQLRequest(...);
  final subscription2 = Amplify.API.subscribe(request2).listen(...);
}
```

Results in the following error:

```
E/flutter (14866): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:amplify_api/src/graphql/web_socket/blocs/web_socket_bloc.dart': Failed assertion: line 211 pos 7: '_currentState is ConnectingState': We should never receive an connection ack message while not connecting.
package:amplify_api/…/blocs/web_socket_bloc.dart:211
E/flutter (14866): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (14866): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (14866): #2      WebSocketBloc._connectionAck
package:amplify_api/…/blocs/web_socket_bloc.dart:211
E/flutter (14866): <asynchronous suspension>
E/flutter (14866):
```

**Comment by dnys1** [comment]
This has been fixed in v1.0.0-next.5
