### ISSUE TITLE
Can not access the GraphQL data with built deployments

### ISSUE THREAD

**Issue by fuzkabir** [aws-amplify/amplify-flutter#2636]
### Description

My project has no Data Store functionality as its target is web & android, and no offline syncing is required. But initially, when I followed along with some tutorials, I enabled the Enable conflict detection and later disabled that. During development, My App can pull DynamoDB Tables via GraphQL without any problem. Just one problem I could not do anything with : 
`Error: CompileError: WebAssembly.instantiateStreaming(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
`
Yesterday I built the web (hosting with S3) and android, but none can pull the data from GraphQL and face null safety problems. The Web browser is asking for sqlite3.wasm file. Later, I created the file on my own and uploaded it. But Still, the issue exists. Android App opens for once but remains unresponsive (maybe for null problems). But I never had such experience with both platforms while developing local machines.

Packages I'm using:
  amplify_flutter: ^1.0.0-next.1
  amplify_auth_cognito: ^1.0.0-next.1
  amplify_authenticator: ^1.0.0-next.1
  amplify_storage_s3: ^1.0.0-next.2
  amplify_api: ^1.0.0-next.2+1

Error shown during:

flutter build apk --split-per-abi

```
e: C:/Users/fuzka/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.
7.10/d70d7d2c56371f7aa18f32e984e3e2e998fe9081/kotlin-stdlib-jdk8-1.7.10.jar!/META-INF/kotlin-st
dlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary
 version of its metadata is 1.7.1, expected version is 1.5.1.
e: C:/Users/fuzka/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.
7.10/1ef73fee66f45d52c67e2aca12fd945dbe0659bf/kotlin-stdlib-jdk7-1.7.10.jar!/META-INF/kotlin-st
dlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary
 version of its metadata is 1.7.1, expected version is 1.5.1.
e: C:/Users/fuzka/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.5.0/85767
8d6b4ca7b28571ef7935c668bdb57e15027/annotation-1.5.0.jar!/META-INF/annotation.kotlin_module: Mo
dule was compiled with an incompatible version of Kotlin. The binary version of its metadata is n-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
```
Error Shown during: Flutter Build windows

```
C:\dhsapps\dhsapps\build\windows_deps\sqlite3-src\sqlite3.c(114636,7): warning C4101: 'rc': unreferenced local variable [C:\dhsapps\dhsapps\build\windows\plugins\amplify_db_common\sqlite3.v
cxproj]
```

Chrome Console also shows this error for deployed web: 
```
Exception while loading service worker: Error: Service worker not supported (or configured).
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:107:11)
    at FlutterLoader.loadEntrypoint (flutter.js:344:33)
    at (index):46:23
```

Why I feel it as bug?
-I worked with Expo-cli with react native before. While I built any deployment it work seemlessly with S3 and cloudFront. But here is no reason the output and deployment do not bring the same result or there is no way to determine what is going wrong so that I can focus on that issue and make the fix.
-As per https://docs.amplify.aws/lib/project-setup/platform-setup/q/platform/flutter/  it requires a custom build of SQLite when targeting web. But there is no guideline or tutorial how to do that. But I feel it is not a valid reason why GraphQL Doesn't work with every deployment.
Thanks to Billy Gerhard.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Build Basic Auth with Amplify
2. A basic Data model for users only
3. A GraphQL get Query
4. Running in local machine 
5. Build as Apk, web and desktop
6. Test deployments.

### Platforms

- [ ] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [X] Windows
- [ ] Linux

### Flutter Version

3.7.0-1.5.pre

### Amplify Flutter Version

1.0.0-next.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type AppUser @model @auth(rules: [{allow: private}]) {
  id: ID!
  Name: String
  Address: String
  Gender: String
  Reference: String
  Mobile: String
  Email: String
  CognitoId: String
  TypeReq: String
  TypeGiven: String
  SwPatCall: Boolean
  SwMkPres: Boolean
  SwSupUnit: Boolean
  SwMyPres: Boolean
  SwCalDoc: Boolean
  SwPhAdmin: Boolean
  SwPhUser: Boolean
  SwCuSup: Boolean
  SwSche: Boolean
  SwAppt: Boolean
  SwMgt: Boolean
  SwLoc: Boolean
  SwAcc: Boolean
  SwCert: Boolean
  RegNo: String
  Status: String
  RequestFlag: String
  BirthDay: AWSDate
  Age: Int
  Weight: Int
  PatientRating: Float
  DoctorRating: Float
  PharmecyRating: Float
  WorkerRating: Float
  Location: String
  Designation: String
  Verified: Boolean
  Reg: String
  Department: String
  OutdoorFee: Int
  ChamberTime: String
  VirtualTime: String
  MarriageDay: AWSDate
  StartYear: Int
  Photo: String
  Phone2: String
  FamilyContact: String
  Height: String
  PhysicalStatus: String
  Profit: Float
  VirtualFee: String
  Remarks: String
}
```

**Comment by fuzkabir** [comment]
I just deployed a single page after login to S3,  Where it just pulls and shows one GraphQL field. But the message it's showing:

```
Query failed: ApiException {
  "message": "No schema found for the ModelType provided: minified:q7",
  "recoverySuggestion": "Pass in a valid modelProvider instance while instantiating APIPlugin or provide a valid ModelType"
}
```
again this is not happening with the local machine. Everything is Okay there.

**Comment by salihgueler** [comment]
Thanks for the issue @fuzkabir it seems like this is the same as https://github.com/aws-amplify/amplify-flutter/issues/2524, @dnys1 is there an alternative way for us to help Fuz out?

**Comment by fuzkabir** [comment]
@fjnoyp Thanks for your response. 

I just ran `amplify codegen models` Model and deployed for web on S3. This is the result from Chrome Developer tool Console:

```
Uncaught GET http://doctorial.link/sqlite3.wasm failed: An unknown exception occurred loading sqlite3.wasm.

sqlite3.wasm needs to be included in your /web dir. See Amplify Platform Setup docs for more info: https://docs.amplify.aws/lib/project-setup/platform-setup/q/platform/flutter/

GET http://doctorial.link/sqlite3.wasm failed: Request to load sqlite3.wasm returned status code: 403.

sqlite3.wasm needs to be included in your /web dir. See Amplify Platform Setup docs for more info: https://docs.amplify.aws/lib/project-setup/platform-setup/q/platform/flutter/
    at Object.i (http://doctorial.link/main.dart.js:4668:3)
    at http://doctorial.link/main.dart.js:76002:9
    at bSl.a (http://doctorial.link/main.dart.js:6063:62)
    at bSl.$2 (http://doctorial.link/main.dart.js:53561:14)
    at bQU.$1 (http://doctorial.link/main.dart.js:53555:21)
    at aXa.q3 (http://doctorial.link/main.dart.js:54829:33)
    at bHC.$0 (http://doctorial.link/main.dart.js:54012:11)
    at Object.a83 (http://doctorial.link/main.dart.js:6219:40)
    at ae.tj (http://doctorial.link/main.dart.js:53944:3)
    at alB.bt (http://doctorial.link/main.dart.js:53549:8)
```

The APK is working fine now. 

I guess it's just missing the sqlite3.wasm. Is there any guideline on how I can embed the file in the source code so that it automatically be added to the deployment?

Thanks again.

**Comment by dnys1** [comment]
Hi @fuzkabir can you try downloading the sqlite3.wasm file from [here](https://github.com/simolus3/sqlite3.dart/releases/tag/sqlite3-1.9.1) and including that in your `web/` folder?

Regarding the other issues,
> Error Shown during: Flutter Build windows
>
> `C:\dhsapps\dhsapps\build\windows_deps\sqlite3-src\sqlite3.c(114636,7): warning C4101: 'rc': unreferenced local variable [C:\dhsapps\dhsapps\build\windows\plugins\amplify_db_common\sqlite3.v
cxproj]`

I think this is just a warning and should be harmless. Let me know if you have issues running the app on Windows.

> Chrome Console also shows this error for deployed web:
>
> Exception while loading service worker: Error: Service worker not supported (or configured).
>    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:107:11)
>    at FlutterLoader.loadEntrypoint (flutter.js:344:33)
>    at (index):46:23

You may try regenerating your `web/index.html` by deleting it and running `flutter create .`

**Comment by fuzkabir** [comment]
@dnys1 
> You may try regenerating your `web/index.html` by deleting it and running `flutter create .`

Now the page shows nothing (on S3), and error is displayed in Chrome Developer Console:

```
doctorial.link/:40          GET http://doctorial.link/flutter.js net::ERR_ABORTED 403 (Forbidden)
(index):46 Uncaught ReferenceError: _flutter is not defined
    at (index):46:7
(anonymous) @ (index):46
load (async)
(anonymous) @ (index):44
```

Windows is working perfectly now. Thanks.

**Comment by dnys1** [comment]
You are uploading your `build/web` folder to S3, correct? Can you try running `flutter clean` followed by `flutter build web` again?

Is your project being hosted at the root path of your website or at a subpath? For example:
`http://example.com/` <- root path
`http://example.com/app/` <- subpath

**Comment by fuzkabir** [comment]
@dnys1 
root path.
I'll try and let you know.

**Comment by fuzkabir** [comment]
@dnys1 
Steps Taken:
1. `flutter clean `
2. Deleted web/index.html
3. `flutter create .`
4. `flutter build web`
5. Uploaded to the S3 root folder

Result: Showing everything but no pull from GraphQL.
Chrome Developer Console shows:
```
flutter.js:346 Exception while loading service worker: Error: Service worker not supported (or configured).
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:107:11)
    at FlutterLoader.loadEntrypoint (flutter.js:344:33)
    at (index):46:23
```

Thanks.

**Comment by dnys1** [comment]
Are you using CloudFront? I wonder if file caching is to blame for this behavior.

Have you tried in other browsers to see if that works?

**Comment by dnys1** [comment]
> Result: Showing everything but no pull from GraphQL.

Are there any other errors in the console related to GraphQL/Amplify?

**Comment by fuzkabir** [comment]
> Are you using CloudFront? I wonder if file caching is to blame for this behaviour.

No, I'm used to doing that when everything is done. But to check the HTTPS protocol response I created a distribution with Managed-CachingDisabled. The results are almost the same.

>Have you tried in other browsers to see if that works?
**Results with Edge:**
S3:
```
Exception while loading service worker: Error: Service worker not supported (or configured).
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:107:11)
    at FlutterLoader.loadEntrypoint (flutter.js:344:33)
    at (index):46:23
(anonymous) @ flutter.js:346
Promise.catch (async)
loadEntrypoint @ flutter.js:344
(anonymous) @ (index):46
load (async)
(anonymous) @ (index):44
main.dart.js:36100 Query failed: ApiException {
  "message": "No schema found for the ModelType provided: minified:q7",
  "recoverySuggestion": "Pass in a valid modelProvider instance while instantiating APIPlugin or provide a valid ModelType"
}

```
Cloudfront:

```
Query failed: ApiException {
  "message": "No schema found for the ModelType provided: minified:q7",
  "recoverySuggestion": "Pass in a valid modelProvider instance while instantiating APIPlugin or provide a valid ModelType"
}

```
**Result with Firefox :**
S3 & CloudFront:

```
Exception while loading service worker: Error: Service worker not supported (or configured).
    loadServiceWorker http://doctorial.link/flutter.js:107
    loadEntrypoint http://doctorial.link/flutter.js:344
    <anonymous> http://doctorial.link/#/:46
    EventListener.handleEvent* http://doctorial.link/#/:44
[fl](http://doctorial.link/flutter.js)

Uncaught Error: Instance of 'minified:bi' [main.dart.js:4627:3](http://doctorial.link/main.dart.js)
    i http://doctorial.link/main.dart.js:4627
    c8w http://doctorial.link/main.dart.js:7479
    ib http://doctorial.link/main.dart.js:7745
    $0 http://doctorial.link/main.dart.js:51462
    cjr http://doctorial.link/main.dart.js:6210
    cjZ http://doctorial.link/main.dart.js:6212
    $1 http://doctorial.link/main.dart.js:50186
    cJ2 http://doctorial.link/main.dart.js:4708
    s http://doctorial.link/main.dart.js:4716
    (Async: MutationCallback)
    cfW http://doctorial.link/main.dart.js:5991
    <anonymous> http://doctorial.link/main.dart.js:143373
    c http://doctorial.link/main.dart.js:32
    bXI http://doctorial.link/main.dart.js:6217
    bIx http://doctorial.link/main.dart.js:6334
    pv http://doctorial.link/main.dart.js:51518
    WF http://doctorial.link/main.dart.js:50633
    kw http://doctorial.link/main.dart.js:50631
    bH http://doctorial.link/main.dart.js:50228
    z http://doctorial.link/main.dart.js:6012
    bKz http://doctorial.link/main.dart.js:9165
    s http://doctorial.link/main.dart.js:6022
    $2 http://doctorial.link/main.dart.js:50243
    A http://doctorial.link/main.dart.js:6008
    bKz http://doctorial.link/main.dart.js:9166
    bJK http://doctorial.link/main.dart.js:36085
    s http://doctorial.link/main.dart.js:6022
    $2 http://doctorial.link/main.dart.js:50243
    A http://doctorial.link/main.dart.js:6008
    bJK http://doctorial.link/main.dart.js:36087
    <anonymous> http://doctorial.link/main.dart.js:144046
    <anonymous> http://doctorial.link/main.dart.js:144040
    dartProgram http://doctorial.link/main.dart.js:144043
    <anonymous> http://doctorial.link/main.dart.js:144046

Query failed: ApiException {
  "message": "No schema found for the ModelType provided: minified:q7",
  "recoverySuggestion": "Pass in a valid modelProvider instance while instantiating APIPlugin or provide a valid ModelType"
}

```

**Comment by dnys1** [comment]
Hmm can you share how you’re configuring Amplify and which code is failing?

**Comment by fuzkabir** [comment]
@dnys1 
Sure.

```
Future<void> _configureAmplify() async {

  final auth = AmplifyAuthCognito();
  await Amplify.addPlugins([
    auth,
    AmplifyAPI(modelProvider: ModelProvider.instance),
    AmplifyStorageS3(),
  ]);
  try
  {
    await Amplify.configure(amplifyconfig);
    safePrint('Amplify has been Successfully configured');
  } on Exception catch (e) {
    safePrint('Error configuring Amplify: $e');
  }
}
```



amplifyconfiguration.dart

```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "dhsapps": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://wyvo2tpa6zf53hwce4ksbkupgq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
                    "region": "ap-southeast-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://wyvo2tpa6zf53hwce4ksbkupgq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
                        "Region": "ap-southeast-1",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "dhsapps_AMAZON_COGNITO_USER_POOLS"
                    },
                    "dhsapps_AWS_IAM": {
                        "ApiUrl": "https://wyvo2tpa6zf53hwce4ksbkupgq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
                        "Region": "ap-southeast-1",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "dhsapps_AWS_IAM"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-southeast-1:245b614c-d072-4e04-a0d8-a5905febeb22",
                            "Region": "ap-southeast-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-southeast-1_zZE2flX89",
                        "AppClientId": "1dvcpr6i7pg7hnno5usm0mkch3",
                        "Region": "ap-southeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "signupAttributes": [
                            "ADDRESS",
                            "EMAIL",
                            "MIDDLE_NAME",
                            "GENDER",
                            "NAME",
                            "NICKNAME",
                            "PHONE_NUMBER"
                        ],
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL",
                            "PHONE_NUMBER"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "dhsapps2000e29311bc4dcc818f701044eae0c9234846-dev",
                        "Region": "ap-southeast-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "dhsapps2000e29311bc4dcc818f701044eae0c9234846-dev",
                "region": "ap-southeast-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}''';
```

Code that are failing:

```
      final request = ModelQueries.get(
          AppUser.classType, "eea4da20-fa21-430e-9225-54ed6ea0aada");
      final response = await Amplify.API.query(request: request).response;
      final appUser = response.data;
```




There is no problem with pulling data during Development.

**Comment by dnys1** [comment]
Can you verify you've run `amplify upgrade` followed by `amplify codegen models`? This should resolve your GraphQL issue as @fjnoyp mentioned above.

I'm not sure what could be causing the Flutter service worker exception. Let's see if we can resolve the GraphQL problem first though.

**Comment by fuzkabir** [comment]
@dnys1
It is working this time. 
Thanks a lot to you all. Really appreciate your kind and quick support. 
Never mind, but I need to remove amplifyconfiguration.dart part for my security concern.
