### ISSUE TITLE
`java.io.FileNotFoundException: can't read keyset` while initializing Amplify

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-flutter#2640]
### Issue

A FileNotFoundException and stack trace is logged while initializing Amplify. The full log looks like:
```
W/AndroidKeysetManager( 1231): keyset not found, will generate a new one
W/AndroidKeysetManager( 1231): java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist
W/AndroidKeysetManager( 1231): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
W/AndroidKeysetManager( 1231): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
W/AndroidKeysetManager( 1231): 	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
W/AndroidKeysetManager( 1231): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
W/AndroidKeysetManager( 1231): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
W/AndroidKeysetManager( 1231): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
W/AndroidKeysetManager( 1231): 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:123)
W/AndroidKeysetManager( 1231): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke(EncryptedKeyValueRepository.kt:31)
W/AndroidKeysetManager( 1231): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke(EncryptedKeyValueRepository.kt:21)
W/AndroidKeysetManager( 1231): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
W/AndroidKeysetManager( 1231): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.EncryptedKeyValueRepository.getSharedPreferences(EncryptedKeyValueRepository.kt:21)
W/AndroidKeysetManager( 1231): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.EncryptedKeyValueRepository.get(EncryptedKeyValueRepository.kt:73)
W/AndroidKeysetManager( 1231): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.AmplifySecureStoragePlugin.read(AmplifySecureStoragePlugin.kt:33)
W/AndroidKeysetManager( 1231): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.Messages$AmplifySecureStorageApi.lambda$setup$0(Messages.java:77)
W/AndroidKeysetManager( 1231): 	at com.amazonaws.amplify.amplify_secure_storage.amplify_secure_storage.Messages$AmplifySecureStorageApi$$ExternalSyntheticLambda0.onMessage(Unknown Source:2)
W/AndroidKeysetManager( 1231): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
W/AndroidKeysetManager( 1231): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/AndroidKeysetManager( 1231): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/AndroidKeysetManager( 1231): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/AndroidKeysetManager( 1231): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
W/AndroidKeysetManager( 1231): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0$io-flutter-embedding-engine-dart-DartMessenger$SerialTaskQueue(DartMessenger.java:163)
```

### Cause

The log message is coming from Android Security (androidx.security:security-crypto:1.0.0) which is used for storing sensitive data in Amplify when targeting Android.

### Solution (short term)

This log message can be safely ignored. The log message is confusing. However, it is not harmful. It is currently expected when a new EncryptedSharedPreferences file is created since the keyset has not yet been created.

https://github.com/aws-amplify/amplify-flutter/pull/2637 adds a log message before/after creating a new EncryptedSharedPreferences instance to note that this is expected.

### Solution (long term)

The log message has been removed from google/tink. ~~Once this update is included in a stable version of Android Security, updating will remove the log.~~ Adding a dependency on the latest version of google/tink resolves this issue. See https://github.com/google/tink/issues/534 for more info.

**Comment by Jordan-Nelson** [comment]
A fix for this has been merged and released.

**Comment by adplant** [comment]
@Jordan-Nelson I'm using the update version of flutter (Flutter 3.13.9 / Dart 3.1.5) and I still have this issue.

**Comment by selvaviswanath** [comment]
Im going through the same error, is there way to handle this before hand?
