### ISSUE TITLE
Not Authorized to access syncTasks on type ModelTaskConnection

### ISSUE THREAD

**Issue by primico** [aws-amplify/amplify-flutter#2724]
### Description

Not sure if this is a bug or I haven't configured my auth correctly? When I log into my app with an authenticated user I get this error:

```
DataStoreException{message=Initial cloud sync failed for Task., cause=DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Not Authorized to access syncTasks on type ModelTaskConnection', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncTasks'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check your internet connection.}
2023-03-03 11:32:54.434 10615-10729 amplify:aws-datastore   com.clearup.clearup_mobile           E  Failure encountered while attempting to start API sync.
                                                                                                    DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.lang.RuntimeException: DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Not Authorized to access syncTasks on type ModelTaskConnection', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncTasks'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
                                                                                                    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
                                                                                                    match your scenario, and file an issue with the details of the bug if there isn't.}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Log into app with authenticated user.
2. Datastore tries to sync.
3. Error in logcat

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.5

### Amplify Flutter Version

1.0.0-next.5

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hi @primico - can you share your GraphQL schema?

**Comment by primico** [comment]
sure, here it is:

```
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Task
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["Managers"], operations: [create, update, read, delete] }
      { allow: groups, groups: ["Employees"], operations: [read] }
    ]
  ) {
  id: ID!
  title: String!
  description: String
  status: String
}

type PrivateNote @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  content: String!
}

type UserType @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
}

type Review @model @auth(rules: [{allow: private}]) {
  id: ID!
  stars: Int!
  review: String
}

type ProductType @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
}

type Action @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
  description: String
}

type RoutineItem @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
  action: Action @hasOne
  productType: ProductType @hasOne
  routineID: ID! @index(name: "byRoutine")
}

type Routine @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
  rating: Float
  userID: ID! @index(name: "byUser")
  routineItems: [RoutineItem] @hasMany(indexName: "byRoutine", fields: ["id"])
  user: User @belongsTo(fields: ["userID"])
}

type Product @model @auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
  shortDescription: String!
  longDescription: String
  link: AWSURL
  image: AWSURL
  rating: Float
  minPrice: Float
  maxPrice: Float
  productType: ProductType @hasOne
}

type User @model @auth(rules: [{allow: private}]) {
  id: ID!
  email: AWSEmail!
  firstName: String!
  lastName: String!
  image: AWSURL
  routines: [Routine] @hasMany(indexName: "byUser", fields: ["id"])
  ipAddress: AWSIPAddress
  userType: UserType @hasOne
}
```

**Comment by Jordan-Nelson** [comment]
Thanks. Can you also share your amplify configuration (with sensitive info removed)?

**Comment by primico** [comment]
```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "AdminQueries": {
                    "endpointType": "REST",
                    "endpoint": "https://xxxxxxx.execute-api.us-east-1.amazonaws.com/dev",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                },
                "clxxxxxxxx": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://xxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "xxxx_AMAZON_COGNITO_USER_POOLS"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:85b1xxxxxxxxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_xxxxxxxx",
                        "AppClientId": "xxxxxxxxxxxxxxxxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL",
                            "FAMILY_NAME",
                            "GIVEN_NAME"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';
```

**Comment by primico** [comment]
Still haven't been able to sync successfully. I can write locally but get sync errors. Any ideas?

```
Failure encountered while attempting to start API sync.
                                                                                                    DataStoreException{message=DataStore subscriptionProcessor failed to start., cause=DataStoreException{message=Error during subscription., cause=ApiAuthException{message=Token is null, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}, recoverySuggestion=Check your internet.}
                                                                                                    	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$com-amplifyframework-datastore-syncengine-Orchestrator(Orchestrator.java:305)
                                                                                                    	at com.amplifyframework.datastore.syncengine.Orchestrator$$ExternalSyntheticLambda5.subscribe(Unknown Source:2)
                                                                                                    	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
                                                                                                    	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
```

**Comment by primico** [comment]
I saw this information below in another thread about a possible cause of the error I'm getting, however I have Auto-Merge Conflict Resolution enabled.. however I don't see a "lastChangedAt" and "version" in my data tables? Should I?

`if you are still experiencing this issue please make sure that DataStore is enabled on your AppSync API by configuring Conflict Resolution via the Amplify CLI command amplify update api. If you already had existing data before enabling DataStore, it will not be synced unless they have a value for _lastChangedAt and _version as they are required and non-nullable.`

**Comment by primico** [comment]
I have this in a file called Mutation.updateUser.req.vtl, but don't see these fields in my schema.graphql file, or in my model in amplify studio. Not sure if those fields should be in my model or not? Not even sure if this is my problem or not, just trying anything at this point to figure this out.

`#set( $keyFields = ["_version", "_deleted", "_lastChangedAt"] )`

**Comment by primico** [comment]
Getting an error trying to sync a Product, in amplify studio it says "Any signed-in users authenticated with Cognito User Pool can Create, Read, Update, and Delete Product", but Product in my schema.graphql says "allow:private" could this be my issue? I did "amplify pull" and "amplify codegen models"

![image](https://user-images.githubusercontent.com/6954991/226499584-f729696e-35db-4268-9f99-5c387ef77a91.png)
![image](https://user-images.githubusercontent.com/6954991/226500015-e9a09fb9-1f93-4eec-af85-e0ee60f30e0f.png)

**Comment by primico** [comment]
or what about this? could this be a problem?

![image](https://user-images.githubusercontent.com/6954991/226510049-7e566b53-dc06-47d0-8a35-4419268f83e6.png)

**Comment by primico** [comment]
spent a lot of time trying to get this working, but probably gonna cut my losses and switch to firebase unfortunately.

**Comment by Jordan-Nelson** [comment]
Hello @primico - Apologies for the delayed response. We will take a look at this issue today and see if we can reproduce it.

**Comment by HuiSF** [comment]
Hi @primico

I'm trying to digest the information you've provided. In the meantime, could you try to remove this from your `schema.graphql` first, and redeploy by `amplify push`?

```
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } }
```
