### ISSUE TITLE
RequestTimeTooSkewed when uploading to S3

### ISSUE THREAD

**Issue by bigbaliboy** [aws-amplify/amplify-flutter#2878]
### Description

I was trying to upload a basic text file to S3 using the example code in Amplify console. Got an error for RequestTimeTooSkewed. My aws region is ap-south-1 and I'm accessing it from Bahrain. What's the fix for this? 

`
Future<void> createAndUploadFilePublic() async {

      // Create a dummy file
      final exampleString = 'Example file contents';
      final tempDir = await getTemporaryDirectory();
      final exampleFile = File(tempDir.path + '/example.txt')
        ..createSync()
        ..writeAsStringSync(exampleString);
      // Upload the file to S3
      try {
        final UploadFileResult result = await Amplify.Storage.uploadFile(
          local: exampleFile,
          key: 'ExampleKey',
          options: S3UploadFileOptions(
            accessLevel: StorageAccessLevel.guest,
          ),
        );
        print('Successfully uploaded file: ${result.key}');
      } on StorageException catch (e) {
        print('Error uploading file: $e');
      }
    }
`
LOGS: 
`E/amplify:flutter:storage_s3(23745): StorageException
E/amplify:flutter:storage_s3(23745): StorageException{message=Something went wrong with your AWS S3 Storage upload file operation, cause=com.amazonaws.services.s3.model.AmazonS3Exception: <?xml version="1.0" encoding="UTF-8"?>
E/amplify:flutter:storage_s3(23745): <Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>20230415T160536Z</RequestTime><ServerTime>2023-04-15T19:29:34Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>ZJW22FAMM83ZDX1G</RequestId><HostId>1zlYEsKAlmdtmKuJKAD8CSF0WDfEe/1ufDwfi10NYfCr63tOWyeByCay7sAafWIEX/q47Na9FyQ=</HostId></Error> (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: ZJW22FAMM83ZDX1G), S3 Extended Request ID: 1zlYEsKAlmdtmKuJKAD8CSF0WDfEe/1ufDwfi10NYfCr63tOWyeByCay7sAafWIEX/q47Na9FyQ=, recoverySuggestion=See attached exception for more information and suggestions}
E/amplify:flutter:storage_s3(23745): 	at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:199)
E/amplify:flutter:storage_s3(23745): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:316)
E/amplify:flutter:storage_s3(23745): 	at android.os.Handler.handleCallback(Handler.java:958)
E/amplify:flutter:storage_s3(23745): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/amplify:flutter:storage_s3(23745): 	at android.os.Looper.loopOnce(Looper.java:205)
E/amplify:flutter:storage_s3(23745): 	at android.os.Looper.loop(Looper.java:294)
E/amplify:flutter:storage_s3(23745): 	at android.app.ActivityThread.main(ActivityThread.java:8128)
E/amplify:flutter:storage_s3(23745): 	at java.lang.reflect.Method.invoke(Native Method)
E/amplify:flutter:storage_s3(23745): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
E/amplify:flutter:storage_s3(23745): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
E/amplify:flutter:storage_s3(23745): Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: <?xml version="1.0" encoding="UTF-8"?>
E/amplify:flutter:storage_s3(23745): <Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>20230415T160536Z</RequestTime><ServerTime>2023-04-15T19:29:34Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>ZJW22FAMM83ZDX1G</RequestId><HostId>1zlYEsKAlmdtmKuJKAD8CSF0WDfEe/1ufDwfi10NYfCr63tOWyeByCay7sAafWIEX/q47Na9FyQ=</HostId></Error> (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: ZJW22FAMM83ZDX1G), S3 Extended Request ID: 1zlYEsKAlmdtmKuJKAD8CSF0WDfEe/1ufDwfi10NYfCr63tOWyeByCay7sAafWIEX/q47Na9FyQ=
E/amplify:flutter:storage_s3(23745): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
E/amplify:flutter:storage_s3(23745): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
E/amplify:flutter:storage_s3(23745): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
E/amplify:flutter:storage_s3(23745): 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4835)
E/amplify:flutter:storage_s3(23745): 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1912)
E/amplify:flutter:storage_s3(23745): 	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:282)
E/amplify:flutter:storage_s3(23745): 	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:114)
E/amplify:flutter:storage_s3(23745): 	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)`

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.10

### Amplify Flutter Version

0.6.13

### Deployment Method

Amplify CLI

**Comment by bigbaliboy** [comment]
Figured the issue was from the  emulator not being timed correctly, tried on a physical device and the error is gone. Closing the issue
