### ISSUE TITLE
cannot run amplify codegen 

### ISSUE THREAD

**Issue by rodrigobastosv** [aws-amplify/amplify-flutter#288]
**Describe the bug**
I'm following the https://docs.amplify.aws/lib/datastore/getting-started/q/platform/flutter docs to implement DataStore on my flutter app. Doing Auth and Storage was just a breeze. But when trying to implement the DataStore i got an error on the codegen step 

After creating a new graphql api and try to run `amplify codegen models` i got this error:

```
amplify-codegen-appsync-model-plugin not support language target flutter. Supported codegen targets arr java, android, swift, ios, javascript, typescript
Error: amplify-codegen-appsync-model-plugin not support language target flutter. Supported codegen targets arr java, android, swift, ios, javascript, typescript
    at Object.buildGeneratesSection (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/src/preset.ts:214:15)
    at Object.generateModels (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:44:67)
    at Object.run (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/commands/codegen/models.js:9:7)
    at Object.executeAmplifyCommand (/usr/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/amplify-plugin-index.js:9:3)
    at executePluginModuleCommand (/usr/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:161:3)
    at Object.executeCommand (/usr/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:25:5)
    at Object.run (/usr/lib/node_modules/@aws-amplify/cli/src/index.ts:92:5)
 ```

After some digging some tutorials advise to use the `amplify add codegen` command. But when i do i got the error:
```
flutter is not supported by codegen plugin
```

I'm a bit newbie with amplify and i'm feeling a bit lost.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android

**Comment by jamesonwilliams** [comment]
My guess is that you need to update your CLI. Codegen for Dart was only recently added to the CLI.

What version are you using? The latest version is 4.41.0.
```console
$ amplify -v
4.41.0
```

**Comment by rodrigobastosv** [comment]
Thanks @jamesonwilliams , that works!

**Comment by liamross** [comment]
I'm still having this issue:

```sh
$ amplify upgrade
This is the latest Amplify CLI version.
```

```sh
$ amplify -v
4.41.0
```

```sh
$ amplify add codegen
flutter is not supported by codegen plugin
```

```sh
$ amplify add codegen --apiId xxxxxxxxxx
✔ Getting API details
Successfully added API YourAppSync to your Amplify project
flutter is not supported by codegen plugin
```

**Comment by pedrommarquesm** [comment]
no news on this? version 4.44.0 out and I also have this problem

**Comment by Amplifiyer** [comment]
@liamross, @pedrommarquesm can you try this workaround mentioned here https://github.com/aws-amplify/amplify-flutter/issues/241#issuecomment-755565445

**Comment by pedrommarquesm** [comment]
@Amplifiyer My project is recent, that flag is set by default on `amplify init`

**Comment by hyobbb** [comment]
after updating amplify-cli with
`npm i -g @aws-amplify/cli`

solved problem.

**Comment by raywhiteside** [comment]
I am struggling to get this to work still. I have updated the Amplify CLI to 4.44.2,  and amplify_flutter is at 0.1.0. I am trying to do the workaround in cli.json, but I can't find that file in my amplify folder in this old project. I ran `amplify init` again and told it to re-use the current workspace, but I still don't see the cli.json.

I'm seeing this issue:


```
lib/models/ModelProvider.dart:23:7: Error: The non-abstract class 'ModelProvider' is missing implementations for these members:

 - ModelProviderInterface.getModelTypeByModelName
```

which seems to imply I don't have this commit from amplify-codegen from December:

https://github.com/aws-amplify/amplify-codegen/commit/b3daebb5b1425ca51fe6f85ff671960d6696510a

**Comment by hyobbb** [comment]
@raywhiteside if codeine is running in new version it should generate ModelProvider class overriding `getModelTypeByModelName` method. I had the same problem so I remove the project and start it over. #243 check this page.

**Comment by raywhiteside** [comment]
I copied my amplify folder and amplifyconfiguration.dart files to a different name, deleted the current versions, ran amplify init, and copied the new versions as well. Then I put the originals back and moved cli.json from the new amplify directory into the old one. Codegen now worked and I seemed to be synced up with my previous resources without issue after `amplify push`.

Wouldn't recommend trying to save the old space and I'm sure it will bite me at some point, but does work for now.

**Comment by raywhiteside** [comment]
Okay maybe this has bit me already. I'm trying to mock the API as described [here](https://aws.amazon.com/blogs/mobile/amplify-framework-local-mocking/) and [here](https://docs.amplify.aws/cli/usage/mock), and the `amplify mock` command runs `amplify codegen`. That fails with the same error as the OP:

```
flutter is not supported by codegen plugin
```

Which is the same error I get if I run `amplify codegen` myself. I can run `amplify codegen models` and it generates functional code (unlike when I posted earlier in this issue) and that has been sufficient for me thus far, but is seems I need more than a workaround now. `amplify codegen` itself needs to work.

I'm running version 4.45.2 of the Amplify CLI.

Is `amplify codegen` working for anyone on flutter?

**Comment by pedrommarquesm** [comment]
@raywhiteside That's exactly what happens to me. I just don't get it how some people in others open issues, say their problem is solved with updating the CLI... a final answer to this would be cool

**Comment by NKoroloff** [comment]
I have some problem. `flutter is not supported by codegen plugin`

**Comment by DavidTraina** [comment]
Same problem here on fresh flutter project and amplify cli `4.46.1`:
`flutter is not supported by codegen plugin`
