### ISSUE TITLE
Amplify Flutter's DownloadFile operation doesn't work with version ID

### ISSUE THREAD

**Issue by kharely** [aws-amplify/amplify-flutter#3108]
### Description

I have been trying to get a Data trying to add versionId in the key as parameters and adding it to the options, but the storage package returns "NoSuchKey" and I check my s3 path and I have the file, If I remove versionId it returns correctly, but I need the file based on the version.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hey @kharely 

Can you please provide the relevant code snippets? 

Can you provide the full log output?

**Comment by kharely** [comment]
This is the full log output
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: StorageKeyNotFoundException {
  "message": "Cannot find the item specified by the key and access level.",
  "recoverySuggestion": "Ensure that correct object key is provided, and/or correct `StorageAccessLevel` and `targetIdentityId` are included in the options.",
  "underlyingException": "NoSuchKey {\n}"
}
#0      S3DownloadTask._getObject (package:amplify_storage_s3_dart/src/storage_s3_service/service/task/s3_download_task.dart:367:7)
<asynchronous suspension>
#1      S3DownloadTask.start (package:amplify_storage_s3_dart/src/storage_s3_service/service/task/s3_download_task.dart:152:31)
<asynchronous suspension>
```

I didn't find a right way to get the file with the version and I tried with the versionId as parameter

```
 Future<Uint8List> downloadData(key, {String? version}) async {
    String url = key;
    if (version != null && version != '') {
      // Amplify does not return file with version
      url = "$url?versionId=$version";
    }
      final request = Amplify.Storage.downloadData(
        key: url,
      );

      final result = await request.result;
      return result.bytes as Uint8List;
  }
```

**Comment by HuiSF** [comment]
Hi @kharely thank you for opening this issue.

Currently Amplify Flutter doesn't support download by version id. I will mark this a as a feature request.
