### ISSUE TITLE
onNotificationReceivedInForeground error: type 'String' is not a subtype of type 'Map<Object?, Object?>?' in type cast;stackTrace:#0      new PushNotificationMessage.fromJson (package:amplify_core/src/types/notifications/push/push_notification_message.dart:35:34)

### ISSUE THREAD

**Issue by zilaiyedaren** [aws-amplify/amplify-flutter#3435]
### Description

iOS push:
onNotificationReceivedInForeground error: type 'String' is not a subtype of type 'Map<Object?, Object?>?' in type cast;stackTrace:#0      new PushNotificationMessage.fromJson (package:amplify_core/src/types/notifications/push/push_notification_message.dart:35:34)

amplify_flutter: 1.1.0
amplify_core: 1.1.0
amplify_auth_cognito: 1.1.0 
amplify_push_notifications_pinpoint: 1.1.0

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by zilaiyedaren** [comment]
AWS SNS push message parase error

**Comment by Equartey** [comment]
Hey @zilaiyedaren

Sorry you ran into this issue.

Could you please provide more context around how you received this error?

Can you provide the message you tried to send from pinpoint?

**Comment by dnys1** [comment]
Hi @zilaiyedaren, sorry for the delay in resolving this. I have a PR open for the fix: https://github.com/aws-amplify/amplify-flutter/pull/3502

**Comment by dnys1** [comment]
The fix for this has been released in v1.3.1 of the libraries. Thanks for your patience.

**Comment by satoyan** [comment]
still this bug can be reproduced when received FCM message. 

```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════                                                                                                     
The following _TypeError was thrown during a platform message callback:                                                                                                                                  
type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, Object?>?' in type cast                                                                                                              
                                                                                                                                                                                                         
When the exception was thrown, this was the stack:                                                                                                                                                       
#0      new PushNotificationMessage.fromJson (package:amplify_core/src/types/notifications/push/push_notification_message.dart:24:32)                                                                    #1      AmplifyPushNotificationsFlutterApi.onNotificationReceivedInBackground (package:amplify_push_notifications/src/push_notifications_flutter_api.dart:117:50)                                        
#2      PushNotificationsFlutterApi.setup.<anonymous closure> (package:amplify_push_notifications/src/native_push_notifications_plugin.g.dart:128:21)                                                    
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)                                                                            
#4      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:35)                                                                                 
#5      _invoke2 (dart:ui/hooks.dart:174:13)                                                                                                                                                             
#6      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)                                                                                                                                #7      _Channel.push (dart:ui/channel_buffers.dart:130:31)                                                                                                                                              
#8      ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)                                                                                                                                        
#9      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:686:22)                                                                                                            
#10     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)                                                                                                                                              
════════════════════════════════════════════════════════════════════════════════════════════════════                           
```

**Comment by dnys1** [comment]
Hi @satoyan sorry you are facing this issue. Can you please open a new issue ticket so that we can track this appropriately?
