### ISSUE TITLE
"Amplify is already configured. Adding plugins after configure is not supported" exception

### ISSUE THREAD

**Issue by graphicbeacon** [aws-amplify/amplify-flutter#344]
**Describe the bug**
Thanks for the work you guys are doing here! I am getting an "Amplify is already configured" exception upon returning to the screen where I initialised the Amplify plugins. This is happening on 0.0.2-dev.1

**To Reproduce**

1. Visit the initial screen where amplify auth plugin is configured.
2. Visit another screen
3. Return to the initial screen where amplify auth plugin is configured
4. See error.

**Expected behavior**
There should not be an error displayed.

**Screenshots**
Here's what the error looks like:

```bash
E/flutter (25168): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Amplify is already configured. Adding plugins after configure is not supported.
E/flutter (25168): #0      AmplifyClass.addPlugin (package:amplify_flutter/amplify.dart:86:7)
E/flutter (25168): #1      _EntryScreenState._configureAmplify (package:amp_awesome/screens/entry.dart:25:15)
E/flutter (25168): #2      _EntryScreenState.initState (package:amp_awesome/screens/entry.dart:20:5)
E/flutter (25168): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4821:57)
E/flutter (25168): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
E/flutter (25168): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4709:16)
E/flutter (25168): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4378:5)
E/flutter (25168): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4663:5)
E/flutter (25168): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
E/flutter (25168): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4709:16)
E/flutter (25168): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4856:11)
E/flutter (25168): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4378:5)
E/flutter (25168): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4663:5)
E/flutter (25168): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4847:11)
E/flutter (25168): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
E/flutter (25168): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4709:16)
E/flutter (25168): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4856:11)
E/flutter (25168): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4378:5)
E/flutter (25168): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4663:5)
E/flutter (25168): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4847:11)
E/flutter (25168): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
E/flutter (25168): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4709:16)
E/flutter (25168): #45     Element.rebuild (package:flut
E/flutter (25168): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Amplify is already configured. Adding plugins after configure is not supported.
E/flutter (25168): #0      AmplifyClass.addPlugin (package:amplify_flutter/amplify.dart:86:7)
E/flutter (25168): #1      _EntryScreenState._configureAmplify (package:amp_awesome/screens/entry.dart:26:15)
E/flutter (25168): #2      _EntryScreenState.initState (package:amp_awesome/screens/entry.dart:20:5)
E/flutter (25168): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4821:57)
E/flutter (25168): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
E/flutter (25168): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4709:16)
E/flutter (25168): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4378:5)
E/flutter (25168): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4663:5)
E/flutter (25168): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
E/flutter (25168): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4709:16)
E/flutter (25168): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4856:11)
E/flutter (25168): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4378:5)
E/flutter (25168): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4663:5)
E/flutter (25168): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4847:11)
E/flutter (25168): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
E/flutter (25168): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6173:14)
E/flutter (25168): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4709:16)
E/flutter (25168): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4856:11)
E/flutter (25168): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4378:5)
E/flutter (25168): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4663:5)
E/flutter (25168): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4847:11)
E/flutter (25168): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
E/flutter (25168): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
E/flutter (25168): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
E/flutter (25168): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4709:16)
E/flutter (25168): #45     Element.rebuild (package:flut
I/flutter (25168): Bad state: Amplify has already been configured and re-configuration is not supported.
```

This leads to the app breaking entirely:

**_Before_**
<img src="https://user-images.githubusercontent.com/2960965/106689830-9275f280-65c8-11eb-9543-449dd364ab38.png" width="300" />

**_After_**
<img src="https://user-images.githubusercontent.com/2960965/106689893-acafd080-65c8-11eb-85e6-88cd592cc33e.png" width="300" />

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS (_Haven't checked on iOS, but I suspect it will be the same_)

**Smartphone (please complete the following information):**
 - Device: Android Simulator

**Additional context**

This is similar to https://github.com/aws-amplify/amplify-flutter/issues/300

I did some digging in your latest changes and realised it could have been mitigated if `isConfigured` wasn't removed in the below commit:

https://github.com/aws-amplify/amplify-flutter/commit/dea801048d532f494601e10879ec6601ec977832#diff-4d4af0621e2ae3ca315167833741804894e7d9070700bcfb0e1ce603d448438dL103-L107

I think we need this code back:

```dart
class AmplifyClass extends PlatformInterface {
  ...
  ...
/// Returns whether Amplify has been configured or not.	
  bool get isConfigured {	
    return _isConfigured;	
  }
```
so that we can do:

```dart
if (!Amplify.isConfigured) {
  await Amplify.configure(amplifyconfig);
}
```

**Comment by gauravmehta13** [comment]
facing same issue

**Comment by Amplifiyer** [comment]
Thanks @graphicbeacon, @gauravmehta13 for reporting this issue. We discussed the value of `isConfigured` and decided to rather use a specific exception to tackle this. We will have a release soon with this new exception and with that you can catch and ignore that specific exception instead of checking `isConfigured`. See the code sample below


https://github.com/aws-amplify/amplify-flutter/blob/036edd14571aa5cb7229d6ddc29e82c0c9435883/example/lib/main.dart#L63-L69

Will update here once the release is out.

**Comment by graphicbeacon** [comment]
@Amplifiyer That sounds good. Looking forward to the release

**Comment by Amplifiyer** [comment]
This is released today in version 0.0.2-dev.2, use the new `AmplifyAlreadyConfiguredException` for catching duplicate configuration related issues. Let us know if you are face any issues. Closing this.

**Comment by gauravmehta13** [comment]
> This is released today in version 0.0.2-dev.2, use the new `AmplifyAlreadyConfiguredException` for catching duplicate configuration related issues. Let us know if you are face any issues. Closing this.

![image](https://user-images.githubusercontent.com/51997260/107473863-5c6fda00-6b97-11eb-8f70-37e16665ae1f.png)
Giving this error after update

**Comment by gauravmehta13** [comment]
![image](https://user-images.githubusercontent.com/51997260/107473961-81fce380-6b97-11eb-8f74-d52d274aa714.png)
for this line, Can you tell me wht to replace for catching auth error

**Comment by Amplifiyer** [comment]
@gauravmehta13 Please see our list of breaking changes that include the error types change. `AuthError` is now `AuthException` with more fine granular [subtypes ](https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_auth_plugin_interface/lib/src/Exceptions)

`AmplifyAlreadyConfiguredException` is exported from the top level package `amplify_flutter`. Please clean your project and try again ensuring you are using all of the latest packages (currently 0.0.2-dev.2)

**Comment by Abhishek-cmd13** [comment]
I am facing the same issue can anyone help to resolve the same.
