### ISSUE TITLE
Developer menu causing crash in production

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#346]
Hi there.

I had the following crash in production:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.amplifyframework.devmenu.PersistentLogStoragePlugin.getLogs()' on a null object reference
       at com.amplifyframework.devmenu.DeveloperMenu.getLogs(DeveloperMenu.java:2)
       at com.amplifyframework.devmenu.DevMenuLogsFragment.onCreateView(DevMenuLogsFragment.java:31)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:15)
       at androidx.fragment.app.FragmentStateManager.a(FragmentStateManager.java:179)
       at androidx.fragment.app.FragmentManager.a(FragmentManager.java:237)
       at androidx.fragment.app.FragmentManager.a(FragmentManager.java:37)
       at androidx.fragment.app.FragmentManager.b(FragmentManager.java:130)
       at androidx.fragment.app.FragmentManager.c(FragmentManager.java:94)
       at androidx.fragment.app.FragmentManager.c(FragmentManager.java:21)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:3)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I think this exception is linked to the developer menus as the log says. The problem is that the log menu should not appear in release mode. Can you guys please help me with that? Could you guys please release the "pending-release" feature to avoid this crash?

**Comment by haverchuck** [comment]
@brunovsiqueira We are getting ready to do a release as soon as we are able. In the interim, if you want to make the change locally [this is the relevant line](https://github.com/aws-amplify/amplify-flutter/blob/cc36ecc9f246eff99d90963cec50a39fd66ea3c0/packages/amplify_flutter/android/src/main/kotlin/com/amazonaws/amplify/Amplify.kt#L122).

**Comment by Amplifiyer** [comment]
This is released today in version 0.0.2-dev.2. Let us know if you are still facing any issues. Closing this.
