### ISSUE TITLE
Couple of bugs with AppSync and DataStore on Android

### ISSUE THREAD

**Issue by wojciechzahradnikdeviniti** [aws-amplify/amplify-flutter#3580]
### Description

I have couple of bugs on Android using AppSync and DataStore.

1. https://github.com/aws-amplify/amplify-flutter/issues/1479 https://github.com/aws-amplify/amplify-android/issues/1690 - it's the most annoying and imo FATAL bug. I need to delay start method after clean/stop for ~45 seconds. If not that error occurs:

```
Thread interrupted awaiting subscription acknowledgement.
    java.lang.InterruptedException
```

2. https://github.com/aws-amplify/amplify-flutter/issues/3575 - start method throws exception after lib update to 1.3.2 and 1.3.3
```
E/amplify:flutter:datastore(15444): DataStoreException{message=Failed to start DataStore., cause=DataStoreException{message=Timed out while starting to observe storage changes., cause=com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Array: null, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
E/amplify:flutter:datastore(15444): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
E/amplify:flutter:datastore(15444): match your scenario, and file an issue with the details of the bug if there isn't.}, recoverySuggestion=Retry.}
E/amplify:flutter:datastore(15444): 	at com.amplifyframework.datastore.AWSDataStorePlugin.lambda$start$12(AWSDataStorePlugin.java:331)
E/amplify:flutter:datastore(15444): 	at com.amplifyframework.datastore.AWSDataStorePlugin$$ExternalSyntheticLambda34.accept(Unknown Source:4)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:64)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onError(CompletableAndThenCompletable.java:62)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:40)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
2
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout$TimeOutObserver.onComplete(CompletableTimeout.java:87)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:47)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout.subscribeActual(CompletableTimeout.java:53)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
E/amplify:flutter:datastore(15444): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
E/amplify:flutter:datastore(15444): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:flutter:datastore(15444): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/amplify:flutter:datastore(15444): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:datastore(15444): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:datastore(15444): 	at java.lang.Thread.run(Thread.java:920)
E/amplify:flutter:datastore(15444): Caused by: DataStoreException{message=Timed out while starting to observe storage changes., cause=com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Array: null, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
E/amplify:flutter:datastore(15444): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
```

3. https://github.com/aws-amplify/amplify-android/issues/2471 - when I have already some data in the DataStore and sync is doing updates this error occurs (each time with different model):
```
W/amplify:aws-datastore(24053): Initial cloud sync failed for FlowTemplate.
W/amplify:aws-datastore(24053): IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}
W/amplify:aws-datastore(24053): 	at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$syncPage$14(SyncProcessor.java:316)
W/amplify:aws-datastore(24053): 	at com.amplifyframework.datastore.syncengine.SyncProcessor$$ExternalSyntheticLambda19.accept(Unknown Source:4)
W/amplify:aws-datastore(24053): 	at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda1.accept(Unknown Source:4)
W/amplify:aws-datastore(24053): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:153)
W/amplify:aws-datastore(24053): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
W/amplify:aws-datastore(24053): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/amplify:aws-datastore(24053): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/amplify:aws-datastore(24053): 	at java.lang.Thread.run(Thread.java:1012)
E/amplify:flutter:datastore(24053): DataStoreException{message=Initial cloud sync failed for FlowTemplate., cause=IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}, recoverySuggestion=Check your internet connection.}
E/amplify:aws-datastore(24053): Failure encountered while attempting to start API sync.
E/amplify:aws-datastore(24053): DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.lang.RuntimeException: IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
E/amplify:aws-datastore(24053): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
E/amplify:aws-datastore(24053): match your scenario, and file an issue with the details of the bug if there isn't.}
E/amplify:aws-datastore(24053): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$4$com-amplifyframework-datastore-syncengine-Orchestrator(Orchestrator.java:338)
E/amplify:aws-datastore(24053): 	at com.amplifyframework.datastore.syncengine.Orchestrator$$ExternalSyntheticLambda8.subscribe(Unknown Source:2)
E/amplify:aws-datastore(24053): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
E/amplify:aws-datastore(24053): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
```

4. Another collections cast exception during sync
```
E/amplify:flutter:datastore( 5711): Failed to parse and send subscriptionDataProcessed event: 
E/amplify:flutter:datastore( 5711): java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to com.amplifyframework.core.model.SerializedCustomType
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:99)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:56)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.hub.FlutterSubscriptionDataProcessedEvent.toValueMap(FlutterSubscriptionDataProcessedEvent.kt:25)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.sendPayload(DataStoreHubEventStreamHandler.kt:200)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.getHubListener$lambda-0(DataStoreHubEventStreamHandler.kt:78)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.$r8$lambda$hFBWgPzsdNPuhSYi4oGLjITrVpg(Unknown Source:0)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler$$ExternalSyntheticLambda0.onEvent(Unknown Source:2)
E/amplify:flutter:datastore( 5711): 	at com.amplifyframework.hub.AWSHubPlugin.lambda$publish$0(AWSHubPlugin.java:60)
E/amplify:flutter:datastore( 5711): 	at com.amplifyframework.hub.AWSHubPlugin$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/amplify:flutter:datastore( 5711): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:datastore( 5711): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:datastore( 5711): 	at java.lang.Thread.run(Thread.java:920)
```

Because of those bugs my app doesn't work good on Android. In fact, it doesn't work at all.
On iOS it works fine - sync is fast and no major issues exist.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.3.2, 1.3.3

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @wojciechzahradnikdeviniti thanks for taking the time to compile these issues that are affecting your experience on Amplify Datastore for Android. 

As you likely understand, Amplify Flutter for Datastore relies on Amplify Android which is another repo/team.  I will reach out to them regarding your 1rst and 3rd issue to see what prioritization they might have. 

I responded to your comment on the 2nd issue.  Does setting an empty array fix your problem?  We will investigate a fix, but adding that should resolve the exception for now.

**Comment by fjnoyp** [comment]
Hi @wojciechzahradnikdeviniti we spoke with the Android team and they will investigate more next week.  Thanks for your patience and understanding here.

**Comment by wojciechzahradnikdeviniti** [comment]
> Hi @wojciechzahradnikdeviniti thanks for taking the time to compile these issues that are affecting your experience on Amplify Datastore for Android.
> 
> As you likely understand, Amplify Flutter for Datastore relies on Amplify Android which is another repo/team. I will reach out to them regarding your 1rst and 3rd issue to see what prioritization they might have.
> 
> I responded to your comment on the 2nd issue. Does setting an empty array fix your problem? We will investigate a fix, but adding that should resolve the exception for now.

I don't understand. Where should I set empty array? It happens when there is something already synced and I want to call start again after for example entering to the app for the second time.

**Comment by wojciechzahradnikdeviniti** [comment]
hi @fjnoyp are you going to create a new version of the flutter lib with bugs which have been fixed with the Android 2.12.0 version https://github.com/aws-amplify/amplify-android/pull/2571?

**Comment by wojciechzahradnikdeviniti** [comment]
hi @fjnoyp Thanks for fixing 1st and 2nd bug - now its working. 
But now 3rd bug appears and I cant sync date when something is already in the database.
As I said before this bug occurs each time with different model.

```
/amplify:aws-datastore( 5550): Initial cloud sync failed for QuestionItemTemplate.
W/amplify:aws-datastore( 5550): IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$syncPage$16(SyncProcessor.java:325)
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.SyncProcessor$$ExternalSyntheticLambda19.accept(Unknown Source:4)
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda1.accept(Unknown Source:4)
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:153)
W/amplify:aws-datastore( 5550): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
W/amplify:aws-datastore( 5550): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/amplify:aws-datastore( 5550): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/amplify:aws-datastore( 5550): 	at java.lang.Thread.run(Thread.java:1012)
E/amplify:flutter:datastore( 5550): DataStoreException{message=Initial cloud sync failed for QuestionItemTemplate., cause=IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}, recoverySuggestion=Check your internet connection.}
E/amplify:aws-datastore( 5550): Failure encountered while attempting to start API sync.
E/amplify:aws-datastore( 5550): DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.lang.RuntimeException: IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
E/amplify:aws-datastore( 5550): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
E/amplify:aws-datastore( 5550): match your scenario, and file an issue with the details of the bug if there isn't.}
E/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$4$com-amplifyframework-datastore-syncengine-Orchestrator(Orchestrator.java:362)
E/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.Orchestrator$$ExternalSyntheticLambda8.subscribe(Unknown Source:2)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
E/amplify:aws-datastore( 5550): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/amplify:aws-datastore( 5550): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
E/amplify:aws-datastore( 5550): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/amplify:aws-datastore( 5550): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/amplify:aws-datastore( 5550): 	at java.lang.Thread.run(Thread.java:1012)
E/amplify:aws-datastore( 5550): Caused by: java.lang.RuntimeException: IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
E/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1461)
E/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$4$com-amplifyframework-datastore-syncengine-Orchestrator(Orchestrator.java:358)
E/amplify:aws-datastore( 5550): 	... 18 more
E/amplify:aws-datastore( 5550): Caused by: IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}
E/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$syncPage$16(SyncProcessor.java:325)
E/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.SyncProcessor$$ExternalSyntheticLambda19.accept(Unknown Source:4)
E/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda1.accept(Unknown Source:4)
E/amplify:aws-datastore( 5550): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:153)
E/amplify:aws-datastore( 5550): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
E/amplify:aws-datastore( 5550): 	... 3 more
W/amplify:aws-datastore( 5550): API sync failed - transitioning to LOCAL_ONLY.
W/amplify:aws-datastore( 5550): DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.lang.RuntimeException: IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
W/amplify:aws-datastore( 5550): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
W/amplify:aws-datastore( 5550): match your scenario, and file an issue with the details of the bug if there isn't.}
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$4$com-amplifyframework-datastore-syncengine-Orchestrator(Orchestrator.java:362)
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.Orchestrator$$ExternalSyntheticLambda8.subscribe(Unknown Source:2)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
W/amplify:aws-datastore( 5550): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/amplify:aws-datastore( 5550): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
W/amplify:aws-datastore( 5550): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/amplify:aws-datastore( 5550): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/amplify:aws-datastore( 5550): 	at java.lang.Thread.run(Thread.java:1012)
W/amplify:aws-datastore( 5550): Caused by: java.lang.RuntimeException: IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
W/amplify:aws-datastore( 5550): 	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1461)
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$4$com-amplifyframework-datastore-syncengine-Orchestrator(Orchestrator.java:358)
W/amplify:aws-datastore( 5550): 	... 18 more
W/amplify:aws-datastore( 5550): Caused by: IrRecoverableException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$syncPage$16(SyncProcessor.java:325)
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.syncengine.SyncProcessor$$ExternalSyntheticLambda19.accept(Unknown Source:4)
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda1.accept(Unknown Source:4)
W/amplify:aws-datastore( 5550): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:153)
W/amplify:aws-datastore( 5550): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
W/amplify:aws-datastore( 5550): 	... 3 more
I/amplify:aws-datastore( 5550): Orchestrator transitioning from SYNC_VIA_API to LOCAL_ONLY
I/amplify:aws-datastore( 5550): Stopping subscription processor.
I/amplify:aws-datastore( 5550): Stopped subscription processor.
I/amplify:aws-datastore( 5550): Setting currentState to LOCAL_ONLY
```

**Comment by Jordan-Nelson** [comment]
@wojciechzahradnikdeviniti - Can you create a new issue for this and fill out the details in the issue template including the reproduction steps? Please provide your schema (or a minimal version of your schema that can be used to repro) as well so we can reproduce this.

**Comment by wojciechzahradnikdeviniti** [comment]
@Jordan-Nelson no problem - done :)

**Comment by Jordan-Nelson** [comment]
Thanks. I'm going to close this issue out now that we have separate issues tracking each one.
