### ISSUE TITLE
MissingPluginException No implementation found for method configure on channel com.amazonaws.amplify/core

### ISSUE THREAD

**Issue by rayhaanq** [aws-amplify/amplify-flutter#361]
1. Log in
2. Close app fully
3. When I access the app again I get the following error:
```
E/flutter (22494): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method configure on channel com.amazonaws.amplify/core)
E/flutter (22494): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (22494): <asynchronous suspension>
E/flutter (22494): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (22494): #2      MethodChannelAmplifyCore.configure (package:amplify_core_plugin_interface/method_channel_amplify.dart:25:21)
E/flutter (22494): #3      Amplify.configure (package:amplify_core/amplify_core.dart:86:35)
E/flutter (22494): #4      AuthService.configureAmplify (package:myapp/services/auth.service.dart:96:28)
E/flutter (22494): #5      _MyAppState.initState (package:myapp/main.dart:39:10)
E/flutter (22494): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (22494): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (22494): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (22494): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (22494): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (22494): #11     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
E/flutter (22494): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (22494): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (22494): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (22494): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (22494): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (22494): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (22494): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (22494): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (22494): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (22494): #21     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
E/flutter (22494): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (22494): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (22494): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (22494): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (22494): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (22494): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (22494): #28     _NestedHookElement.mount (package:nested/nested.dart:188:11)
E/flutter (22494): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (22494): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (22494): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (22494): #32     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:426:11)
E/flutter (22494): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (22494): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (22494): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (22494): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (22494): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (22494): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (22494): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (22494): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (22494): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (22494): #42     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
E/flutter (22494): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (22494): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (22494): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (22494): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (22494): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (22494): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (22494): #49     _NestedHookElement.mount (package:nested/nested.dart:188:11)
E/flutter (22494): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (22494): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (22494): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (22494): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (22494): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (22494): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (22494): #56     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
E/flutter (22494): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (22494): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (22494): #59     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
E/flutter (22494): #60     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1223:5)
E/flutter (22494): #61     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1165:17)
E/flutter (22494): #62     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2683:19)
E/flutter (22494): #63     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1164:13)
E/flutter (22494): #64     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:974:7)
E/flutter (22494): #65     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:955:7)
E/flutter (22494): #66     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (22494): #67     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (22494): #68     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (22494): #69     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (22494): #70     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (22494): #71     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (22494): #72     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (22494): #73     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (22494): #74     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (22494): #75     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (22494): #76     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (22494):
```

I've tried doing a `flutter clean` and uninstalling the app completely but still no luck.
I've tried this with the following versions:
`amplify_core: 0.0.1-dev.6`
`amplify_auth_cognito: 0.0.1-dev.6`
and
`amplify_flutter: 0.0.2-dev.1`
`amplify_auth_cognito: 0.0.2-dev.1`

Most of the other issues I've seen with a similar error suggest doing a `flutter clean` but this has not worked for me.

**Expected behavior**
There should be no errors and user should be able to continue where they left off since they've already signed in without signing out.

**Workarounds**
Currently just catching the `Amplify.configure` exception and then doing nothing.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
Only tested on Android.

**Smartphone (please complete the following information):**
 - Device: Emulator and Samsung Galaxy S10+

Thanks

**Comment by Amplifiyer** [comment]
This is released today in version 0.0.2-dev.2. You'd still have to catch `AmplifyAlreadyConfiguredException` since flutter kills the activity that is configuring the Amplify and when the activity is restarted it would try to reconfigure Amplify.  for an example

https://github.com/aws-amplify/amplify-flutter/blob/036edd14571aa5cb7229d6ddc29e82c0c9435883/example/lib/main.dart#L63-L69
