### ISSUE TITLE
Cannot cast to com.amplifyframework.core.model.SerializedCustomType on Android

### ISSUE THREAD

**Issue by wojciechzahradnikdeviniti** [aws-amplify/amplify-flutter#3673]
### Description

Hi, on Android when I'm doing sync then ClassCastException occurrs. On iOS it works fine.

I'm creating a new issue according to @Jordan-Nelson comment.

https://github.com/aws-amplify/amplify-flutter/issues/3580

```
E/amplify:flutter:datastore( 5711): Failed to parse and send subscriptionDataProcessed event: 
E/amplify:flutter:datastore( 5711): java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to com.amplifyframework.core.model.SerializedCustomType
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:99)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:56)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.types.hub.FlutterSubscriptionDataProcessedEvent.toValueMap(FlutterSubscriptionDataProcessedEvent.kt:25)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.sendPayload(DataStoreHubEventStreamHandler.kt:200)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.getHubListener$lambda-0(DataStoreHubEventStreamHandler.kt:78)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.$r8$lambda$hFBWgPzsdNPuhSYi4oGLjITrVpg(Unknown Source:0)
E/amplify:flutter:datastore( 5711): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler$$ExternalSyntheticLambda0.onEvent(Unknown Source:2)
E/amplify:flutter:datastore( 5711): 	at com.amplifyframework.hub.AWSHubPlugin.lambda$publish$0(AWSHubPlugin.java:60)
E/amplify:flutter:datastore( 5711): 	at com.amplifyframework.hub.AWSHubPlugin$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/amplify:flutter:datastore( 5711): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:datastore( 5711): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:datastore( 5711): 	at java.lang.Thread.run(Thread.java:920)
```

```
factory ObjectTemplate({String? id, bool? isArchived, required String name, required String description, required String clientId, required String createdById, required FlowType flowType, List<Job>? jobs, List<String>? regionIds}) {
    return ObjectTemplate._internal(
      id: id == null ? amplify_core.UUID.getUUID() : id,
      isArchived: isArchived,
      name: name,
      description: description,
      clientId: clientId,
      createdById: createdById,
      flowType: flowType,
      jobs: jobs != null ? List<Job>.unmodifiable(jobs) : jobs,
      regionIds: regionIds != null ? List<String>.unmodifiable(regionIds) : regionIds);
  }
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.4.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type ObjectTemplate @model @auth(rules: [{ allow: private }, { allow: private, provider: iam }]) {
  id: ID!
  isArchived: Boolean
  name: String!
  description: String!
  clientId: ID! @index(name: "byClient", queryField: "objectTemplateByClient")
  createdById: ID!
  flowType: FlowType!
  jobs: [Job] @hasMany(indexName: "byFlow", fields: ["id"])
  regionIds: [ID]
}
```

**Comment by Jordan-Nelson** [comment]
Hi @wojciechzahradnikdeviniti - Can you share the schema definition for FlowType? The error occurs during a case which I believe is from a non-model type. If you have any other non model types in your schema, please share them as well. Thanks.

**Comment by wojciechzahradnikdeviniti** [comment]
@wojciechzahradnikdeviniti 
```
enum FlowType {
  ONE,
  TWO
}
```

**Comment by dnys1** [comment]
Hi @wojciechzahradnikdeviniti, can you please also provide the definition of `Job`?

**Comment by dnys1** [comment]
Could you also provide more of the surrounding log messages leading up to the error?

**Comment by wojciechzahradnikdeviniti** [comment]
hi @dnys1, sure:

```
type Job @model @searchable @auth(rules: [{ allow: private }, { allow: private, provider: iam }]) {
  id: ID!
  addressId: ID!
  approved: AWSDateTime
  approvedByUserId: ID
  archivedDate: AWSDateTime @index(name: "byArchivedDate", queryField: "jobByArchivedDate")
  cancelledByUserId: ID
  cancellationTypeId: ID
  cancelledDate: AWSDateTime @index(name: "byCancelledDate", queryField: "jobByCancelledDate")
  completedDate: AWSDateTime @index(name: "byCompletedDate", queryField: "jobByCompletedDate")
  createdById: ID
  escalated: AWSDateTime
  escalatedByUserId: ID
  object: ObjectTemplate @belongsTo(fields: ["objectId"])
  objectId: ID @index(name: "byObject", queryField: "jobByObject")
  currentStageId: ID
  currentStage: Stage @hasOne(fields: ["currentStageId"])
  currentStepId: ID
  currentStep: Step @hasOne(fields: ["currentStepId"])
  insuranceCompanyId: ID
  jobType: JobType
  dwellingType: DwellingType
  regionId: ID! @index(name: "byRegion", queryField: "jobByRegion")
  clientId: ID @index(name: "byClient", queryField: "jobByClient")
  salesRepId: ID
  leadTypeId: ID
  paperworkApprovedDate: AWSDateTime
  contingencySignedDate: AWSDateTime
}
```

```
I/flutter ( 4998): AwsAmplifyUserApi - syncDataStore - event subscriptionDataProcessed
I/amplify:aws-datastore( 4998): Successfully sync'd down model state from cloud.
I/flutter ( 4998): AwsAmplifyUserApi - syncDataStore - event modelSynced
E/amplify:flutter:datastore( 4998): java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to com.amplifyframework.core.model.SerializedCustomType
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:99)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:56)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.hub.FlutterSubscriptionDataProcessedEvent.toValueMap(FlutterSubscriptionDataProcessedEvent.kt:25)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.sendPayload(DataStoreHubEventStreamHandler.kt:200)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.getHubListener$lambda-0(DataStoreHubEventStreamHandler.kt:78)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.$r8$lambda$hFBWgPzsdNPuhSYi4oGLjITrVpg(Unknown Source:0)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler$$ExternalSyntheticLambda0.onEvent(Unknown Source:2)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin.lambda$publish$0(AWSHubPlugin.java:60)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/amplify:flutter:datastore( 4998): 	at java.lang.Thread.run(Thread.java:1012)
D/EGL_emulation( 4998): app_time_stats: avg=3.35ms min=1.88ms max=6.21ms count=60
E/amplify:flutter:datastore( 4998): Failed to parse and send subscriptionDataProcessed event: 
E/amplify:flutter:datastore( 4998): java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to com.amplifyframework.core.model.SerializedCustomType
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:99)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:56)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.hub.FlutterSubscriptionDataProcessedEvent.toValueMap(FlutterSubscriptionDataProcessedEvent.kt:25)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.sendPayload(DataStoreHubEventStreamHandler.kt:200)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.getHubListener$lambda-0(DataStoreHubEventStreamHandler.kt:78)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.$r8$lambda$hFBWgPzsdNPuhSYi4oGLjITrVpg(Unknown Source:0)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler$$ExternalSyntheticLambda0.onEvent(Unknown Source:2)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin.lambda$publish$0(AWSHubPlugin.java:60)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/amplify:flutter:datastore( 4998): 	at java.lang.Thread.run(Thread.java:1012)
E/amplify:flutter:datastore( 4998): Failed to parse and send subscriptionDataProcessed event: 
E/amplify:flutter:datastore( 4998): java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to com.amplifyframework.core.model.SerializedCustomType
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:99)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:56)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.hub.FlutterSubscriptionDataProcessedEvent.toValueMap(FlutterSubscriptionDataProcessedEvent.kt:25)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.sendPayload(DataStoreHubEventStreamHandler.kt:200)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.getHubListener$lambda-0(DataStoreHubEventStreamHandler.kt:78)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.$r8$lambda$hFBWgPzsdNPuhSYi4oGLjITrVpg(Unknown Source:0)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler$$ExternalSyntheticLambda0.onEvent(Unknown Source:2)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin.lambda$publish$0(AWSHubPlugin.java:60)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/amplify:flutter:datastore( 4998): 	at java.lang.Thread.run(Thread.java:1012)
I/amplify:aws-datastore( 4998): Successfully sync'd down model state from cloud.
I/flutter ( 4998): AwsAmplifyUserApi - syncDataStore - event modelSynced
E/amplify:flutter:datastore( 4998): Failed to parse and send subscriptionDataProcessed event: 
E/amplify:flutter:datastore( 4998): java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to com.amplifyframework.core.model.SerializedCustomType
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:99)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:56)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.hub.FlutterSubscriptionDataProcessedEvent.toValueMap(FlutterSubscriptionDataProcessedEvent.kt:25)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.sendPayload(DataStoreHubEventStreamHandler.kt:200)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.getHubListener$lambda-0(DataStoreHubEventStreamHandler.kt:78)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.$r8$lambda$hFBWgPzsdNPuhSYi4oGLjITrVpg(Unknown Source:0)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler$$ExternalSyntheticLambda0.onEvent(Unknown Source:2)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin.lambda$publish$0(AWSHubPlugin.java:60)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/amplify:flutter:datastore( 4998): 	at java.lang.Thread.run(Thread.java:1012)
E/amplify:flutter:datastore( 4998): Failed to parse and send subscriptionDataProcessed event: 
E/amplify:flutter:datastore( 4998): java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to com.amplifyframework.core.model.SerializedCustomType
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:99)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:56)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.types.hub.FlutterSubscriptionDataProcessedEvent.toValueMap(FlutterSubscriptionDataProcessedEvent.kt:25)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.sendPayload(DataStoreHubEventStreamHandler.kt:200)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.getHubListener$lambda-0(DataStoreHubEventStreamHandler.kt:78)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler.$r8$lambda$hFBWgPzsdNPuhSYi4oGLjITrVpg(Unknown Source:0)
E/amplify:flutter:datastore( 4998): 	at com.amazonaws.amplify.amplify_datastore.DataStoreHubEventStreamHandler$$ExternalSyntheticLambda0.onEvent(Unknown Source:2)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin.lambda$publish$0(AWSHubPlugin.java:60)
E/amplify:flutter:datastore( 4998): 	at com.amplifyframework.hub.AWSHubPlugin$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/amplify:flutter:datastore( 4998): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/amplify:flutter:datastore( 4998): 	at java.lang.Thread.run(Thread.java:1012)
I/amplify:aws-datastore( 4998): Successfully sync'd down model state from cloud.
I/flutter ( 4998): AwsAmplifyUserApi - syncDataStore - event modelSynced
I/flutter ( 4998): AwsAmplifyUserApi - syncDataStore - event subscriptionDataProcessed
I/amplify:aws-datastore( 4998): Successfully sync'd down model state from cloud.
I/amplify:aws-datastore( 4998): Starting processing subscription data buffer.
I/amplify:aws-datastore( 4998): Started the orchestrator in API sync mode.
I/flutter ( 4998): AwsAmplifyUserApi - syncDataStore - event modelSynced
I/amplify:aws-datastore( 4998): Started processing the mutation outbox. Pending mutations will be published to the cloud.
I/flutter ( 4998): AwsAmplifyUserApi - syncDataStore - event syncQueriesReady
I/flutter ( 4998): AwsAmplifyUserApi - syncDataStore - event ready
```

**Comment by wojciechzahradnikdeviniti** [comment]
Any updates?

**Comment by Jordan-Nelson** [comment]
Hello @wojciechzahradnikdeviniti - Apologies for the delayed response.

The stack trace is pointing toward a block of code that should only execute for models with a list of custom types. For example:

```graphql

# Foo is a model type with an attribute that is a list of custom types.
type Foo @model {
  id: ID!
  bars: [Bar]
}

# Bar is a customer type. That is, it is not a model.
type Bar {
  id: ID!
}
```

I don't see this in the subset of the schema you have provided. Is it possible that another model in your schema has a relation like this? Are you able to provide the full schema?

Also, do you see this on every sync attempt? If not, are there any patterns as to when this occurs?

**Comment by Jordan-Nelson** [comment]
@wojciechzahradnikdeviniti - If you are still facing this issue can you please provide the info requested above?

**Comment by Jordan-Nelson** [comment]
Closing this out since we have not heard back.
