### ISSUE TITLE
AMPLIFY_SIGNUP_FAILED following Build a Flutter Application tutorial at await Amplify.Auth.signUp method

### ISSUE THREAD

**Issue by djsjr** [aws-amplify/amplify-flutter#371]
**Describe the bug**
Following the [official tutorial](https://aws.amazon.com/getting-started/hands-on/build-flutter-app-amplify/module-three/), the Amplify.Auth.signUp method won't sign up new users. I've initialized amplify, and installed the default auth and pushed it to the backend etc etc. The error caught is AMPLIFY_SIGNUP_FAILED. (First time using GitHub, Flutter, and AWS, so excuse me if this is the wrong way to describe or voice my issue. I'm happy to provide more info if needed.)

```
void signUpWithCredentials(SignUpCredentials credentials) async {
    try {
      Map<String, dynamic> userAttributes = {'email': credentials.email};
      final result = await Amplify.Auth.signUp(
        username: credentials.username,
        password: credentials.password,
        options: CognitoSignUpOptions(userAttributes: userAttributes),
      );
      if (result.isSignUpComplete) {
        loginWithCredentials(credentials);
      } else {
        this._credentials = credentials;
        final state = AuthState(authFlowStatus: AuthFlowStatus.verification);
        authStateController.add(state);
      }
    } on AuthError catch (authError) {
      print('Failed to sign up - ${authError.cause}');
    }
  }
```

When I remove the try block, the exception I get is this: 

`[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Instance of 'AuthError'
#0      AmplifyAuthCognitoMethodChannel._throwError (package:amplify_auth_cognito/method_channel_auth_cognito.dart:350:5)
#1      AmplifyAuthCognitoMethodChannel.signUp (package:amplify_auth_cognito/method_channel_auth_cognito.dart:40:7)
<asynchronous suspension>
#2      AmplifyAuthCognito.signUp (package:amplify_auth_cognito/amplify_auth_cognito.dart:48:33)
#3      AuthCategory.signUp (package:amplify_flutter/categories/amplify_auth_category.dart:32:22)
#4      AuthService.signUpWithCredentials (package:aws_tutorial/auth_service.dart:61:41)
#5      _SignUpPageState._signUp (package:aws_tutorial/signup_page.dart:83:33)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#9      TapGestureRe<…>`

**Comment by djsjr** [comment]
Password was too short. Found out by checking the settings in the backend UI. Suggest adding in the tutorial that the default min length is 8. (Firestore min length is 6.)
