### ISSUE TITLE
Amplify.Notifications.Push.launchNotification returns null

### ISSUE THREAD

**Issue by szymondobrzanski** [aws-amplify/amplify-flutter#3710]
### Description

Hello, 
_Amplify.Notifications.Push.launchNotification_ returns _null_ each time I sent push notification to terminated app. Both foreground and background notifications are delivered and read properly. I tested this behavior on both Android and iOS devices (in release mode for iOS). App is killed (by swipe - not from editor), I sent push notification, it is delivered to phone, after clicking on it app is opened but _launchNotification_ returns _null_. Here is log example from Android device in release mode:
```
W/FlutterJNI(29654): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(29654): FlutterJNI.init called more than once
I/flutter (29654): 🚀 launchNotificationFromTerminated: null
```
I checked and _launchNotification_ is not consumed anywhere before.

I attach code of my configuration and notifications service:

**Configuration:**

```
Future<void> main() async {
  await configureApp();
  runMain();
}

void runMain() {
  runApp(MyApp());
}

Future<void> configureApp() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  const environment =
      String.fromEnvironment('ENVIRONMENT_F', defaultValue: Environment.prod);
  if (kDebugMode) {
    await firebaseCrashlyticsInstance.setCrashlyticsCollectionEnabled(false);
  }
  FlutterError.onError = (errorDetails) {
    firebaseCrashlyticsInstance.recordFlutterFatalError(errorDetails);
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    firebaseCrashlyticsInstance.recordError(error, stack, fatal: true);
    return true;
  };
  await configureInjection(environment);
  try {
    if (Amplify.isConfigured) {
      safePrint('Amplify is already configured. Skipping configuration.');
    } else {
      final auth = AmplifyAuthCognito();
      final dataStorePlugin =
          AmplifyDataStore(modelProvider: ModelProvider.instance);
      final api = AmplifyAPI(modelProvider: ModelProvider.instance);
      final pushPlugin = AmplifyPushNotificationsPinpoint();
      PushNotificationsService.initalize(getIt<INotificationsRepository>());
      pushPlugin.onNotificationReceivedInBackground(
          PushNotificationsService.backgroundNotificationReceivedHandler);
      await Amplify.addPlugins([dataStorePlugin, api, auth, pushPlugin]);
      await Amplify.configure(amplifyconfig);
      PushNotificationsService.launchNotificationFromTerminated();
PushNotificationsService.startListeningToForeground();
          PushNotificationsService.onNotificationOpened();
    }
  } catch (e) {
    safePrint('An error occurred while configuring Amplify: $e');
    reportError(
        exception: 'Aws Amplify framework could not be initialised',
        reason: 'An error occurred while configuring Amplify: $e');
  }
}
```

**Service:**

```
@injectable
@pragma('vm:entry-point')
class PushNotificationsService {
  static late final PushNotificationsService _self;
  static late final INotificationsRepository _notificationsRepository;
  static late final StreamSubscription<PushNotificationMessage>
      _foregroundStream;
  static late final StreamSubscription<PushNotificationMessage>
      _notificationsOpenedStream;
  static late final StreamSubscription<String> _tokenStream;

  PushNotificationsService._internal(
      INotificationsRepository notificationsRepository) {
    _notificationsRepository = notificationsRepository;
  }

  @factoryMethod
  static PushNotificationsService initalize(
      INotificationsRepository notificationsRepository) {
    _self = PushNotificationsService._internal(notificationsRepository);
    return _self;
  }

  static Future<bool> requestPermission() async {
    final status = await Amplify.Notifications.Push.getPermissionStatus();
    if (status == PushNotificationPermissionStatus.granted) {
      return true;
    }
    if (status == PushNotificationPermissionStatus.shouldRequest ||
        status == PushNotificationPermissionStatus.shouldExplainThenRequest) {
      final status = await Amplify.Notifications.Push.requestPermissions();

      await _notificationsRepository.saveNotifications(status);
      return status;
    }
    return false;
  }

  static void startListeningToForeground() {
    _foregroundStream = Amplify
        .Notifications.Push.onNotificationReceivedInForeground
        .listen(_foregroundNotificationReceivedHandler);
  }

  static void onNotificationOpened() {
    _notificationsOpenedStream = Amplify.Notifications.Push.onNotificationOpened
        .listen(_notificationOpenedHandler);
  }

  ///Used to get device id in order to test notifications
  static void onTokenReceived() {
    _tokenStream = Amplify.Notifications.Push.onTokenReceived
        .listen(_tokenReceivedHandler);
  }

  static void launchNotificationFromTerminated() {
    final notification = Amplify.Notifications.Push.launchNotification;
    print('🚀 launchNotificationFromTerminated: $notification');
    if (notification != null) {
       //do sth
    }
  }

  static void _foregroundNotificationReceivedHandler(
      PushNotificationMessage notification) {
    print('🚀 foregroundNotificationReceivedHandler: $notification');
    if (notification.title != null && notification.body != null) {
      //display local notification
    }
  }

  static Future<void> backgroundNotificationReceivedHandler(
      PushNotificationMessage notification) async {
    print('🚀 backgroundNotificationReceivedHandler: $notification');

    ///onNotificationOpened won't work on iOS because of flutter_local_notifications config
    ///https://github.com/aws-amplify/amplify-flutter/issues/3273 -> that's why navigation is done here
    if (Platform.isIOS) {
        //do sth
    }
  }

  static void _notificationOpenedHandler(PushNotificationMessage notification) {
    ///Works only on Android as per comment above
    print('🚀 _notificationOpenedHandler: $notification');
  }


  static void cancelStreams() {
    _foregroundStream.cancel();
    _notificationsOpenedStream.cancel();
    _tokenStream.cancel();
  }
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.0

### Amplify Flutter Version

1.4.0

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment]
Hi @szymondobrzanski

For iOS, if you enabled the background mode for your app, when a PN arrives on the phone after the app is killed, it will launch the app in the background. In this case, the message will be emitted via `onNotificationReceivedInBackground`. And then, when you click on the PN to open the app, as the app has already launched in the background, the message will be emitted via `onNotificationOpened`. If the background mode is not enabled, when you click the PN to launch the app, the message should be accessible via `Amplify.Notifications.Push.launchNotification`.

For android, while you are seeing `Amplify.Notifications.Push.launchNotification` returns `null`, do you receive any message event from other channels (`onNotificationReceivedInBackground` etc.)?

**Comment by szymondobrzanski** [comment]
Hi @HuiSF, nope the only log I'm getting is from `Amplify.Notifications.Push.launchNotification` as stated above, other channels don't invoke any notifications.

**Comment by szymondobrzanski** [comment]
@HuiSF  any update from your side? Did you try to reproduce it?

**Comment by szymondobrzanski** [comment]
Hey @HuiSF  @dnys1 any update?

**Comment by cwomack** [comment]
@szymondobrzanski, apologies on the delayed response.  Can you share details of the android environment that you're using?  Is it an emulator or a real, physical device? There was a **_similar_** issue (#3143) that we couldn't reproduce, and has since been closed tied to Android behavior .  

On the iOS side, I believe it's expected behavior if the you have enabled background mode.  We're still investigating this, so any further context/answers would be helpful! Thank you.

**Comment by szymondobrzanski** [comment]
Hey @cwomack , thanks for response. I was using Android physical device with API Level 26. Why returning null after opening app from terminated state in iOS device would be expected behavior? Enabling background modes for iOS is one of configuration steps in Amplify documentation and there is none information that `getLaunchNotification` will return null for iOS by default.

**Comment by chrispypatt** [comment]
@cwomack I am experiencing the same behavior on iOS. I have tried with both with background notification mode on and  off based on your [suggestion above](https://github.com/aws-amplify/amplify-flutter/issues/3710#issuecomment-1712330209). I have my notification code register with `onNotificationOpened` and check `Amplify.Notifications.Push.launchNotification` for notifications after the app has initialized with no luck.

**Comment by chrispypatt** [comment]
Please disregard my comment above. I identified a scenario on launch where my app will register for notification receiving before I am able to handle the notification in my UI. There was a race condition in my code that was only occurring on iOS.

**Comment by rest950** [comment]
Same issue on iOS, launchNotification and onNotificationOpened are both not trigged.

**Comment by bitsplash-andy** [comment]
@rest950 Do you have firebase messaging as part of the project?

If you are using firebase_messaging in any way in the project, iOS will stop behaving as expected, the two libraries are currently incompatible.

see [#4237](https://github.com/aws-amplify/amplify-flutter/issues/4237)

**Comment by bitsplash-andy** [comment]
Just to add to this, I am also experiencing this issue, but only on Android. I receive tokens, foreground and background notifications as expected but am unable to get access to the notification that launched the app. iOS works fine providing the firebase_messaging library isn't used in conjunction with Amplify. Frustratingly, I didn't experience this issue using Firebase, so we've swapped one problem for another.

**Comment by rest950** [comment]
@bitsplash-andy 

My project no longer utilizes Firebase Messaging; it only relies on other Firebase services. However, on iOS in the terminated state, I am unable to trigger `launchNotification` or `onNotificationOpened`.

Regarding Android's ability to obtain `launchNotification`, in my tests, I found that it can only be trigged in a release build; it is not trigged in a debug build. Please give it a try and see if you encounter the same issue.

**Comment by HuiSF** [comment]
Hi @rest950 

>However, on iOS in the terminated state, I am unable to trigger launchNotification

Have you enabled the background mode for you iOS app?

If you have enabled background mode for your iOS app, when a push notification arrives on the device and your app is in the terminated state - the notification wakes your app up in the background. In this case, the notification will be sent to the callback of `onNotificationReceivedInBackground` - so there won't be a `launchNotification`.

>I am unable to trigger onNotificationOpened.

Is this happening when you tap on a notification in the notification center to open the app?

**Comment by bitsplash-andy** [comment]
I've noticed in logcat when the app launches from a terminated state the following exception is thrown.

I've tried to initialise Firebase followed by amplify in the first two lines of the main method and onNotificationReceivedInBackground handler, but the issue persists, wondering if this could be related.

`Error registering plugin amplify_push_notifications, com.amazonaws.amplify.amplify_push_notifications.AmplifyPushNotificationsPlugin
                                                                                                    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.app. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at s2.e.n(Unknown Source:56)
                                                                                                    	at com.google.firebase.messaging.FirebaseMessaging.l(Unknown Source:3)
                                                                                                    	at com.amazonaws.amplify.amplify_push_notifications.PushNotificationUtilsKt.refreshToken(Unknown Source:0)
                                                                                                    	at com.amazonaws.amplify.amplify_push_notifications.AmplifyPushNotificationsPlugin.onAttachedToEngine(Unknown Source:89)
                                                                                                    	at io.flutter.embedding.engine.c.e(Unknown Source:110)
                                                                                                    	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:68)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at i4.a.a(Unknown Source:21)
                                                                                                    	at io.flutter.embedding.engine.a.<init>(Unknown Source:256)
                                                                                                    	at io.flutter.embedding.engine.a.<init>(Unknown Source:10)
                                                                                                    	at io.flutter.embedding.engine.a.<init>(Unknown Source:8)
                                                                                                    	at io.flutter.embedding.engine.a.<init>(Unknown Source:11)
                                                                                                    	at io.flutter.embedding.engine.a.<init>(Unknown Source:6)
                                                                                                    	at io.flutter.embedding.engine.a.<init>(Unknown Source:1)
                                                                                                    	at com.amazonaws.amplify.amplify_push_notifications.PushNotificationBackgroundService.createAndRunBackgroundEngine(Unknown Source:28)
                                                                                                    	at com.amazonaws.amplify.amplify_push_notifications.PushNotificationBackgroundService.startPushNotificationService$lambda$2$lambda$1$lambda$0(Unknown Source:16)
                                                                                                    	at com.amazonaws.amplify.amplify_push_notifications.PushNotificationBackgroundService.a(Unknown Source:0)
                                                                                                    	at com.amazonaws.amplify.amplify_push_notifications.c.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

and 

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PushNotificationException {
                                                                                                      "message": "Error occurred awaiting for device token.",
                                                                                                      "recoverySuggestion": "Review the underlying exception.",
                                                                                                      "underlyingException": "PlatformException(java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.app. Make sure to call FirebaseApp.initializeApp(Context) first., IllegalStateException, Cause: null, Stacktrace: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.app. Make sure to call FirebaseApp.initializeApp(Context) first.\n\tat s2.e.n(Unknown Source:56)\n\tat com.google.firebase.messaging.FirebaseMessaging.l(Unknown Source:3)\n\tat com.amazonaws.amplify.amplify_push_notifications.PushNotificationUtilsKt.refreshToken(Unknown Source:0)\n\tat com.amazonaws.amplify.amplify_push_notifications.AmplifyPushNotificationsPlugin.requestInitialToken(Unknown Source:0)\n\tat com.amazonaws.amplify.amplify_push_notifications.PushNotificationsHostApiBindings$PushNotificationsHostApi.lambda$setup$0(Unknown Source:5)\n\tat com.amazonaws.amplify.amplify_push_notifications.PushNotificationsHostApiBindings$PushNotificationsHostApi.c(Unknown Source:0)\n\tat com.amazonaws.amplify.amplify_push_notifications.k.a(Unknown Source:2)\n\tat io.flutter.plugin.common.a$b.a(Unknown Source:17)\n\tat y3.c.l(Unknown Source:18)\n\tat y3.c.m(Unknown Source:40)\n\tat y3.c.i(Unknown Source:0)\n\tat y3.b.run(Unknown Source:12)\n\tat android.os.Handler.handleCallback(Handler.java:958)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:230)\n\tat android.os.Looper.loop(Looper.java:319)\n\tat android.app.ActivityThread.main(ActivityThread.java:8893)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)\n, null)"
                                                                                                    }
                                                                                                    #0      AmplifyPushNotifications._registerDeviceWhenConfigure (package:amplify_push_notifications/src/amplify_push_notifications_impl.dart:352)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      AmplifyPushNotifications.configure (package:amplify_push_notifications/src/amplify_push_notifications_impl.dart:231)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      Future.wait.<anonymous closure> (dart:async/future.dart:523)
                                                                                                    <asynchronous suspension>
                                                                                                    #3      AmplifyClass._configurePlugins (package:amplify_core/src/amplify_class.dart:171)
                                                                                                    <asynchronous suspension>
                                                                                                    #4      AmplifyClass.configure (package:amplify_core/src/amplify_class.dart:128)
                                                                                                    <asynchronous suspension>
                                                                                                    #5      amplifyBackgroundProcessing (package:amplify_push_notifications_pinpoint/src/push_notifications_background_processing.dart:49)
                                                                                                    <asynchronous suspension>`

**Comment by chrispypatt** [comment]
I am still seeing this on iOS and we do not use any Firebase dependencies.

**Comment by bitsplash-andy** [comment]
In our case this didn’t work on android because we were using google-services 4.4.1 in our Androids build.gradle.

Downgrading google-services to 4.3.16 resolved the issue. Not sure if the library is incompatible with 4.4.x versions at this time?

**Comment by rest950** [comment]
> 
> > I am unable to trigger onNotificationOpened.
> 
> Is this happening when you tap on a notification in the notification center or the PN banner to open the app?

@HuiSF 

After my attempts, I found that tap from notification center successfully triggered onNotificationOpened. 
However, tap from the PN Banner did not trigger onNotificationOpened.
Is this the expected behavior?

**Comment by Jordan-Nelson** [comment]
Apologies for the delay. Thank you for the additional info. We will attempt to reproduce this with the additional info provided.

**Comment by dummiss** [comment]
> > > I am unable to trigger onNotificationOpened.
> > 
> > 
> > Is this happening when you tap on a notification in the notification center or the PN banner to open the app?
> 
> @HuiSF
> 
> After my attempts, I found that tap from notification center successfully triggered onNotificationOpened. However, tap from the PN Banner did not trigger onNotificationOpened. Is this the expected behavior?

I’ve encountered the same issue. It tends to occur when a notification is received after the app has not been running for some time. In these cases, tapping the notification center or PN banner often fails to trigger onNotificationOpened. However, after using the app for a while, the onNotificationOpened event is triggered normally. I have already upgraded the plugin to the latest version, 2.4.1.

**Comment by tyllark** [comment]
I have not been able to reproduce the issue on my side yet. Could you please retry in this simplified app and provide your logs after removing your tokens. [lib.zip](https://github.com/user-attachments/files/16997222/lib.zip)

The OS can be a bit finicky when it comes to launching an app from a terminated or background state but If you handle both [launch notifications and onNotificationOpened](https://docs.amplify.aws/gen1/flutter/build-a-backend/push-notifications/interact-with-notifications/#respond-to-a-notification-being-opened) you should be covered for both cases.
