### ISSUE TITLE
Pod install and repo update failures when using amplify_push_notifications_pinpoint

### ISSUE THREAD

**Issue by Laebrye** [aws-amplify/amplify-flutter#3887]
### Description

My project uses a few of the amplify flutter packages in order to work. I wanted to add push notifications so I added the library. Below is are the packages and versions that I'm using:

```
  amplify_api: ^1.4.0
  amplify_auth_cognito: ^1.4.0
  amplify_flutter: ^1.4.0
  amplify_push_notifications_pinpoint: ^1.4.0
  amplify_storage_s3: ^1.4.0
```

When I build the project for iOS without `amplify_push_notifications_pinpoint`, it builds and runs fine. But when I include it I get the following failures:

**Pod install:**
```
Analyzing dependencies
[!] Unable to find a target named `RunnerTests` in project `Runner.xcodeproj`, did find `Runner` and <package name>ShareExtension
```

**Pod repo update:**
```
### Error


LoadError - dlopen(/Users/Dave/.rvm/gems/ruby-2.5.0/gems/ffi-1.15.0/lib/ffi_c.bundle, 0x0009): tried: '/Users/Dave/.rvm/gems/ruby-2.5.0/gems/ffi-1.15.0/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/Dave/.rvm/gems/ruby-2.5.0/gems/ffi-1.15.0/lib/ffi_c.bundle' (no such file), '/Users/Dave/.rvm/gems/ruby-2.5.0/gems/ffi-1.15.0/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')) - /Users/Dave/.rvm/gems/ruby-2.5.0/gems/ffi-1.15.0/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/ffi-1.15.0/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/ffi-1.15.0/lib/ffi.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/ethon-0.14.0/lib/ethon.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:142:in `each'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:140:in `open'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:140:in `update'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/lib/cocoapods/command/repo/update.rb:23:in `run'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Users/Dave/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/Users/Dave/.rvm/gems/ruby-2.5.0/bin/pod:23:in `load'
/Users/Dave/.rvm/gems/ruby-2.5.0/bin/pod:23:in `<main>'
```

Things I've tried to fix this: numerous combinations of llvm, ffi, arch -x86_64 commands. Reinstalling ruby. Reinstalling homebrew.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a project that includes 
  amplify_api: ^1.4.0
  amplify_auth_cognito: ^1.4.0
  amplify_flutter: ^1.4.0
  amplify_push_notifications_pinpoint: ^1.4.0
  amplify_storage_s3: ^1.4.0
2. run or build for iOS

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.40.0

### Deployment Method

Amplify CLI

**Comment by Laebrye** [comment]
I think I may have resolved it. Completely overlooked the `rvm` in my error log and only then remembered that I had setup rvm about 2 years ago and not updated the ruby version there since.

Have managed to run pod repo update and am testing pod install now. If it works I'll close this down and apologise profusely for my ignorance

**Comment by Laebrye** [comment]
Pod install completed successfully. Installing the app now as well but I'm confident the issue has been resolved. For anyone debugging a similar problem, make sure your version of ruby is updated, whether you're using `rvm` or otherwise.
