### ISSUE TITLE
fetchAuthSession doesn't work with CognitoSessionOptions(getAWSCredentials: true)

### ISSUE THREAD

**Issue by NepipenkoIgor** [aws-amplify/amplify-flutter#390]
**Describe the bug**
Hi all. Thanks. it is amazing implementation for flutter. But i have strange result. Everything looks like in documentation and everything works. For example `Amplify.Auth.signIn` or `Amplify.Auth.signOut`.  But when i try to call `Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));` for example after signIn i have an error . Without `getAWSCredentials: true` everything works . But i need a token to continue work. Maybe somebody could help or maybe we have another way to retry token ?

**Screenshots**
Error text
```
flutter: Amplify signIn Error => UnknownException(message: Unexpected error occurred with message: An unknown error occurred, recoverySuggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/igornepipenko/work/mueller/sentryx/ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79, underlyingException: Obtaining an identity id in another thread failed or didn't complete within 5 seconds.)
flutter: [INFO] LoggingMiddleware: {Action: null, State: Instance of 'AppState', ts: 2021-02-15 14:20:13.727453}
```

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Comment by haverchuck** [comment]
@NepipenkoIgor What is your Cognito configuration?

**Comment by NepipenkoIgor** [comment]
@haverchuck 

const String amplifyconfig = ''' {
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
      "plugins": {
          "awsCognitoAuthPlugin": {
              "IdentityManager": {
                  "Default": {}
              },
              "CredentialsProvider": {
                  "CognitoIdentity": {
                      "Default": {
                          "PoolId": null,
                          "Region": myRegion
                      }
                  }
              },
              "CognitoUserPool": {
                  "Default": {
                      "PoolId": myPoolId,
                      "AppClientId": myClientId,
                      "Region": myRegion
                  }
              },
              "Auth": {
                  "Default": {
                      "authenticationFlowType": "USER_SRP_AUTH"
                  }
              }
          }
      }
  }
}''';

**Comment by haverchuck** [comment]
Ok, thank you. Is the error you are seeing identical across both iOS and Android?

**Comment by Amplifiyer** [comment]
Looks similar to https://github.com/aws-amplify/amplify-ios/issues/877 

Couple questions:
* Did you observe this in android as well? If yes, please add the logs to this issue.
* Based on the above issue I referenced, are you able to call `fetchAuthSession` successfully after few seconds (such as 5?). And are you awaiting the results of the signin before calling `fetchAuthSession`

**Comment by NepipenkoIgor** [comment]
@haverchuck @Amplifiyer   yes i have error on Android too 

logs
```
D/AWSMobileClient(15533): _federatedSignIn: Putting provider and token in store
D/AWSMobileClient(15533): Inspecting user state details
D/AWSMobileClient(15533): hasFederatedToken: false provider: cognito-idp.us-east-1.amazonaws.com/us-east-1_qKBuDoKlM
W/AWSMobileClient(15533): Failed to federate tokens during sign-in
W/AWSMobileClient(15533): java.lang.RuntimeException: Error in federating the token.
W/AWSMobileClient(15533): 	at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1733)
W/AWSMobileClient(15533): 	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
W/AWSMobileClient(15533): 	at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1661)
W/AWSMobileClient(15533): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1193)
W/AWSMobileClient(15533): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1020)
W/AWSMobileClient(15533): 	at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1178)
W/AWSMobileClient(15533): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(15533): 	at java.lang.Thread.run(Thread.java:919)
W/AWSMobileClient(15533): Caused by: com.amazonaws.AmazonServiceException: 1 validation error detected: Value 'null' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+ (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ValidationException; Request ID: de76869c-5db0-4d90-a636-eaddbf4afb46)
W/AWSMobileClient(15533): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient(15533): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient(15533): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(15533): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient(15533): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient(15533): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient(15533): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3910)
W/AWSMobileClient(15533): 	at com.amazonaws.auth.CognitoCredentialsProvider.retryRefresh(CognitoCredentialsProvider.java:723)
W/AWSMobileClient(15533): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:695)
W/AWSMobileClient(15533): 	at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:640)
W/AWSMobileClient(15533): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:511)
W/AWSMobileClient(15533): 	at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1764)
W/AWSMobileClient(15533): 	at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1720)
W/AWSMobileClient(15533): 	... 7 more
2
W/InternalCallback(15533): Library attempted to call user callback twice, expected only once
2
D/AWSMobileClient(15533): Inspecting user state details
D/AWSMobileClient(15533): waitForSignIn: userState:SIGNED_OUT
E/amplify:flutter:auth_cognito(15533): SignedOutException
E/amplify:flutter:auth_cognito(15533): SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
E/amplify:flutter:auth_cognito(15533): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareCognitoSessionFailure(AuthCognito.kt:480)
E/amplify:flutter:auth_cognito(15533): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:333)
E/amplify:flutter:auth_cognito(15533): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:69)
E/amplify:flutter:auth_cognito(15533): 	at com.amplifyframework.auth.cognito.MobileClientSessionAdapter$1.onError(MobileClientSessionAdapter.java:74)
E/amplify:flutter:auth_cognito(15533): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:47)
E/amplify:flutter:auth_cognito(15533): 	at java.lang.Thread.run(Thread.java:919)

```

i will process flow in epic . Redux widdleware 

```
Stream<dynamic> logInEpic(Stream<dynamic> actions, EpicStore<dynamic> store) {
  return actions
      .whereType<LogInAction>()
      .asyncMap<dynamic>((LogInAction action) {
    return Amplify.Auth.signIn(
      username: action.username.trim(),
      password: action.password.trim(),
    ).then<AuthSession>((SignInResult res) {
      return Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));
    }).then<PushReplacementAction>((AuthSession res) {
      print(res);
      return PushReplacementAction(SentryxSitesScreen());
    }).catchError((dynamic err) {
      if (err is UserNotFoundException) {
        appStore.store.dispatch(ShowToastAction(
            ToastModel(ToastType.error, 'Incorrect username or password.')));
        return;
      }
      print(
          'Amplify signIn Error => $err ====> ${err is UserNotFoundException}');
    });
  });
}
```

And it is very strange but if i remove `CognitoSessionOptions(getAWSCredentials: true)`
everything works but with this output

```
I/flutter (15912): [INFO] LoggingMiddleware: {Action: Instance of 'LogInAction', State: Instance of 'AppState', ts: 2021-02-15 21:32:35.850623}
D/AWSMobileClient(15912): _federatedSignIn: Putting provider and token in store
D/AWSMobileClient(15912): Inspecting user state details
D/AWSMobileClient(15912): hasFederatedToken: false provider: cognito-idp.us-east-1.amazonaws.com/us-east-1_qKBuDoKlM
W/AWSMobileClient(15912): Failed to federate tokens during sign-in
W/AWSMobileClient(15912): java.lang.RuntimeException: Error in federating the token.
W/AWSMobileClient(15912): 	at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1733)
W/AWSMobileClient(15912): 	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
W/AWSMobileClient(15912): 	at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1661)
W/AWSMobileClient(15912): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1193)
W/AWSMobileClient(15912): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1020)
W/AWSMobileClient(15912): 	at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1178)
W/AWSMobileClient(15912): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(15912): 	at java.lang.Thread.run(Thread.java:919)
W/AWSMobileClient(15912): Caused by: com.amazonaws.AmazonServiceException: 1 validation error detected: Value 'null' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+ (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ValidationException; Request ID: 877e05b8-c5d4-4113-b001-d7d5f8e19229)
W/AWSMobileClient(15912): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient(15912): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient(15912): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(15912): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient(15912): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient(15912): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient(15912): 	at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1764)
W/AWSMobileClient(15912): 	at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1720)
W/AWSMobileClient(15912): 	... 7 more
2
W/InternalCallback(15912): Library attempted to call user callback twice, expected only once
2
D/AWSMobileClient(15912): Inspecting user state details
D/AWSMobileClient(15912): waitForSignIn: userState:SIGNED_OUT

```

**Comment by haverchuck** [comment]
@NepipenkoIgor Did you set up your Cognito resources with the Amplify CLI?

**Comment by NepipenkoIgor** [comment]
@NepipenkoIgor  Yes. I discussed with my team and i removed it from configuration . Because we used only userPoll .  Now everything works. Problem was with configuration .  Also i didn't setup and i needed to use existing one . We have a web application that used Cognito

**Comment by VisakhRaman** [comment]
@NepipenkoIgor Hello there. Can you help me with how to configure with an existing userpool that is already used for the web application? I'm getting a similar error as well and the official documentation only has information about creating a new userpool and connecting to it. 
Any inputs will be helpful, thanks!
