### ISSUE TITLE
UserCancelledException on signInWithWebUI(Android only, works fine on IOS)

### ISSUE THREAD

**Issue by omchiii** [aws-amplify/amplify-flutter#396]
**Describe the bug**
After following all the instructions in the official documentation, sign in with web ui sends me back to my application(using my uri) and just throws an error : UserCancelledException{message=The user cancelled the sign-in attempt, so it did not complete. I'm using Amplify Auth 1.0.1. I tried using the latest code from the repo but this didn't solve the issue as well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an empty Flutter & configure Amplify with the Auth plugin.
2. Add the intent filter in AndroidManifest.xml
2. call Amplify.Auth.signInWithWebUI, wrap it in a try catch block, the catch block should print out the following "The user cancelled the sign-in attempt, so it did not complete."

**Expected behaviour**
Expected to successfully log in.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Smartphone (please complete the following information):**
 - Device: Tried on multiple android devices

**Additional context**
https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android#add-response-handler
In Amplify Android docs there is a first step to add a response handler in the activity, whereas in the official Amplify IOS docs I could not see this step. Maybe this is the reason?

**Comment by haverchuck** [comment]
@omchiii The differeing implementation could be at play here; however, we implement the response hander in our amplify-flutter native code.  There could be some sort of bug in our implementation, but I am unable to repro this issue currently.  In your AndroidManifest file, are you using just a domain for the app or an additional signin path?  I noticed that some (not all) of our docs show a full path, but it should be simply the app domain.  The user should be navigated back to the widget where they launched the sign in activity.

**Comment by haverchuck** [comment]
@omchiii Can you specify one or two of the devices/emulators you've been testing on?

**Comment by omchiii** [comment]
> @omchiii Can you please provide a bit more informaiton?
> 
> 1. Please specify one or two of the devices/emulators you've been testing on?
> 2. Please post the code you've been using to launch the activity.
> 3. Please describe what exactly you see when you launch the activity.  Do you get the error immediately? Does the Hosted UI site actually launch and then hang?
> 
> PS We implement the response handler for Android in our own platform code.

1. Samsung Galaxy S7 Edge,  Xiaomi mi 8 lite & a Huawei device Y2
2. Amplify.Auth.signInWithWebUI(
                provider: AuthProvider.google);
3. I see the select Google Account screen, I select the account it takes me back to the app and gives me this error: `I/flutter (20740): The user cancelled the sign-in attempt, so it did not complete.`

**Comment by haverchuck** [comment]
@omchiii I haven't been able to reproduce this - does your project have a GitHub repo you're willing/able to share? Also, is there any additional console output you could post - particularly anything prefixed with `AWSMobileClient`?

**Comment by omchiii** [comment]
I cannot share the source code because of the NDA. But I will send you the complete logs today.

**Comment by omchiii** [comment]
`W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
I/chatty  ( 2527): uid=10342(com.example.ev_butler) GoogleApiHandle identical 28 lines
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
I/flutter ( 2527): true
I/flutter ( 2527): null
I/ViewRootImpl@8972440[MainActivity]( 2527): ViewPostIme pointer 0
I/ViewRootImpl@8972440[MainActivity]( 2527): ViewPostIme pointer 1
I/flutter ( 2527): asd
I/flutter ( 2527): aaa
I/flutter ( 2527): 0
I/flutter ( 2527): lenggth
I/flutter ( 2527): true
I/flutter ( 2527): null
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
I/chatty  ( 2527): uid=10342(com.example.ev_butler) GoogleApiHandle identical 1 line
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
I/ViewRootImpl@8972440[MainActivity]( 2527): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 2527): prepareNavigationBarInfo() DecorView@dbfeed4[MainActivity]
D/InputMethodManager( 2527): getNavigationBarColor() -855310
I/ViewRootImpl@8972440[MainActivity]( 2527): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager( 2527): prepareNavigationBarInfo() DecorView@dbfeed4[MainActivity]
D/InputMethodManager( 2527): getNavigationBarColor() -855310
I/ViewRootImpl@8972440[MainActivity]( 2527): ViewPostIme pointer 0
I/ViewRootImpl@8972440[MainActivity]( 2527): ViewPostIme pointer 1
W/ActivityThread( 2527): handleWindowVisibility: no activity for token android.os.BinderProxy@8ecdfd0
D/PhoneWindow( 2527): forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4274 com.android.internal.policy.DecorView.updateColorViews:1547 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3252 android.view.Window.setFlags:1153 com.android.internal.policy.PhoneWindow.generateLayout:2474 
I/MultiWindowDecorSupport( 2527): [INFO] isPopOver = false
I/MultiWindowDecorSupport( 2527): updateCaptionType >> DecorView@3ecdbc9[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport( 2527): setCaptionType = 0, DecorView = DecorView@3ecdbc9[]
I/ViewRootImpl@828fc[CustomTabsManagerActivity]( 2527): setView = com.android.internal.policy.DecorView@3ecdbc9 TM=true MM=false
I/ViewRootImpl@8972440[MainActivity]( 2527): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 2527): prepareNavigationBarInfo() DecorView@dbfeed4[MainActivity]
D/InputMethodManager( 2527): getNavigationBarColor() -855310
I/ViewRootImpl@828fc[CustomTabsManagerActivity]( 2527): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=14 res=0x7 s={true 523890753536} ch=true
D/OpenGLRenderer( 2527): createReliableSurface : 0x7a51924d00(0x79fa528000)
I/mali_winsys( 2527): new_window_surface() [1080x2340] return: 0x3000
D/OpenGLRenderer( 2527): eglCreateWindowSurface : 0x79fa397f80
D/OpenGLRenderer( 2527): makeCurrent EglSurface : 0x7a51910200 -> 0x79fa397f80
I/ViewRootImpl@828fc[CustomTabsManagerActivity]( 2527): MSG_RESIZED: frame=(0,0,1080,2340) ci=(0,83,0,126) vi=(0,83,0,126) or=1
D/InputTransport( 2527): Input channel destroyed: 'ClientS', fd=104
D/OpenGLRenderer( 2527): makeCurrent EglSurface : 0x79fa397f80 -> 0x0
D/OpenGLRenderer( 2527): destroyEglSurface : 0x79fa397f80
I/mali_egl( 2527): eglDestroySurface() in
I/mali_winsys( 2527): delete_surface() [1080x2340] return
I/mali_egl( 2527): eglDestroySurface() out
E/OpenGLRenderer( 2527): ReliableSurface: perform returned an error
W/libEGL  ( 2527): EGLNativeWindowType 0x7a51924d10 disconnect failed
D/OpenGLRenderer( 2527): ~ReliableSurface : 0x7a51924d00
I/ViewRootImpl@828fc[CustomTabsManagerActivity]( 2527): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)8 dur=16 res=0x5 s={false 0} ch=true
I/ViewRootImpl@828fc[CustomTabsManagerActivity]( 2527): stopped(true) old=false
I/SurfaceView( 2527): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{62874be V.E...... ........ 0,0-1080,2214} of ViewRootImpl@8972440[MainActivity]
I/SurfaceView( 2527): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{62874be V.E...... ........ 0,0-1080,2214}
I/mali_egl( 2527): eglDestroySurface() in
I/mali_winsys( 2527): delete_surface() [1080x2214] return
I/mali_egl( 2527): eglDestroySurface() out
W/libEGL  ( 2527): EGLNativeWindowType 0x79fa996010 disconnect failed
I/SurfaceView( 2527): remove() io.flutter.embedding.android.FlutterSurfaceView{62874be V.E...... ........ 0,0-1080,2214} Surface(name=SurfaceView - com.example.ev_butler/com.example.ev_butler.MainActivity@62874be@7)/@0x7547dda
D/OpenGLRenderer( 2527): destroyEglSurface : 0x7a5d3d3000
I/mali_egl( 2527): eglDestroySurface() in
I/mali_winsys( 2527): delete_surface() [1080x2340] return
I/mali_egl( 2527): eglDestroySurface() out
E/OpenGLRenderer( 2527): ReliableSurface: perform returned an error
W/libEGL  ( 2527): EGLNativeWindowType 0x79cdf6bbd0 disconnect failed
D/OpenGLRenderer( 2527): ~ReliableSurface : 0x79cdf6bbc0
I/ViewRootImpl@8972440[MainActivity]( 2527): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)8 dur=10 res=0x5 s={false 0} ch=true
D/OpenGLRenderer( 2527): destroyEglSurface : 0x7a51910200
I/mali_egl( 2527): eglDestroySurface() in
I/mali_winsys( 2527): delete_surface() [1080x2214] return
I/mali_egl( 2527): eglDestroySurface() out
E/OpenGLRenderer( 2527): ReliableSurface: perform returned an error
W/libEGL  ( 2527): EGLNativeWindowType 0x7aea217f50 disconnect failed
D/OpenGLRenderer( 2527): ~ReliableSurface : 0x7aea217f40
I/ViewRootImpl@8972440[MainActivity]( 2527): stopped(true) old=false
I/SurfaceView( 2527): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{62874be V.E...... ........ 0,0-1080,2214} of ViewRootImpl@8972440[MainActivity]
I/mali_egl( 2527): eglDestroySurface() in
I/mali_winsys( 2527): delete_surface() [1080x2214] return
I/mali_egl( 2527): eglDestroySurface() out
W/libEGL  ( 2527): EGLNativeWindowType 0x79fa970010 disconnect failed
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
I/ViewRootImpl@828fc[CustomTabsManagerActivity]( 2527): dispatchDetachedFromWindow
D/InputTransport( 2527): Input channel destroyed: '28a8938', fd=163
I/SurfaceView( 2527): onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{62874be V.E...... ........ 0,0-1080,2214} of ViewRootImpl@8972440[MainActivity]
I/ViewRootImpl@8972440[MainActivity]( 2527): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)4 dur=6 res=0x1 s={false 0} ch=false
I/ViewRootImpl@8972440[MainActivity]( 2527): stopped(false) old=true
I/SurfaceView( 2527): windowStopped(false) false io.flutter.embedding.android.FlutterSurfaceView{62874be V.E...... ........ 0,0-1080,2214} of ViewRootImpl@8972440[MainActivity]
I/mali_winsys( 2527): new_window_surface() [1080x2214] return: 0x3000
I/ViewRootImpl@8972440[MainActivity]( 2527): stopped(false) old=false
E/amplify:flutter:auth_cognito( 2527): UserCancelledException
E/amplify:flutter:auth_cognito( 2527): UserCancelledException{message=The user cancelled the sign-in attempt, so it did not complete., cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled, recoverySuggestion=To recover: catch this error, and show the sign-in screen again.}
E/amplify:flutter:auth_cognito( 2527):  at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$22.onError(AWSCognitoAuthPlugin.java:1078)
E/amplify:flutter:auth_cognito( 2527):  at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito( 2527):  at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito( 2527):  at com.amazonaws.mobile.client.AWSMobileClient$25$1$3.run(AWSMobileClient.java:3319)
E/amplify:flutter:auth_cognito( 2527):  at java.lang.Thread.run(Thread.java:919)
E/amplify:flutter:auth_cognito( 2527): Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled
E/amplify:flutter:auth_cognito( 2527):  at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.handleCustomTabsCancelled(AuthClient.java:316)
E/amplify:flutter:auth_cognito( 2527):  at com.amazonaws.mobileconnectors.cognitoauth.Auth.handleFlowCancelled(Auth.java:760)
E/amplify:flutter:auth_cognito( 2527):  at com.amazonaws.mobile.client.AWSMobileClient.handleAuthResponse(AWSMobileClient.java:2978)
E/amplify:flutter:auth_cognito( 2527):  at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.handleWebUISignInResponse(AWSCognitoAuthPlugin.java:486)
E/amplify:flutter:auth_cognito( 2527):  at com.amplifyframework.auth.AuthCategory.handleWebUISignInResponse(AuthCategory.java:154)
E/amplify:flutter:auth_cognito( 2527):  at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.onActivityResult(AuthCognito.kt:120)
E/amplify:flutter:auth_cognito( 2527):  at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/amplify:flutter:auth_cognito( 2527):  at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/amplify:flutter:auth_cognito( 2527):  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
E/amplify:flutter:auth_cognito( 2527):  at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
E/amplify:flutter:auth_cognito( 2527):  at android.app.Activity.dispatchActivityResult(Activity.java:8300)
E/amplify:flutter:auth_cognito( 2527):  at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
E/amplify:flutter:auth_cognito( 2527):  at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
E/amplify:flutter:auth_cognito( 2527):  at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/amplify:flutter:auth_cognito( 2527):  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/amplify:flutter:auth_cognito( 2527):  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/amplify:flutter:auth_cognito( 2527):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
E/amplify:flutter:auth_cognito( 2527):  at android.os.Handler.dispatchMessage(Handler.java:107)
E/amplify:flutter:auth_cognito( 2527):  at android.os.Looper.loop(Looper.java:237)
E/amplify:flutter:auth_cognito( 2527):  at android.app.ActivityThread.main(ActivityThread.java:8167)
E/amplify:flutter:auth_cognito( 2527):  at java.lang.reflect.Method.invoke(Native Method)
E/amplify:flutter:auth_cognito( 2527):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/amplify:flutter:auth_cognito( 2527):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/SurfaceView( 2527): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{62874be V.E...... ........ 0,0-1080,2214} of ViewRootImpl@8972440[MainActivity]
I/ViewRootImpl@8972440[MainActivity]( 2527): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=18 res=0x7 s={true 523887054848} ch=true
D/OpenGLRenderer( 2527): createReliableSurface : 0x79bc9a5dc0(0x79fa1a1000)
D/OpenGLRenderer( 2527): makeCurrent EglSurface : 0x0 -> 0x0
I/SurfaceView( 2527): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{62874be V.E...... ........ 0,0-1080,2214}
I/mali_winsys( 2527): new_window_surface() [1080x2214] return: 0x3000
I/mali_winsys( 2527): new_window_surface() [1080x2340] return: 0x3000
D/OpenGLRenderer( 2527): eglCreateWindowSurface : 0x7aea1aef80
I/SurfaceView( 2527): surfaceChanged (1080,2214) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{62874be V.E...... ........ 0,0-1080,2214}
D/OpenGLRenderer( 2527): makeCurrent EglSurface : 0x0 -> 0x7aea1aef80
I/OpenGLRenderer( 2527): doUpdatePositionAsync is called and callVoidMethod
I/ViewRootImpl@8972440[MainActivity]( 2527): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager( 2527): prepareNavigationBarInfo() DecorView@dbfeed4[MainActivity]
D/InputMethodManager( 2527): getNavigationBarColor() -855310
D/InputMethodManager( 2527): prepareNavigationBarInfo() DecorView@dbfeed4[MainActivity]
D/InputMethodManager( 2527): getNavigationBarColor() -855310
V/InputMethodManager( 2527): Starting input: tba=com.example.ev_butler ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 2527): startInputInner - Id : 0
I/InputMethodManager( 2527): startInputInner - mService.startInputOrWindowGainedFocus
I/flutter ( 2527): err
I/flutter ( 2527): UserCancelledException(message: The user cancelled the sign-in attempt, so it did not complete., recoverySuggestion: To recover: catch this error, and show the sign-in screen again., underlyingException: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled)
W/ample.ev_butle( 2527): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)`



These are the logs after invoking Amplify.Auth.signInWithWebUI(
provider: AuthProvider.google);

**Comment by omchiii** [comment]
@haverchuck

**Comment by omchiii** [comment]
@haverchuck I am sorry for creating this issue. The reason why all this was not working was because I added the intent filter to the .MainActivity activity instead of creating a new activity with the "com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity" name. This was clearly stated in the documentation, but I somehow missed it.
