### ISSUE TITLE
[Datastore] API sync failure on configure 

### ISSUE THREAD

**Issue by hyobbb** [aws-amplify/amplify-flutter#421]
Hi. I am using datastore api and I get this message on initializing app.

```
E/amplify:aws-datastore(21773): Failure encountered while attempting to start API sync.
E/amplify:aws-datastore(21773): GraphQLResponseException{message=Subscription error for Video: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_deleted' in type 'Video' is undefined @ 'onUpdateVideo/_deleted'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Video' is undefined @ 'onUpdateVideo/_lastChangedAt'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_version' in type 'Video' is undefined @ 'onUpdateVideo/_version'', locations='null', path='null', extensions='null'}], errors=[GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_deleted' in type 'Video' is undefined @ 'onUpdateVideo/_deleted'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Video' is undefined @ 'onUpdateVideo/_lastChangedAt'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_version' in type 'Video' is undefined @ 'onUpdateVideo/_version'', locations='null', path='null', extensions='null'}], recoverySuggestion=See attached list of GraphQLResponse.Error objects.}
E/amplify:aws-datastore(21773): 	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$2(AppSyncClient.java:291)
E/amplify:aws-datastore(21773): 	at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$FIbUjC1l68HcabhkQcx9zYkvUI8.accept(Unknown Source:8)
E/amplify:aws-datastore(21773): 	at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchNextMessage(SubscriptionEndpoint.java:392)
E/amplify:aws-datastore(21773): 	at com.amplifyframework.api.aws.SubscriptionEndpoint.notifySubscriptionData(SubscriptionEndpoint.java:226)
E/amplify:aws-datastore(21773): 	at com.amplifyframework.api.aws.SubscriptionEndpoint.access$700(SubscriptionEndpoint.java:60)
E/amplify:aws-datastore(21773): 	at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.processJsonMessage(SubscriptionEndpoint.java:570)
E/amplify:aws-datastore(21773): 	at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onMessage(SubscriptionEndpoint.java:476)
E/amplify:aws-datastore(21773): 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
E/amplify:aws-datastore(21773): 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
E/amplify:aws-datastore(21773): 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
E/amplify:aws-datastore(21773): 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
E/amplify:aws-datastore(21773): 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
E/amplify:aws-datastore(21773): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/amplify:aws-datastore(21773): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:aws-datastore(21773): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:aws-datastore(21773): 	at java.lang.Thread.run(Thread.java:923)
W/amplify:aws-datastore(21773): API sync failed - transitioning to LOCAL_ONLY.

```

My graphQL schema is like below:

```
enum TagStatus {
  ACTIVE
  INACTIVE
}

type Tag @model {
  id: ID!
  text: String!
  rating: Int!
  status: TagStatus!
  # New field with @connection
  videos: [Video] @connection(keyName: "byTag", fields: ["id"])
}

# New model
type Video @model
@key(name: "byTag", fields: ["tagID", "contentUrl"]) {
  id: ID!
  tagID: ID!
  tag: Tag! @connection(fields: ["tagID"])
  contentUrl: String!
  thumbUrl : String!
}
```

I executed `amplify codegen models` and compiled successfully.
Also, in android-studio with JS GraphQL plug in I have error message on my schema.graphql file that is saying "Unknown directive "model"". It doesn't generate any errors for compiling anyway.

**Comment by hyobbb** [comment]
`amplify update api` and selecting `Enable DataStore for entire API` solved the problem

**Comment by b-cancel** [comment]
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help others that might land on this page
https://github.com/aws-amplify/amplify-flutter/issues/822
