### ISSUE TITLE
Get Error AMPLIFY_FETCH_SESSION_FAILED calling `Amplify.Auth.getCurrentUser()` just after logging in.

### ISSUE THREAD

**Issue by fayeed** [aws-amplify/amplify-flutter#451]
**Describe the bug**
After I log in which works fine, I immediately use `Amplify.Auth.getCurrentUser()` to get the user which throws `AMPLIFY_FETCH_SESSION_FAILED ` error.

**To Reproduce**
1. Login in using `Amplify.Auth.signIn`
2. And then use `Amplify.Auth.getCurrentUser` to get the current user, you should see the error.

**Expected behavior**
To get `Amplify.Auth.getCurrentUser` to return the current login user.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.867], locale en-IN)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (8 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\fayee\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.    
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.54.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
```
</details>

**Additional context**
I found something in the logs which might be helpful, it seems that CognitoUserSession is not valid as specified in the first line:
```
W/CognitoUserSession(10888): CognitoUserSession is not valid because idToken is null.
D/AWSMobileClient(10888): Sending password.
D/AWSMobileClient(10888): _federatedSignIn: Putting provider and token in store
W/AWSMobileClient(10888): Failed to federate tokens during sign-in
W/AWSMobileClient(10888): java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.
W/AWSMobileClient(10888): 	at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1708)
W/AWSMobileClient(10888): 	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
W/AWSMobileClient(10888): 	at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1661)
W/AWSMobileClient(10888): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1193)
W/AWSMobileClient(10888): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6.onSuccess(CognitoUser.java:1099)
W/AWSMobileClient(10888): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$27.run(CognitoUser.java:3098)
W/AWSMobileClient(10888): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$24.run(CognitoUser.java:2965)
W/AWSMobileClient(10888): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:147)
W/AWSMobileClient(10888): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1228)
W/AWSMobileClient(10888): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
W/AWSMobileClient(10888): 	at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1178)
W/AWSMobileClient(10888): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(10888): 	at java.lang.Thread.run(Thread.java:923)
D/AWSMobileClient(10888): Inspecting user state details
D/AWSMobileClient(10888): hasFederatedToken: false provider: cognito-idp.us-east-2.amazonaws.com/us-east-2_Cd8BaNB2i
E/amplify:flutter:auth_cognito(10888): AMPLIFY_FETCH_SESSION_FAILED
E/amplify:flutter:auth_cognito(10888): AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
E/amplify:flutter:auth_cognito(10888): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareCognitoSessionFailure(AuthCognito.kt:513)
E/amplify:flutter:auth_cognito(10888): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:368)
E/amplify:flutter:auth_cognito(10888): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:76)
E/amplify:flutter:auth_cognito(10888): 	at com.amplifyframework.auth.cognito.MobileClientSessionAdapter$2.onError(MobileClientSessionAdapter.java:191)
E/amplify:flutter:auth_cognito(10888): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:47)
E/amplify:flutter:auth_cognito(10888): 	at java.lang.Thread.run(Thread.java:923)
I/flutter (10888): [ERROR] [_startMicrotaskLoop]: Error while accessing id token: Instance of 'AuthError'
I/flutter (10888): Exception: Access token is null
```

**Comment by haverchuck** [comment]
@fayeed Could you please post your amplifyconfiguration.dart (it's ok to redact the actual values, we're mainly concerned about the keys)?

**Comment by fayeed** [comment]
Hey, so we had a preconfigured Cognito pool and that we are using and we didn't use the amplify-cli to generate it, also I was able to test signup & login which works fine, its just that after authenticating calling the `Amplify.Auth.getCurrentUser` gives the error `AMPLIFY_FETCH_SESSION_FAILED `.

Here's the structure:
```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                  "Default": {
                    "PoolId": "us-east-x_xxxxxxxx",
                    "AppClientId": "xxxxxxxxxxxxxxxxxx",
                    "AppClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "Region": "us-east-x"
                  }
                },
              "Auth": {
                  "Default": {
                      "authenticationFlowType": "USER_SRP_AUTH"
                  }
              }
            }
        }
    }
}
```

**Comment by haverchuck** [comment]
@fayeed Which version of amplify-flutter are you using?  Based on the error message, it looks to me like it's from our developer preview phase?

**Comment by fayeed** [comment]
@haverchuck sorry for the late response, yes we were using this constraint `<1.0.0` and it didn't update the deps so had to manually set it `0.1.1` which seems to work, but also encountered another error and this seems different "Unable to verify secret hash for client"  let me know if I need to create another issue for this, Thanks!

**Comment by haverchuck** [comment]
@fayeed This could *possibly* be an issue with your Cognito User Pool App Client. Can you share how you've configured it?

**Comment by offlineprogrammer** [comment]
Hey @fayeed

I am closing this issue for now as we didn't hear from you 
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo
