### ISSUE TITLE
Amplify Fails to Configure - WorkerBeeExceptionImpl

### ISSUE THREAD

**Issue by CarlosEspinozaMaruri** [aws-amplify/amplify-flutter#4883]
### Description

When attempting to configure Amplify using `Amplify.configure()`, the following exception is being thrown:

Exception:
```
WorkerBeeExceptionImpl {
  error=FormatException: Unexpected character (at character 9887)
...64,211,194,37,198,206,3,147,170,33]}2-e5be-4be8-8542-1fdf465a27b0.expira...
                                       ^
,
  stackTrace=#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:913)
#2      _parseJson (dart:convert-patch/convert_patch.dart:35)
#3      JsonDecoder.convert (dart:convert/json.dart:610)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      FileKeyValueStore.readAll (package:amplify_secure_storage_dart/src/utils/file_key_value_store.dart:96)
<asynchronous suspension>
#6      FileKeyValueStore.readKey (package:amplify_secure_storage_dart/src/utils/file_key_value_store.dart:70)
<asynchronous suspension>
#7      AmplifySecureStorageWindows.read (package:amplify_secure_storage_dart/src/platforms/amplify_secure_storage_windows.dart:45)
<asynchronous suspension>
#8      SecureStorageWorker.run (package:amplify_secure_storage_dart/src/worker/secure_storage_worker.dart:56)
<asynchronous suspension>
#9      _run (package:amplify_secure_storage_dart/src/worker/secure_storage_worker.worker.vm.dart:14)
<asynchronous suspension>

```

Stacktrace:
```
dart:convert-patch/convert_patch.dart 1383                                                 _ChunkedJsonParser.fail
dart:convert-patch/convert_patch.dart 913                                                  _ChunkedJsonParser.parse
dart:convert-patch/convert_patch.dart 35                                                   _parseJson
dart:convert/json.dart 610                                                                 JsonDecoder.convert
dart:convert/json.dart 216                                                                 JsonCodec.decode
package:amplify_secure_storage_dart/src/utils/file_key_value_store.dart 96                 FileKeyValueStore.readAll
package:amplify_secure_storage_dart/src/utils/file_key_value_store.dart 70                 FileKeyValueStore.readKey
package:amplify_secure_storage_dart/src/platforms/amplify_secure_storage_windows.dart 45   AmplifySecureStorageWindows.read
package:amplify_secure_storage_dart/src/worker/secure_storage_worker.dart 56               SecureStorageWorker.run
package:amplify_secure_storage_dart/src/worker/secure_storage_worker.worker.vm.dart 14     _run
package:amplify_core/src/state_machine/event.dart 43                                       new EventCompleter
package:amplify_core/src/state_machine/state_machine.dart 179                              StateMachineManager.dispatch
package:amplify_core/src/state_machine/state_machine.dart 32                               Dispatcher.dispatchAndComplete
package:amplify_core/src/state_machine/state_machine.dart 190                              StateMachineManager.dispatchAndComplete
package:amplify_auth_cognito_dart/src/state/cognito_state_machine.dart 73                  CognitoAuthStateMachine.loadCredentials
package:amplify_auth_cognito_dart/src/state/machines/configuration_state_machine.dart 108  ConfigurationStateMachine.onConfigure
package:amplify_auth_cognito_dart/src/state/machines/configuration_state_machine.dart 50   ConfigurationStateMachine.resolve
package:amplify_core/src/state_machine/state_machine.dart 255                              StateMachine._listenForEvents.<fn>.<fn>
dart:async/future.dart 427                                                                 new Future.delayed.<fn>
dart:async/zone.dart 1391                                                                  _rootRun
dart:async/zone.dart 1301                                                                  _CustomZone.run
dart:async/zone.dart 1209                                                                  _CustomZone.runGuarded
dart:async/zone.dart 1249                                                                  _CustomZone.bindCallbackGuarded.<fn>
dart:async/zone.dart 1399                                                                  _rootRun
dart:async/zone.dart 1301                                                                  _CustomZone.run
dart:async/zone.dart 1233                                                                  _CustomZone.bindCallback.<fn>
dart:async-patch/timer_patch.dart 18                                                       Timer._createTimer.<fn>
dart:isolate-patch/timer_impl.dart 398                                                     _Timer._runTimers
dart:isolate-patch/timer_impl.dart 429                                                     _Timer._handleMessage
dart:isolate-patch/isolate_patch.dart 189                                                  _RawReceivePort._handleMessage
===== asynchronous gap ===========================
package:amplify_core/src/state_machine/event.dart 43                                       new EventCompleter
package:amplify_core/src/state_machine/state_machine.dart 150                              StateMachineManager.accept
package:amplify_core/src/state_machine/state_machine.dart 162                              StateMachineManager.acceptAndComplete
package:amplify_auth_cognito_dart/src/auth_plugin_impl.dart 236                            AmplifyAuthCognitoDart.configure
package:amplify_auth_cognito/src/auth_plugin_impl.dart 84                                  AmplifyAuthCognito.configure
dart:async/future.dart 525                                                                 Future.wait.<fn>
package:amplify_core/src/amplify_class_impl.dart 77                                        AmplifyClassImpl.configurePlatform
package:amplify_core/src/amplify_class.dart 113                                            AmplifyClass.configure
package:app/di/locator.dart 119                                                      configureAmplify
package:app/di/locator.dart 34                                                       initializeDI
package:app/main.dart 18                                                             main.<fn>
```

This seems to only happen on Windows devices. I have successfully replicated the error in production on 4 devices belonging to different clients. Despite efforts, I have been unable to reproduce the error in our development environment. However, it has come to my attention that this error occurs in installations approximately 2 or more days old. Furthermore, it is noteworthy that reinstalling the application from the Windows Store resolves the issue, suggesting potential file corruption.

Notes: 
- The application retrieves Amplify configuration settings through the `amplifyconfiguration.dart` file, utilizing methods such as `String.fromEnvironment('PINPOINT_ANALYTICS_APP_ID')` to access private keys in environment variables.
- Devices are in the correct time zone.
- In Android and iOS works as expected.
- There are Windows devices (v. 10 and 11) in which the error does not occur.

### Categories

- [X] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

`Amplify.configure()` on Windows

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [X] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.1.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @CarlosEspinozaMaruri - It does seem like the file could be getting corrupted. Without reproduction steps I am unsure what is causing that. The data is stored in a file on the file system in the local app data directory (ex: `C:\Documents and
  /// Settings\username\Local Settings\Application Data`). Is is possible that this file is being modified by some other process? The file is encrypted so you won't be able to read it, but you could see when it was last modified.

I think we could catch this exception and clear out the file. This would allow the app to configure, but it would be as if the user is using the app for the first time after install (credentials would be lost so they would need to re-authenticate).

**Comment by CarlosEspinozaMaruri** [comment]
> Without reproduction steps I am unsure what is causing that

I can't give you more steps to reproduce the error than what's mentioned in the bug report, and perhaps add that it works correctly in the first installation, but then stops working after approximately 2 days. Another thing I didn't mention is that reinstalling the application only solves the problem for another 2 to 3 days, and then it happens again.

>  Is is possible that this file is being modified by some other process?

I am not sure.
I'll try to ask the client to notify me when it happens again to check if the file was modified, and once I have that information, I'll get back to you.

**Comment by NikaHsn** [comment]
thanks @CarlosEspinozaMaruri. Please let us know once you have more information to help us investigate/reproduce this issue.

**Comment by CarlosEspinozaMaruri** [comment]
Hello @Jordan-Nelson @NikaHsn, the error occurred again today and I found in the application files that the file "archivo" was modified. I don't know how it could have happened, but I am sure it was not done by the user.

<img width="872" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/59948587/6fafbe60-40e2-4fc2-b0fc-2c2ccd1c9c29">
<img width="872" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/59948587/5ea9d897-2db4-4bcc-8fe1-2fd7460c399b">

**Comment by Jordan-Nelson** [comment]
@CarlosEspinozaMaruri can you provide me with the contents of the file with the data redacted? The contents of the file should be a JSON object. The keys may have app identifying info (such as a user pool ID). You can redact this as well. The values will contain encrypted blobs of data. The encrypted blobs will be arrays of integers. Please remove that entirely (you can replace with an empty array or `[1, 2, 3]` as a placeholder).

I want to look at the structure of the file. Based on the error it seems that the contents of the file is not valid JSON. I am hoping the structure of the file may give me an idea as to what is modifying it.

**Comment by Jordan-Nelson** [comment]
@CarlosEspinozaMaruri - If you are still experiencing this issue could you provide the info requested above? Thanks

**Comment by CarlosEspinozaMaruri** [comment]
Hello @Jordan-Nelson I am waiting for the client response in order to know if is still happening. As soon as I have a response I will let you know. Thanks.

**Comment by Jordan-Nelson** [comment]
Thanks @CarlosEspinozaMaruri

**Comment by Jordan-Nelson** [comment]
@CarlosEspinozaMaruri - Just wanted to follow up to see if you were able to get the info from the client. Thanks

**Comment by CarlosEspinozaMaruri** [comment]
@Jordan-Nelson It didn't happen again, I'm not sure if it was resolved. However, I am already in the process of migrating to version 2.0 of amplify.

**Comment by CarlosEspinozaMaruri** [comment]
Hello @Jordan-Nelson

Sorry for the delay, I was migrating the Amplify version to 2.1.0 and finally managed to get the file you requested. I'm attaching the json below along with the error.

```
WorkerBeeExceptionImpl { error=FormatException: Unexpected character (at character 866)
...56,193,24]]}21,66],"<region>:<uid>..
```


```json
{
"region:uid.accessKeyId":[56,193,24]}21,66],
"region:uid.sessionToken":[90,143,237],
"region:uid.expiration":[173,25,117]}5,101]
}


```

**Comment by CarlosEspinozaMaruri** [comment]
@Jordan-Nelson Any update on this?

**Comment by pieterbergmans** [comment]
We are getting the exact same issue.  Here is our log output:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: WorkerBeeExceptionImpl {
  error=FormatException: Unexpected character (at character 1)
,
  stackTrace=#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1247:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:912:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      FileKeyValueStore.readAll (package:amplify_secure_storage_dart/src/utils/file_key_value_store.dart:96:35)
<asynchronous suspension>
#7      FileKeyValueStore.readKey (package:amplify_secure_storage_dart/src/utils/file_key_value_store.dart:70:18)
<asynchronous suspension>
#8      AmplifySecureStorageWindows.read (package:amplify_secure_storage_dart/src/platforms/amplify_secure_storage_windows.dart:45:21)
<asynchronous suspension>
#9      SecureStorageWorker.run (package:amplify_secure_storage_dart/sr
```

**Comment by CarlosEspinozaMaruri** [comment]
@pieterbergmans I just opened a new issue with more information, you can follow it [here](https://github.com/aws-amplify/amplify-flutter/issues/5190)
