### ISSUE TITLE
Capability to retry the api request as well as handle the cancellation 

### ISSUE THREAD

**Issue by sagnik-sanyal** [aws-amplify/amplify-flutter#5049]
### Description

I have an important requirement to be able to retry the http request based upon some condition for specified number of attempts for which i am using the extension below , also note that .retry is a custom extension on future to retry the future. So here if the exception is HttpStatusException with status code 500 or some other code i need to retry the request.

```
extension RestOperationTimeout on RestOperation {
  RestOperation applyRetries({int maxAttempts = 3}) {
    return this
      ..response.retry(
        maxAttempts: maxAttempts,
        retryIf: (Exception e) => // some condition here
        onRetry: // do something like log errors on retry,
      );
  }
}
```

But i guess that as the package internally relies on CancellableCompleter, if the first request fails and perform retry i get an error below on the second request ->

```
E/flutter (20132): #0      AmplifyAuthorizationRestClient.transformResponse (package:amplify_api_dart/src/util/amplify_authorization_rest_client.dart:65:7)
E/flutter (20132): <asynchronous suspension>
E/flutter (20132): #1      CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425:16)
E/flutter (20132): <asynchronous suspension>
```

Do i need to create a new RestOperation object everytime a new request is sent or am i missing something ? 
This function is going to be used all across the application so that the retry gets cancelled if request was cancelled and also perform retry if the request fails and the operation is still active.

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

N/A

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Flutter Version

3.22.1

### Amplify Flutter Version

2.1.0

### Deployment Method

Amplify CLI

**Comment by tyllark** [comment]
Hello @sagnik-sanyal thank you for submitting this issue. We will look into this and get back to you!

**Comment by sagnik-sanyal** [comment]
Hi @tyllark any update on this issue ?

**Comment by Jordan-Nelson** [comment]
Hello @sagnik-sanyal - Currently you would need to create a new operation.

Alternatively, you may be able to provide your own http client to the API plugin and use an http client that retries the request. I would need to look into this a bit more to see if this would work.

Let me know if you have other questions.

**Comment by sagnik-sanyal** [comment]
@Jordan-Nelson i would like to have an example of the second implementation that you mentioned, for retrying and cancelling the request

**Comment by Jordan-Nelson** [comment]
@sagnik-sanyal - [Here is an example](https://docs.amplify.aws/gen1/flutter/build-a-backend/graphqlapi/advanced-workflows/#adding-headers-to-outgoing-requests) of using a custom http client. This is a fairly simple example of adding a header to each request. I would need to confirm if this can be used to retry requests.

**Comment by sagnik-sanyal** [comment]
Thanks @Jordan-Nelson for providing valuable insights, yeah I will try this to achieve retrying the requests, but can this be cancelled or how to access whether it has been cancelled from the custom client ( let's say the user left the screen while the request was retrying so there's no need to perform the request ) ?

**Comment by sagnik-sanyal** [comment]
Thanks for helping us although we would love to have a utility or a resuable extension to retry the api calls @Jordan-Nelson

**Comment by Jordan-Nelson** [comment]
@sagnik-sanyal I am going to label this as a feature request for the ability to retry the request.
