### ISSUE TITLE
[Feature Request] DataStore query filtering by null value

### ISSUE THREAD

**Issue by Lorenzohidalgo** [aws-amplify/amplify-flutter#511]
When retrieving data by querying via DataStore there is no way to filter the query by null values, Needing to filter the retrieving list afterwards or adding aditional fields for every nullable field.

It would be greate to have a predicate like `.isNull` to filter by null values or be able to filter by `.eq(null)`.

**Example:**
I have a Members Model to link two models while adding some additional information. Every member is assigned to a Space via the SpaceID, but not all members are assigned to a Team via TeamID (null in this case). I would like to get all members assigned to specific space that have no teams assigned (teamID == null)
![image](https://user-images.githubusercontent.com/22448611/114605412-592dc300-9c9a-11eb-9075-a273b24e6f70.png)

Current thrown exception when trying to filter by `.eq(null`:
```
PlatformException (PlatformException(DataStoreException, Translating platform exception failed. Please take a look at
https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
match your scenario, and file an issue with the details of the bug if there isn't., {recoverySuggestion: See attached exception for details., underlyingException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference, message: Error in querying the model.}, null))
```

**Comment by offlineprogrammer** [comment]
Hi @Lorenzohidalgo 

I used `where: Todo.CATEGORYID.ne(null)` & `where: Todo.CATEGORYID.eq(null)` successfully using the schema below 

```dart
type Todo @model @auth(rules: [{allow: public}]) @key(name: "byUser", fields: ["userId"]) @key(name: "byCategory", fields: ["categoryId"])  {
  id: ID!
  name: String!
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
  isDone: Boolean
  userId: ID!
  categoryId: ID
  desc: String
}

type Users @model  @auth(rules: [{allow: public}]) {
  id: ID!
  username: String
  email: AWSEmail
  imageKey: String!
  imageUrl: String!
  isVerified: Boolean
  createdAt: AWSDateTime
  todos: [Todo] @connection(keyName: "byUser", fields: ["id"])

}

type Category @model  @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  
  todos: [Todo] @connection(keyName: "byCategory", fields: ["id"])

}

```

Can you please share a sample schema to reproduce the issue

Regards
Mo

**Comment by Lorenzohidalgo** [comment]
Hi @offlineprogrammer,

Just tried to query using .eq(null) with the following error log:
```
E/amplify:flutter:datastore(25583): Query operation failed.
E/amplify:flutter:datastore(25583): DataStoreException{message=Error in querying the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference, recoverySuggestion=See attached exception for details.}
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$5$SQLiteStorageAdapter(SQLiteStorageAdapter.java:437)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$YrR7B1Rj3JmC_omOKlzMTn0U5hM.run(Unknown Source:10)
E/amplify:flutter:datastore(25583): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/amplify:flutter:datastore(25583): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:flutter:datastore(25583): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:datastore(25583): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:datastore(25583): 	at java.lang.Thread.run(Thread.java:919)
E/amplify:flutter:datastore(25583): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.TypeConverter.getJavaFieldTypeFromValue(TypeConverter.java:83)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.adapter.SQLPredicate.addBinding(SQLPredicate.java:104)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.adapter.SQLPredicate.parsePredicateOperation(SQLPredicate.java:194)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.adapter.SQLPredicate.parsePredicate(SQLPredicate.java:120)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.adapter.SQLPredicate.parsePredicateGroup(SQLPredicate.java:222)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.adapter.SQLPredicate.parsePredicate(SQLPredicate.java:124)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.adapter.SQLPredicate.<init>(SQLPredicate.java:75)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteCommandFactory.queryFor(SQLiteCommandFactory.java:206)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.getQueryAllCursor(SQLiteStorageAdapter.java:909)
E/amplify:flutter:datastore(25583): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$5$SQLiteStorageAdapter(SQLiteStorageAdapter.java:393)
E/amplify:flutter:datastore(25583): 	... 6 more
```

I'm not sure if it has something to do with the used schema, but here it is:
```graphql
type Notifications @aws_iam @aws_cognito_user_pools {
  id: ID!
  pid: ID
  timestamp: AWSDateTime!
  spacePID: ID!
  senderPID: ID!
  recieverPID: ID!
  notificationType: NotificationTypeEnum!
  title: String
  body: String
  linkingPID: ID
  isRead: Boolean!
  _version: Int!
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

And the executed query was:
```dart
final _result = await Amplify.DataStore.query(
        Notifications.classType,
        where: Notifications.SPACEPID
            .eq(spacePID)
            .and(Notifications.RECIEVERPID.eq(userPID))
            .and(Notifications.LINKINGPID.eq(null)),
        sortBy: [Notifications.TIMESTAMP.descending()],
      );
```

Hope this helps.

**Comment by HuiSF** [comment]
This issue is reproducible in Android. Investigating.

**Comment by HuiSF** [comment]
It looks a bug in amplify-android. Created issue in amplify-android repository for further investigation.

**Comment by HuiSF** [comment]
The latest release of amplify-flutter contains the fix made to amplify-flutter. Now can query by `null` value in Android platform. Please feel free to follow up if you encountered any issues. Thanks!
