### ISSUE TITLE
Amplify.Auth.fetchAuthSession hangs?

### ISSUE THREAD

**Issue by mjvirt** [aws-amplify/amplify-flutter#521]
I ran into issue #491 on 0.11 and therefore upgraded to 0.12 I have a simple app that I'm testing on Android (this is Flutter/Dart). I use the Auth plugin (also 0.12). On initial app start up I notice this:

```
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54513/8hFeUZqM8Xc=/ws
I/flutter (20880): Amplify isConfigured: false
I/AmplifyFlutter(20880): Added StorageS3 plugin
I/flutter (20880): snapshot has data: false
I/amplify:flutter:auth_cognito(20880): Added Auth plugin
D/AWSMobileClient(20880): Using the SignInProviderConfig from `awsconfiguration.json`.
W/AWSMobileClient(20880): Sign in provider was not registered due to missing optional dependency. showSignIn() API may not work as expected.
W/AWSMobileClient(20880): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/mobile/auth/userpools/CognitoUserPoolsSignInProvider;
W/AWSMobileClient(20880): 	at com.amazonaws.mobile.client.AWSMobileClient.registerConfigSignInProviders(AWSMobileClient.java:3536)
W/AWSMobileClient(20880): 	at com.amazonaws.mobile.client.AWSMobileClient.access$100(AWSMobileClient.java:163)
W/AWSMobileClient(20880): 	at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:490)
W/AWSMobileClient(20880): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(20880): 	at java.lang.Thread.run(Thread.java:923)
W/AWSMobileClient(20880): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.mobile.auth.userpools.CognitoUserPoolsSignInProvider" on path: DexPathList[[zip file "/data/app/~~-30YxoltoQPUyyNSU9Kl9w==/com.virtuability.docleverapp-Lz0-IcwBwAHeJdDtSY4Nqw==/base.apk"],nativeLibraryDirectories=[/data/app/~~-30YxoltoQPUyyNSU9Kl9w==/com.virtuability.docleverapp-Lz0-IcwBwAHeJdDtSY4Nqw==/lib/x86, /data/app/~~-30YxoltoQPUyyNSU9Kl9w==/com.virtuability.docleverapp-Lz0-IcwBwAHeJdDtSY4Nqw==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
W/AWSMobileClient(20880): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
W/AWSMobileClient(20880): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/AWSMobileClient(20880): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/AWSMobileClient(20880): 	... 5 more
```

I let the app complete its initialisation. Part of that is running Amplify.Auth.fetchAuthSession() but it appears to never return. In fact this is what I see coming back:

```
I/flutter (20880): calling fetchAuthSession
D/AWSMobileClient(20880): Inspecting user state details
D/AWSMobileClient(20880): Inspecting user state details
D/AWSMobileClient(20880): waitForSignIn: userState:SIGNED_OUT
```

**To Reproduce**

The code that I use is a StateFul app and in the initState I call _configureAmplify(), which looks like this:

```
  void _configureAmplify() async {

    bool isConfigured = Amplify.isConfigured;

    print('Amplify isConfigured: $isConfigured');
    if (isConfigured)
      return;

    try {
      await Amplify.addPlugin(AmplifyStorageS3());
      await Amplify.addPlugin(AmplifyAuthCognito());
      await Amplify.configure(amplifyconfig);

      print('Successfully configured Amplify');
    } on AmplifyAlreadyConfiguredException {
      print('Amplify was already configured.');
    }

    print('calling fetchAuthSession');
    final session = await Amplify.Auth.fetchAuthSession();
    print('done fetchAuthSession');
```

I never see the "done fetchAuthSession" message.

**Expected behavior**

I would expect fetchAuthSession to return with a result.

**Platform**
[x] Android
[] iOS

```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.928], locale en-IE)    • Flutter version 2.0.4 at C:\Users\mjensen\app\flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\...\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at
    .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\...\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30)
      (emulator)
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.76 
```

**Smartphone (please complete the following information):**
 - Device: [Pixel_3a_API_30_x86 emulator]
 - OS: [Android]
 - Browser [N/A]
 - Version [30]

**Additional context**

**Comment by mjvirt** [comment]
Note that I can workaround the issue above by editing the `dependencies` section in `build.gradle` by adding `implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.22.+'`.

**Comment by haverchuck** [comment]
@mjvirt Thanks for the workaround - which version of `aws-android-sdk-auth-userpools` were you using previously?

**Comment by mjvirt** [comment]
@haverchuck I'm honestly not sure, it would have been whatever the 0.10 and after the 0.11 version of the dart/flutter library amplify_auth_cognito brought in.

**Comment by dgagnon** [comment]
Hi,

we are facing the same issue.  It appears that the android folder is not maintained by Amplify during version upgrades.  We also were not able to find any reference to this breaking change.

What is the recommended approach to keep the build environment updated with the amplify requirements ?

@mjvirt Would you please be able to share your corrected file?

Thank you,

**Comment by Jordan-Nelson** [comment]
Hi @mjvirt - I am unable to reproduce this issue. Can you please remove the work around, confirm you are still experiencing this issue, and then provide the output of running `./gradlew app:dependencies` from the android directory of your project?

**Comment by Jordan-Nelson** [comment]
Closing issue due to inactivity. If you are still experiencing this issue, please open a new issue with the output from `./gradlew app:dependencies` so that I can attempt to reproduce.

**Comment by dnys1** [comment]
@flgatormike What kind of network speeds are you testing with? Could this be a case of slow/bad network connection, potentially? We have seen similar issues in such cases, so that's why I'm curious.

**Comment by vgribok** [comment]
Using 0.6.10, I am having this issue on one of the three dev boxes I use with the identical codebase. I run into it on my work Windows laptop, but not on my home Windows desktop or Mac Mini M1. The issue happens on either home or corp network.

**Comment by Jordan-Nelson** [comment]
@vgribok - Sorry for the long delay in response. Do you see this on every single call to fetchAuthSession on that machine? Are there other calls that hang? Are you seeing anything in the logs that indicate an issue?

**Comment by Jordan-Nelson** [comment]
@vgribok - Thanks for the info. I am going to close this issue. If you experience this again please let use know.

**Comment by Andrew0000** [comment]
It still exists. https://github.com/aws-amplify/amplify-android/issues/2816 
Adding com.amazonaws:aws-android-sdk-auth-userpools from this thread doesn't help.

**Comment by Jordan-Nelson** [comment]
@Andrew0000 - If you are experiencing an issue can you please open a new GitHub issue and fill out the info in the template?

**Comment by Andrew0000** [comment]
My issue is solved, thanks.
