### ISSUE TITLE
Auth always giving "Incorrect Username or Password" error

### ISSUE THREAD

**Issue by FiercestT** [aws-amplify/amplify-flutter#549]
Recently started using Amplify and implemented Auth on 2 brand new projects. Experiencing the following issue on both.

Issue:
Auth.signIn(...) will always return the following with a newly created and verified account: 
```AuthException{message=Sign in failed, cause=com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 3257e760-7d0b-4e2b-bf1a-f742bf98221c), recoverySuggestion=See attached exception for more details.}```

AmplifyConfig client pool and client id's match those where the account is located in cognito. Email (not username) authentication was used. Everything but sign in works.

Device: 
Pixel 4 Emulator AVD (running Android 11).

Code: 
```dart
  //This is the problematic method
  Future<SignInResult> Login(String email, String password) async {
    Amplify.Auth.signOut(); //Same issue without this.
    return Amplify.Auth.signIn(username: email.trim(), password: password.trim());
  }

  Future<SignUpResult> SignUp(String email, String password) async {
    return Amplify.Auth.signUp(
      username: email,
      password: password,
      options: CognitoSignUpOptions(userAttributes: {'email': email}),
    );
  }
```

Log upon running the above method:
```
D/IdentityManager( 7940): Signing out...
W/CognitoUserSession( 7940): CognitoUserSession is not valid because idToken is null.
D/AWSMobileClient( 7940): Sending password.
D/AWSMobileClient( 7940): Inspecting user state details
(2) E/UserContextDataProvider( 7940): Exception in creating JSON from context data
E/amplify:flutter:auth_cognito( 7940): NotAuthorizedException
E/amplify:flutter:auth_cognito( 7940): AuthException{message=Sign in failed, cause=com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 3257e760-7d0b-4e2b-bf1a-f742bf98221c), recoverySuggestion=See attached exception for more details.}
E/amplify:flutter:auth_cognito( 7940): 	at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:106)
E/amplify:flutter:auth_cognito( 7940): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$5.onError(AWSCognitoAuthPlugin.java:375)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.onFailure(AWSMobileClient.java:1271)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6.onFailure(CognitoUser.java:1155)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$23.run(CognitoUser.java:2915)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$24.run(CognitoUser.java:2965)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:147)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1235)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1185)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito( 7940): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:auth_cognito( 7940): Caused by: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 3257e760-7d0b-4e2b-bf1a-f742bf98221c)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6334)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.respondToAuthChallenge(AmazonCognitoIdentityProviderClient.java:4966)
E/amplify:flutter:auth_cognito( 7940): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToChallenge(CognitoUser.java:2886)
E/amplify:flutter:auth_cognito( 7940): 	... 7 more
E/flutter ( 7940): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NotAuthorizedException(message: Sign in failed, recoverySuggestion: See attached exception for more details., underlyingException: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 3257e760-7d0b-4e2b-bf1a-f742bf98221c))
E/flutter ( 7940): #0      castAndThrowPlatformException
package:amplify_auth_cognito/amplify_auth_error_handling.dart:73
E/flutter ( 7940): #1      AmplifyAuthCognitoMethodChannel.signIn
package:amplify_auth_cognito/method_channel_auth_cognito.dart:118
E/flutter ( 7940): <asynchronous suspension>
E/flutter ( 7940): #2      AmplifyAuthCognito.signIn
package:amplify_auth_cognito/amplify_auth_cognito.dart:68
E/flutter ( 7940): <asynchronous suspension>
E/flutter ( 7940): #3      LoginPage.build.<anonymous closure>
package:regroup/…/Login/LoginPage.dart:17
E/flutter ( 7940): <asynchronous suspension>
E/flutter ( 7940):
```
Log from starting App:
```
I/amplify:flutter:auth_cognito( 7940): Added Auth plugin
D/AWSMobileClient( 7940): Using the SignInProviderConfig from `awsconfiguration.json`.
(2) D/AWSMobileClient( 7940): Inspecting user state details
I/TetheringManager( 7940): registerTetheringEventCallback:ca.package.app.app
D/AWSMobileClient( 7940): Inspecting user state details
D/AWSMobileClient( 7940): waitForSignIn: userState:SIGNED_OUT
W/AWSMobileClient( 7940): getCredentials: Failed to getCredentials from Cognito Identity
W/AWSMobileClient( 7940): com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 0d3ab327-cecf-41a0-8faa-758813cb24fb)
```
Might this have anything to do with the following line in the log? 
```
(2) E/UserContextDataProvider( 7940): Exception in creating JSON from context data
```

I only saw one other instance of this which was never actually solved (https://github.com/aws-amplify/amplify-android/issues/948).

**Comment by haverchuck** [comment]
@FiercestT did you create your Cognito instance with the Amplify CLI?

**Comment by FiercestT** [comment]
Yes, followed the Auth guide from the docs twice now. The user is in the cognito user pool and reports as email verified/confirmed.

**Comment by FiercestT** [comment]
Aha!

Issue Resolved

Turns out I need to pass the client metadata map as a SignIn option using the same keys that were employed for user signup. 

Unfortunately, I was mislead to think it was an issue with the User Pool as the error code said it was the username or password which was incorrect rather than the metadata which was missing from the SignIn method. 

Solution Code
```dart
  Future<SignInResult> Login(String email, String password) async {
    return Amplify.Auth.signIn(
        username: email,
        password: password,
        options: CognitoSignInOptions(clientMetadata: {'email': email}));
  }

  Future<SignUpResult> SignUp(String email, String password) async {
    return Amplify.Auth.signUp(
      username: email,
      password: password,
      options: CognitoSignUpOptions(userAttributes: {'email': email}),
    );
  }
```

**Comment by offlineprogrammer** [comment]
Closing as per the confirmation from @FiercestT above
