### ISSUE TITLE
Websocket listener received CONNECTION_ERROR

### ISSUE THREAD

**Issue by riyan-datalyca** [aws-amplify/amplify-flutter#584]
**Describe the bug**
Websocket listener received CONNECTION_ERROR event. Caused when adding Data Resource in AppSync GraphQL API. Added custom schema.graphql schema and then created Data Source which link to the table in DynamoDB.

**To Reproduce**
Environment contained DataStore and then added GraphQL api.
1. Run command amplify add api - > GraphQL and custom configuration enabling the AutoMerge functionality.
2. Here I add custom schema.graphql file which contained DynamoDB table exported schema and amplify push. 
3. Then I went to AppSync console -> Data Sources -> Create New DataSource and linked the DynamoDB table with new User Role. Versioning and Automatic generate GraphQL options were off. 
4. The error occues when the applicaiton was initiated. 

**Expected behavior**
The newPost data must be saved to the DynamoDB table. 

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.0.1 at C:\Flutter\flutter
    • Framework revision c5a4b4029c (3 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.56.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56

• No issues found! 
```

</details>

**Smartphone :**
 - Device: Nexus 5
 - OS: [ Android OS]
 - Version [API 24]

**Additional context**
The DynamoDB (TODO-table) created when form the default settings of GaphQL api was working without any issues. The data got updated to the TODO table. This error occured when I added my personal DynamoDB table schema and then added the AppSync Data Source link to DynamoDB table. 

**Error: **
```I/amplify:aws-datastore(12432): Orchestrator lock acquired.
I/amplify:aws-datastore(12432): Orchestrator transitioning from STOPPED to SYNC_VIA_API
I/amplify:aws-datastore(12432): Starting to observe local storage changes.
I/amplify:aws-datastore(12432): Now observing local storage. Local changes will be enqueued to mutation outbox.
I/amplify:aws-datastore(12432): Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore(12432): Setting currentState to SYNC_VIA_API
I/amplify:flutter:datastore(12432): Established a new stream form flutter com.amplifyframework.datastore.storage.sqlite.-$$Lambda$coxN3FV0myAqN-gpZfZvj7bzSOI@7f5d0db
I/amplify:aws-datastore(12432): Starting API synchronization mode.
I/amplify:aws-datastore(12432): Orchestrator lock released.
I/amplify:aws-datastore(12432): Starting processing subscription events.
W/amplify:aws-api(12432): Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
E/amplify:aws-datastore(12432): Failure encountered while attempting to start API sync.
E/amplify:aws-datastore(12432): DataStoreException{message=Error during subscription., cause=ApiException{message=Connection failed., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
E/amplify:aws-datastore(12432): 	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:298)
E/amplify:aws-datastore(12432): 	at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$797ziDK0io-qXODzROLOA77stS8.accept(lambda)
E/amplify:aws-datastore(12432): 	at com.amplifyframework.api.aws.SubscriptionOperation.lambda$null$1$SubscriptionOperation(SubscriptionOperation.java:92)
E/amplify:aws-datastore(12432): 	at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$l9lC7Ew6niNmyszMXQSUKS6YhwE.accept(lambda)
E/amplify:aws-datastore(12432): 	at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:127)
E/amplify:aws-datastore(12432): 	at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$2$SubscriptionOperation(SubscriptionOperation.java:83)
E/amplify:aws-datastore(12432): 	at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$dV6kPdbE8Z12Qd0_rE-16cujgUk.run(lambda)
E/amplify:aws-datastore(12432): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
E/amplify:aws-datastore(12432): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/amplify:aws-datastore(12432): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/amplify:aws-datastore(12432): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/amplify:aws-datastore(12432): 	at java.lang.Thread.run(Thread.java:761)
E/amplify:aws-datastore(12432): Caused by: ApiException{message=Connection failed., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
E/amplify:aws-datastore(12432): 	at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:128)
E/amplify:aws-datastore(12432): 	... 7 more ```

**Comment by riyan-datalyca** [comment]
Important Note: This error was caused due to the Expiration of the API KEY in AppSync GraphQL API. By changing the API KEY the Error got resolved. Please update accordingly and confirm if the issue and fix are accurate. Thank you.

**Comment by haverchuck** [comment]
@riyan-datalyca Thanks for updating this issue.  This looks accurate.
