### ISSUE TITLE
some REST API method have a fatal error on android when body not included in request

### ISSUE THREAD

**Issue by ragingsquirrel3** [aws-amplify/amplify-flutter#612]
**Describe the bug**
 put, post, patch crash fatally on android when body not set. Error is `java.lang.IllegalArgumentException: method PATCH must have a request body.`

**To Reproduce**
1. Run the example api app in android in debug mode `flutter run -d sdk`
2. Click on "Patch" button (which calls API with no body in the request)
3. Get error and flutter crashes.

```
E/AndroidRuntime(31856): java.lang.IllegalArgumentException: method PATCH must have a request body.
E/AndroidRuntime(31856): 	at okhttp3.Request$Builder.method(Request.kt:254)
E/AndroidRuntime(31856): 	at com.amplifyframework.api.aws.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:237)
E/AndroidRuntime(31856): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/AndroidRuntime(31856): 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
E/AndroidRuntime(31856): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
E/AndroidRuntime(31856): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(31856): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(31856): 	at java.lang.Thread.run(Thread.java:923)
```

**Expected behavior**
Certainly not a fatal error, though not sure exactly best way out, or why exactly it works on iPhone. Possible ways out:
* catch error and throw a flutter exception which is not fatal
* make the body a required parameter for `RestOptions` so this becomes a compile time error and forces developers to provide a body
* provide a default body, such as `"{}"`
* understand how this is not error in iOS and do that

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)

• No issues found!
```

</details>

**Smartphone (please complete the following information):**
Android simulator

**Comment by ragingsquirrel3** [comment]
Fixed in 0.2.2
