### ISSUE TITLE
Amplify.Auth.fetchAuthSession launches sign in WebView on iOS

### ISSUE THREAD

**Issue by gianmarcocalbi** [aws-amplify/amplify-flutter#733]
### Describe the bug
At app startup, I run

```dart
await Amplify.Auth.fetchAuthSession(
  options: CognitoSessionOptions(getAWSCredentials: true),
) as CognitoAuthSession`
```

to get info about the logged user that I need to initialize some other objects. If there is no logged user I catch the exception without letting it propagate.

Well, when I start the app for the first time, `fetchAuthSession` prompts a dialog to launch the WebView for login (**yet, I'd not expect this behavior**)

If I dismiss the dialog, and later try to sign in with

```dart
Amplify.Auth.signInWithWebUI(provider: AuthProvider.google)
```

I get this:

```
There is already a user which is signed in. Please log out the user before calling showSignIn
#0      AmplifyAuthCognitoMethodChannel.signInWithWebUI (package:amplify_auth_cognito/method_channel_auth_cognito.dart:298:7) <asynchronous suspension>
#1      AmplifyAuthCognito.signInWithWebUI (package:amplify_auth_cognito/amplify_auth_cognito.dart:119:17) <asynchronous suspension>
```

It's impossible that there is a signed-in user, because I have just created a fresh new user pool and identity.

### To Reproduce
Unfortunately I don't have a "test app" to provide you with.. but if you have one just do:

1. Fresh install an app that runs `Amplify.Auth.fetchAuthSession` at startup (catching exceptions in case there is no signed-in user)
2. Dismiss the alert dialog
3. Try to login with `Amplify.Auth.signInWithWebUI`

### Expected behavior
I'd expect no sign-in dialog from `Amplify.Auth.fetchAuthSession`

### Screenshots
Here is a video of the alert dialog prompting at startup.
_Sorry for the cold start, you can see the dialog at 0:11._

https://user-images.githubusercontent.com/13722041/126473466-08ff4f81-f713-413d-bc08-6b930a01af4a.mov

### Platform
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
✅ iOS
❌ Android

The issue **does not occur on Android** where I get the expected behavior: that is, the `fetchAuthSession` fails because there is no signed-in user (even if the exception message reads `Your session has expired.`) and after I can sign-in without problems.

```
D/AWSMobileClient(27940): Inspecting user state details
D/AWSMobileClient(27940): Inspecting user state details
D/AWSMobileClient(27940): waitForSignIn: userState:SIGNED_OUT
W/AWSMobileClient(27940): getCredentials: Failed to getCredentials from Cognito Identity
W/AWSMobileClient(27940): com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: d2460303-7044-4d9e-8cd8-84d6da3d4251)
W/AWSMobileClient(27940): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient(27940): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient(27940): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(27940): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient(27940): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient(27940): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3923)
W/AWSMobileClient(27940): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
W/AWSMobileClient(27940): 	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
W/AWSMobileClient(27940): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:397)
W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:442)
W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:439)
W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
W/AWSMobileClient(27940): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:auth_cognito(27940): SessionExpiredException
E/amplify:flutter:auth_cognito(27940): SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
E/amplify:flutter:auth_cognito(27940): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareCognitoSessionFailure(AuthCognito.kt:559)
E/amplify:flutter:auth_cognito(27940): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:353)
E/amplify:flutter:auth_cognito(27940): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:79)
E/amplify:flutter:auth_cognito(27940): 	at com.amplifyframework.auth.cognito.MobileClientSessionAdapter$1.onError(MobileClientSessionAdapter.java:74)
E/amplify:flutter:auth_cognito(27940): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:47)
```

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
```
➜   flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-US)
    • Flutter version 2.2.3 at /Users/gcalbi/dev/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gcalbi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7479365/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/gcalbi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Users/gcalbi/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • 6868F987-0796-49A4-BA77-A42DDFCEBB75 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 92.0.4515.107

! Doctor found issues in 1 category.

```

</details>

### Smartphone (please complete the following information):
 - Device: iPhone 12 simulator
 - OS: iOS 14.6

**Comment by gianmarcocalbi** [comment]
I need to investigate more the issue because after I erased the content of the simulator and installed the app again the issue did not occur.

I am closing the issue and if needed I will reopen it later.

**Comment by dander11** [comment]
I'm having this issue intermittently with users even after uninstalling and reinstalling. Is there really something left behind from previous installs that is causing this?

**Comment by dnys1** [comment]
Hi @dander11, please see the documentation available [here](https://docs.amplify.aws/lib/info/app-uninstall/q/platform/ios) for this issue. The Flutter team does not currently have an automated solution planned for this issue. Please consider filing a feature request ticket if that is something you'd like to see.
