### ISSUE TITLE
ResourceNotFoundException on trying to SignUp with Amplify

### ISSUE THREAD

**Issue by dev-Roshan-lab** [aws-amplify/amplify-flutter#740]
**Describe the bug**
`ResourceNotFoundException` thrown while trying to SignUp.

**Expected behavior**
Upon invoking `Amplify.Auth.signUp` with necessary data, OTP is received and the user is signed In

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[:heavy_check_mark:] Android
[:x:] iOS: haven't checked.

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1052], locale en-IN)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\skros\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\skros\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM A217F (mobile) • RZ8N816CTRD • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 91.0.864.59

• No issues found!

```

</details>

**Additional context**

```dart
try {
      print('-------------trying--------------');
      Map<String, String> userAttributes = {
        'email': regemail,
        'phone_number': '+91$phone'
      };
      SignUpResult res = await Amplify.Auth.signUp(
          username: '+91$phone',
          password: confirmpass,
          options: CognitoSignUpOptions(userAttributes: userAttributes));
      setState(() {
        isSignUpComplete = res.isSignUpComplete;
      });
    } on AuthException catch (_e) {
      print(_e);
      final snackBar = SnackBar(
          backgroundColor: Colors.red,
          content: Container(
              child: Text(
            'Something went wrong, please try again later',
            style: GoogleFonts.montserrat(color: Colors.white),
          )));
      ScaffoldMessenger.of(context).showSnackBar(snackBar);
    }
```

On trying this method, an AuthException is thrown that elaborates as

```
ResourceNotFoundException(message: Could not find the requested online resource., recoverySuggestion: Retry with exponential back-off or check your config file to be sure the endpoint is valid., underlyingException: com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException: User pool client 47r5gbil1bfhr09d5j50bekvmd does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 8f4db33b-835d-4872-ade1-07c49d78cfe9))
```
Apart from that:
- Successfully configured amplify
- Added auth Plugin
- In sandbox mode
- Added phone number to verified phone numbers
- synced changes from cloud w/ `amplify pull`

**Logs:**

```
E/amplify:flutter:auth_cognito(24388): ResourceNotFoundException
E/amplify:flutter:auth_cognito(24388): ResourceNotFoundException{message=Could not find the requested online resource., cause=com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException: User pool client 47r5gbil1bfhr09d5j50bekvmd does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 8f4db33b-835d-4872-ade1-07c49d78cfe9), recoverySuggestion=Retry with exponential back-off or check your config file to be sure the endpoint is valid.}
E/amplify:flutter:auth_cognito(24388): 	at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:107)
E/amplify:flutter:auth_cognito(24388): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onError(AWSCognitoAuthPlugin.java:300)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.AWSMobileClient$13$1.onFailure(AWSMobileClient.java:2121)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:486)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.AWSMobileClient$13.run(AWSMobileClient.java:2090)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito(24388): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:auth_cognito(24388): Caused by: com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException: User pool client 47r5gbil1bfhr09d5j50bekvmd does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 8f4db33b-835d-4872-ade1-07c49d78cfe9)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6770)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.signUp(AmazonCognitoIdentityProviderClient.java:5724)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUpInternal(CognitoUserPool.java:537)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:481)
E/amplify:flutter:auth_cognito(24388): 	... 3 more
E/amplify:flutter:auth_cognito(24388): AuthException
E/amplify:flutter:auth_cognito(24388): ResourceNotFoundException{message=Could not find the requested online resource., cause=com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException: User pool client 47r5gbil1bfhr09d5j50bekvmd does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 8f4db33b-835d-4872-ade1-07c49d78cfe9), recoverySuggestion=Retry with exponential back-off or check your config file to be sure the endpoint is valid.}
E/amplify:flutter:auth_cognito(24388): 	at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:107)
E/amplify:flutter:auth_cognito(24388): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onError(AWSCognitoAuthPlugin.java:300)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.AWSMobileClient$13$1.onFailure(AWSMobileClient.java:2121)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:486)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.AWSMobileClient$13.run(AWSMobileClient.java:2090)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito(24388): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:auth_cognito(24388): Caused by: com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException: User pool client 47r5gbil1bfhr09d5j50bekvmd does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 8f4db33b-835d-4872-ade1-07c49d78cfe9)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6770)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.signUp(AmazonCognitoIdentityProviderClient.java:5724)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUpInternal(CognitoUserPool.java:537)
E/amplify:flutter:auth_cognito(24388): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:481)
E/amplify:flutter:auth_cognito(24388): 	... 3 more
```

**Comment by dnys1** [comment]
Hi @dev-Roshan-lab were you able to resolve this issue? The error message is saying the user pool client does not exist. Do you remember if you had made some changes to your auth category in and around this error? You may have luck removing the `amplifyconfiguration.dart` file present and running `amplify pull` to ensure you have the latest changes.

**Comment by offlineprogrammer** [comment]
Hi @dev-Roshan-lab 

Following up on this. If you are still experiencing an issue, please provide the info requested above.

Regards
Mo

**Comment by nallibtermatrac** [comment]
I am facing this problem too.
No clue to solve this.
I am reviewing the client id, region and other... the same !

**Comment by cyberpunk-akash** [comment]
I am getting this after I deleted app client from Amazon Cognito. Looks like this needs to be resolved by creating a new app client under the concerned user pool and then somehow linking it to the flutter project
