### ISSUE TITLE
Null Pointer Exception while deleting parent table 

### ISSUE THREAD

**Issue by rohanakut** [aws-amplify/amplify-flutter#767]
I am trying to run Amplify on Flutter. While the rest of the operations seem to be working well, I am having a hard time in deleting a parent table. The following is my problem:

I have 2 tables namely: DeckListTable and CardsListTable. The CardsListTable can have multiple DeckListTable ids. 

The following is my GraphQL schema 

```
type CardsListTable @model @key(name: "byDeckListTable", fields: ["decklistID"]) @auth(rules: [{allow: public}]) @key(name: "byLoginTable", fields: ["logintableID"]) @key(name: "byChartListTable", fields: ["chartlisttableID"]) {
  id: ID!
  question: String
  answer: String
  confidence: Int
  decklistID: ID
  logintableID: ID
  chartlisttableID: ID
}

type DeckListTable @model @auth(rules: [{allow: public}]) @key(name: "byLoginTable", fields: ["logintableID"]) {
  id: ID!
  deckName: String
  CardsLists: [CardsListTable] @connection(keyName: "byDeckListTable", fields: ["id"])
  logintableID: ID
}

```

I am trying to delete the values in DeckListTable but amplify is throwing a Null pointer exception error. The following is my stacktrace

```
Delete operation failed.
E/amplify:flutter:datastore( 5371): DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}
E/amplify:flutter:datastore( 5371): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:530)
E/amplify:flutter:datastore( 5371): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$4xJ0GiWAuutTeU1lYbbrxzmMITw.run(Unknown Source:12)
E/amplify:flutter:datastore( 5371): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/amplify:flutter:datastore( 5371): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:flutter:datastore( 5371): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:datastore( 5371): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:datastore( 5371): 	at java.lang.Thread.run(Thread.java:919)
E/amplify:flutter:datastore( 5371): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference
E/amplify:flutter:datastore( 5371): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.recurseTree(SQLiteModelTree.java:125)
E/amplify:flutter:datastore( 5371): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.descendantsOf(SQLiteModelTree.java:87)
E/amplify:flutter:datastore( 5371): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:498)
E/amplify:flutter:datastore( 5371): 	... 6 more
E/flutter ( 5371): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: DataStoreException(message: Error in deleting the model., recoverySuggestion: See attached exception for details., underlyingException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference)
E/flutter ( 5371): #0      AmplifyDataStoreMethodChannel.delete (package:amplify_datastore/method_channel_datastore.dart:113:7)
E/flutter ( 5371): <asynchronous suspension>
E/flutter ( 5371): #1      AmplifyDb.deleteDeckData.<anonymous closure> (package:flashcards/database/amplify_db.dart:38:7)
E/flutter ( 5371): <asynchronous suspension>

```

The following is my delete query:
```
(await Amplify.DataStore.query(DeckListTable.classType,
            where: DeckListTable.ID.eq(deckId)))
        .forEach((element) async {
      await Amplify.DataStore.delete(element);
      print('Deleted a post');
    });
```
I am positive that I am not passing a null value as `deckId`, but it is not clear as to why it is throwing a null pointer error.

Thank you for the help

**Comment by cshfang** [comment]
Hi @rohanakut, thanks for filing this issue. I attempted to replicate the models you shared above but was unable to reproduce the `NullPointerException`. Could you let me know if
1. The app that is producing the error above is currently integrated with real-time sync to the cloud?
2. What the output of
```
await Amplify.DataStore.query(DeckListTable.classType,
            where: DeckListTable.ID.eq(deckId))

**Comment by rohanakut** [comment]
Thank you for the reply @cshfang . 

1. The app is synced real time with the cloud
2. On running the above query, the output of deckList is as expected
`[DeckListTable {id=171a05c0-e3e2-493b-9731-24a0bf1ae75a, deckName=first, logintableID=28f10caa-aa9d-4ad7-ace4-b05f4b3766a0}]`

Thank you

**Comment by rohanakut** [comment]
@cshfang Is there any update on this?

**Comment by cshfang** [comment]
@rohanakut I am still unable to reproduce this on my end, unfortunately. I will try to work backwards from the error but anything you can do to help me repro would be most helpful. E.g. if you could share a minimal project or code snippets where this issue manifests in an app from scratch it would go a long way.

**Comment by rohanakut** [comment]
Sure @cshfang .
I will share with you the workflow that I am going through and also the necessary snippets.

Initially there is a login where I check the user has logged an existing account or not. 
The amplify code for the same is 

```
Future<List<LoginTable>> checkLogin(String username, String password) async {
    List<LoginTable> login = await Amplify.DataStore.query(LoginTable.classType,
        where: LoginTable.USERNAME
            .eq(username)
            .and(LoginTable.PASSWORD.eq(password)));
    return login;
  }
```

Once the user is logged in I try to fetch the content of that user. This is the code foe the same

**Comment by HuiSF** [comment]
Issue may be related to https://github.com/aws-amplify/amplify-android/issues/1449

**Comment by aniket-chati** [comment]
@rohanakut was this issue solved for you finally? Can you help with the resolution steps?

**Comment by two4zero** [comment]
hi~ amplify.

I have the same problem.
`'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference`
'Null Pointer Exception while deleting parent table'

1. I created a model in amplify `admin ui`.
2. `amplify pull` in local.
3. `amplify/backend/api/ctc/schema.graphql` has no `'belongs-to'` described in https://docs.amplify.aws/cli-legacy/graphql-transformer/connection/#belongs-to
4. Is `'belongs-to'` setting required?

```
E/amplify:flutter:datastore(30087): DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}
E/amplify:flutter:datastore(30087): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:533)
```

```
>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.348], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (4 available)

• No issues found!
```

```
>npm ls -g --depth=0
\AppData\Roaming\npm
+-- @aws-amplify/cli@7.5.2
`-- npm@8.1.4
```

**Comment by two4zero** [comment]
maybe... 'belongs-to' setting is required.

**Comment by HuiSF** [comment]
Hi @two4zero sorry missed your comments!

In you first comment, did you mean that the `schema.graphql` doesn't have `belongsTo` on the child model referred by the `hasMany` relationship?

Could you provide the model for investigation?

**Comment by mmered8** [comment]
Damn, I had hoped this had been resolved... 

`Jobs deleteJob = listJobs.elementAt(i);

                                      (await Amplify.DataStore.query(Jobs.classType
                                          , where: Jobs.USERID.contains(widget.userId)
                                          & Jobs.ELEMENTID.contains(widget.elementID)
                                          & Jobs.ID.contains(deleteJob.id)))
                                          .forEach((Job) async {
                                        try {
                                          await Amplify.DataStore.delete(Job);
                                          print('Deleted a job');
                                          listJobs.removeAt(i);
                                        } on DataStoreException catch (e) {
                                          print('Delete failed: $e');
                                        }
                                      });

                                      // Jobs deleteJob = listJobs.elementAt(i);
                                      // try {
                                      //   await Amplify.DataStore.delete(deleteJob);
                                      //   print('Deleted a post');
                                      // } on DataStoreException catch (e) {
                                      //   print('Delete failed: $e');
                                      // }`
That Code is failing in all scenarios. Inside the widget and when instantiated during the init phase.

**Comment by rajd90** [comment]
Hi. I'm having the same problem....

My code (i've tried a few variations):
```
Place _placeToDelete = (await Amplify.DataStore.query<Place>(
                          Place.classType,
                          where: Place.ID.eq(widget.originalPlace.id)))
                      .first;
                  print("place to delete");
                  print(_placeToDelete);
                  await Amplify.DataStore.delete(_placeToDelete);
```
How I configure Amplify:
```
await Amplify.addPlugins([
      AmplifyAuthCognito(),
      AmplifyAPI(),
      AmplifyDataStore(modelProvider: ModelProvider.instance),
      AmplifyStorageS3()
    ]);
    // amplify config
    try {
      await Amplify.configure(amplifyconfig);
    } on AmplifyAlreadyConfiguredException {
      print(
          "authModel.dart: Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    }
```

Flutter doctor:
```
$ flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale en-GB)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\rajd9\AppData\Local\Android\sdk
    • Platform android-31, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\rajd9\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!
```

My GraphQL schema:
```
type Place @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  userID: ID! @index(name: "byUser", sortKeyFields: ["name"])
  name: String!
  place_id: String
  formatted_address: String
  lat: Float
  lng: Float
  saved: Boolean!
  visited: Boolean!
  tags: [String!]!
  recommendedByProfile: Profile @hasOne
  recommendedByText: String
  note: String
  rating: Float
  review: String
  icon: String
  types: [String!]!
}
```

The error:
```
E/amplify:flutter:datastore(19989): Delete operation failed.
E/amplify:flutter:datastore(19989): DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}
E/amplify:flutter:datastore(19989): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:533)
E/amplify:flutter:datastore(19989): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$4xJ0GiWAuutTeU1lYbbrxzmMITw.run(Unknown Source:12)
E/amplify:flutter:datastore(19989): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/amplify:flutter:datastore(19989): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
I/flutter (19989): WidgetsBinding...set initial rating
I/amplify:aws-datastore(19989): Orchestrator lock acquired.
I/amplify:aws-datastore(19989): Orchestrator lock released.
I/flutter (19989): place to delete
I/flutter (19989): Place {id=4be1e25c-34d0-4572-bc1d-080f4c8c258e, userID=6f1c53ee-845a-4f02-9816-9ecffb136bac, name=La Creperie de Hampstead, place_id=ChIJK7xz4IcadkgRVnC_XCg2aRE, formatted_address=77 Hampstead High St, London NW3 1RE, United Kingdom, lat=51.5557302, lng=-0.1768354, saved=true, visited=false, tags=[], recommendedByText=null, note=null, rating=null, review=null, icon=https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png, types=[restaurant, food, point_of_interest, store, establishment], placeRecommendedByProfileId=null}
I/amplify:aws-datastore(19989): Orchestrator lock acquired.
I/amplify:aws-datastore(19989): Orchestrator lock released.
E/amplify:flutter:datastore(19989): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:datastore(19989): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:datastore(19989): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:datastore(19989): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference
E/amplify:flutter:datastore(19989): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.recurseTree(SQLiteModelTree.java:125)
E/amplify:flutter:datastore(19989): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.descendantsOf(SQLiteModelTree.java:87)
E/amplify:flutter:datastore(19989): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:501)
E/amplify:flutter:datastore(19989): 	... 6 more
E/flutter (19989): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: DataStoreException(message: Error in deleting the model., recoverySuggestion: See attached exception for details., underlyingException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference)
E/flutter (19989): #0      AmplifyDataStoreMethodChannel.delete
package:amplify_datastore/method_channel_datastore.dart:162
E/flutter (19989): <asynchronous suspension>
E/flutter (19989): #1      _PlaceFormState.build.<anonymous closure>
package:savethatplace_flutter/widgets/placeForm.dart:284
E/flutter (19989): <asynchronous suspension>
E/flutter (19989):
```

**Comment by HuiSF** [comment]
Hi @two4zero @rajd90 There is a known issue existing in amplify-android, that deleting the parent model of a `hasOne` relationship causes below error

```
DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}
```

amplify-android maintainer are now aware of this issue, and they are looking into a solution.

**Comment by HuiSF** [comment]
amplify-android PR for fixing above exception:
https://github.com/aws-amplify/amplify-android/pull/1614

Note: this PR fixes the underlying exception, however, cascade delete is still not supported on a hasOne relationship., i.e. when deleting the parent model (which has one child), won't automatically delete the child.

**Comment by HuiSF** [comment]
hi @rajd90 regarding the schema you provided -

Here's a suggestion to make the `@hasOne` work - using `@belongsTo` on the child model. Example as below

```graphql
type Project @model {
  id: ID!
  name: String
  team: Team @hasOne
}

type Team @model {
  id: ID!
  name: String!
  project: Project @belongsTo # make the cascade delete work
}

# or

type Project @model {
  id: ID!
  name: String
  team: Team @hasOne
}

type Team @model {
  id: ID!
  name: String!
  projectID: ID
  project: Project @belongsTo(fields: ["projectID"]) # make the cascade delete work
}
```

**Comment by dkseo-lien** [comment]
Hi~ @HuiSF 

how to fix it in my case, please~

`Amplify.DataStore.delete(hospitalRoom)`

```
E/amplify:flutter:datastore(10246): DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}
```

`schema.graphql`
```
type WardBed @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  hospitalroomID: ID @index(name: "byHospitalRoom")
}

type HospitalRoom @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  wardBeds: [WardBed] @hasMany(indexName: "byHospitalRoom", fields: ["id"])
}
```

**Comment by HuiSF** [comment]
Hi @dkseo-lien yes I tried it myself in Admin Studio, it seems no way to create `belongsTo` on the `WardBed` model.

On workaround is that you can modify the `schema.graphql` (located in `<project_directory>/amplify/backend/api/<api_name>/`) manually.

```graphql
type WardBed @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  hospitalroomID: ID @index(name: "byHospitalRoom")
  hospitalRoom: HospitalRoom @belongsTo(fields: ["hospitalroomID"])
}

type HospitalRoom @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  wardBeds: [WardBed] @hasMany(indexName: "byHospitalRoom", fields: ["id"])
}
```

Then run `amplify codegen modes`. If no errors, then run `amplify push` to deploy the schema update.

In the meantime, I'm trying to reach out Amplify Studio regarding the issue you described.

**Comment by dkseo-lien** [comment]
@HuiSF Thank you~!
Hopefully Amplify Studio will patch it soon.
Happy new year~~~

**Comment by HuiSF** [comment]
Hi @dkseo-lien Amplify Studio Data modeling interface currently is not supporting create relationship using `@belongsTo` directive. 

At this moment, we can only use Amplify CLI to get around. Please refer to https://github.com/aws-amplify/amplify-adminui/issues/427#issuecomment-1006962854

Please feel free to follow up if you encounter any issues using CLI in the development cycle.

**Comment by HuiSF** [comment]
The fix implemented in amplify-android to eliminate below error has integrated into amplify-flutter version 0.3.2.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference
```

**Comment by HuiSF** [comment]
To clarify, the released fix only eliminates the underlying Java exception, it doesn't guarantee cascade delete on associated model. Cascade delete requires `@belongsTo` on the child side.
