### ISSUE TITLE
Amplify Auth - Example App - Android Exceptions

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-flutter#77]
**Describe the bug**

When running the example app within the Amplify Auth category of this repo, when clicking on the "configure" "get user details" and "sign out" buttons, etc. within an Android Emulator device, I get Android Exceptions. 

**To Reproduce**
1. Go to Auth category's example app
2. Run the example app
3. Click on the configure button and other buttons in the sample app 
4. The app will run fine, but if you look in the logs, you will see Android exceptions 

**Expected behavior**
No exceptions thrown. 

**Screenshots**
Here's the exception: 

```
W/AWSMobileClient(26440): Could not check if ACCESS_NETWORK_STATE permission is available.
W/AWSMobileClient(26440): java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
W/AWSMobileClient(26440): 	at java.lang.Class.classForName(Native Method)
W/AWSMobileClient(26440): 	at java.lang.Class.forName(Class.java:454)
W/AWSMobileClient(26440): 	at java.lang.Class.forName(Class.java:379)
W/AWSMobileClient(26440): 	at com.amazonaws.mobile.client.AWSMobileClient.isNetworkAvailable(AWSMobileClient.java:771)
W/AWSMobileClient(26440): 	at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:983)
W/AWSMobileClient(26440): 	at com.amazonaws.mobile.client.AWSMobileClient.signOut(AWSMobileClient.java:1483)
W/AWSMobileClient(26440): 	at com.amazonaws.mobile.client.AWSMobileClient$9.run(AWSMobileClient.java:1569)
W/AWSMobileClient(26440): 	at com.amazonaws.mobile.client.AWSMobileClient$9.run(AWSMobileClient.java:1520)
W/AWSMobileClient(26440): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
W/AWSMobileClient(26440): 	at java.lang.Thread.run(Thread.java:923)
W/AWSMobileClient(26440): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/~~RRTqeS4ojfhaUqv3RaTVUw==/com.amazonaws.amplify.amplify_auth_cognito_example-r609kCpBPJWQBa3tcJHOuQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~RRTqeS4ojfhaUqv3RaTVUw==/com.amazonaws.amplify.amplify_auth_cognito_example-r609kCpBPJWQBa3tcJHOuQ==/lib/x86, /data/app/~~RRTqeS4ojfhaUqv3RaTVUw==/com.amazonaws.amplify.amplify_auth_cognito_example-r609kCpBPJWQBa3tcJHOuQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
W/AWSMobileClient(26440): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
W/AWSMobileClient(26440): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/AWSMobileClient(26440): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/AWSMobileClient(26440): 	... 10 more
I/flutter (26440): USER IS SIGNED OUT
E/Surface (26440): getSlotFromBufferLocked: unknown buffer: 0x0

```
**Platform**
Amplify-Flutter only on Android 

**Smartphone (please complete the following information):**
Android Emulator

**Comment by fjnoyp** [comment]
This issue does not happen on the example app ... So it might be a configuration issue I made on my machine or something specific to just this auth example app as well

**Comment by fjnoyp** [comment]
Related to my local configuration of locally hosted pub dependencies and local file pub dependencies causing conflicts when running the example apps.
