### ISSUE TITLE
Error when I do Apple's Login

### ISSUE THREAD

**Issue by toshiossada** [aws-amplify/amplify-flutter#790]
Hello, I'm using cognito to do social network login, Facebook's Login and Google's Login works great but and I done Apple' Login I get follow error.
I'm testing on android device

![image](https://user-images.githubusercontent.com/2637049/128703324-bce2edf0-bb48-40ec-8824-18ee8fdfb7a3.png)

```
W/MixpanelAPI.SysInfo(19901): Permission READ_PHONE_STATE not granted. Property $radio will not be available.
D/AuthClient(19901): Authorization flow completed successfully
W/amplify:flutter:auth_cognito:utils(19901): HostedUIRedirectActivity is not declared in AndroidManifest.
E/amplify:flutter:auth_cognito(19901): AuthException
E/amplify:flutter:auth_cognito(19901): AuthException{message=Sign-in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: invalid_request, recoverySuggestion=See attached exception for more details}
E/amplify:flutter:auth_cognito(19901): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$22.onError(AWSCognitoAuthPlugin.java:1095)
E/amplify:flutter:auth_cognito(19901): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(19901): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito(19901): 	at com.amazonaws.mobile.client.AWSMobileClient$25$1$3.run(AWSMobileClient.java:3389)
E/amplify:flutter:auth_cognito(19901): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:auth_cognito(19901): Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: invalid_request
E/amplify:flutter:auth_cognito(19901): 	at com.amazonaws.mobileconnectors.cognitoauth.AuthClient$1$2.run(AuthClient.java:438)
E/amplify:flutter:auth_cognito(19901): 	at android.os.Handler.handleCallback(Handler.java:938)
E/amplify:flutter:auth_cognito(19901): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/amplify:flutter:auth_cognito(19901): 	at android.os.Looper.loop(Looper.java:223)
E/amplify:flutter:auth_cognito(19901): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/amplify:flutter:auth_cognito(19901): 	at java.lang.reflect.Method.invoke(Native Method)
E/amplify:flutter:auth_cognito(19901): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/amplify:flutter:auth_cognito(19901): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (19901): Sign-in with web UI failed
E/amplify:flutter:auth_cognito(19901): SignedOutException
E/amplify:flutter:auth_cognito(19901): SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
E/amplify:flutter:auth_cognito(19901): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.onGetCurrentUser(AuthCognito.kt:380)
E/amplify:flutter:auth_cognito(19901): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.onMethodCall(AuthCognito.kt:177)
E/amplify:flutter:auth_cognito(19901): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/amplify:flutter:auth_cognito(19901): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/amplify:flutter:auth_cognito(19901): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/amplify:flutter:auth_cognito(19901): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/amplify:flutter:auth_cognito(19901): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/amplify:flutter:auth_cognito(19901): 	at android.os.Looper.loop(Looper.java:183)
E/amplify:flutter:auth_cognito(19901): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/amplify:flutter:auth_cognito(19901): 	at java.lang.reflect.Method.invoke(Native Method)
E/amplify:flutter:auth_cognito(19901): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/amplify:flutter:auth_cognito(19901): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (19901): You are currently signed out.

```

```
$ flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision f4abaa0735 (6 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

```
dependencies:
  amplify_flutter: ^0.2.1
  amplify_auth_cognito: ^0.2.1
```

**Comment by toshiossada** [comment]
![image](https://user-images.githubusercontent.com/2637049/128704902-61403579-8686-43ff-a4c7-498d2350c8e4.png)
![image](https://user-images.githubusercontent.com/2637049/128704975-279b551a-4d31-4cba-93d5-cc9f2dc72592.png)
![image](https://user-images.githubusercontent.com/2637049/128705038-83fae2e7-3f80-4611-806e-f07757fa0646.png)
![image](https://user-images.githubusercontent.com/2637049/128705112-c5db2974-2a4f-4cf5-a7f8-4e7d22a6ed1b.png)

**Comment by dnys1** [comment]
Hi @toshiossada, sorry you are experiencing this issue. Please verify you have added the Hosted UI activity to your Android manifest and try signing in again: https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter#android-platform-setup

**Comment by toshiossada** [comment]
Yes I did.
Google and Facebook' Login works well
Just Apple's login doesnt work

**Comment by dnys1** [comment]
Thank you for verifying. Could you also please verify that you have configured Sign In With Apple as such?

 Enter your Services ID for your OAuth flow:  <bundle ID>.sid
 Enter your Team ID for your OAuth flow:  <10-digit alphanumeric code>
 Enter your Key ID for your OAuth flow:  <10-digit alphanumeric code>
 Enter your Private Key for your OAuth flow:  <.p8 key with no headers and newlines>

**Comment by offlineprogrammer** [comment]
Hey @toshiossada 

I am closing this issue for now as we didn't hear from you
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Comment by joshuafriso** [comment]
I have the same error. Someone know how to fix it?

I had check my config settings and them are correct

**Comment by abdallahshaban557** [comment]
@joshuafriso  - since we have closed this issue - can you please open a new one, and provide us with the info needed in the issue template?
