### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by FirdousNath** [aws-amplify/amplify-flutter#791]
```
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.a(MethodChannel.java:14)
       at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareSignInResult$lambda-36(AuthCognito.java:18)
       at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.lambda$-hLIiVX5tYvt6Yd7EzY14YjOdTU(AuthCognito.java)
       at com.amazonaws.amplify.amplify_auth_cognito.-$$Lambda$AuthCognito$-hLIiVX5tYvt6Yd7EzY14YjOdTU.run(-.java:4)
```

This error is being seen on crashlytics. Mu pub spec.yaml looks like : 
```
`amplify_flutter: ^0.2.0-nullsafety.1
  amplify_auth_cognito: ^0.2.0-nullsafety.1
  amplify_storage_s3: ^0.2.0-nullsafety.1`
```

**Comment by offlineprogrammer** [comment]
Hi @FirdousNath 

Can you please provide more details on this

Feel free to test using the latest build and let us know if you got any issues


Thanks
Mo

**Comment by FirdousNath** [comment]
this issue is resolved when I wait `Amplify.Auth.fetchAuthSession` response. Actually I was calling it twice when token was expiring on android.
