### ISSUE TITLE
Flutter app using datastore and cloud sync crashes on start

### ISSUE THREAD

**Issue by santhoshraje** [aws-amplify/amplify-flutter#828]
I have no issues running my app in debug mode but when I try to run it in release mode my app crashes immediately when it starts and I get the following error:

```
E/AndroidRuntime(31841): FATAL EXCEPTION: RxCachedThreadScheduler-4
E/AndroidRuntime(31841): Process: com.app.myapp, PID: 31841
E/AndroidRuntime(31841): z9: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava
/wiki/What's-different-in-2.0#error-handling | java.lang.IllegalAccessError: Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'Ka$a' (declaration of 'com.amplifyframework.dat
astore.syncengine.SubscriptionProcessor' appears in /data/app/com.app.myapp-x3nLa4_rfpjjcJ4Lg_N67g==/base.apk)
E/AndroidRuntime(31841):        at Lb.f(:2)
E/AndroidRuntime(31841):        at k9$a.run(Unknown Source:19)
E/AndroidRuntime(31841):        at ob.run(Unknown Source:21)
E/AndroidRuntime(31841):        at ob.call(Unknown Source:0)
E/AndroidRuntime(31841):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(31841):        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AndroidRuntime(31841):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(31841):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(31841):        at java.lang.Thread.run(Thread.java:784)
E/AndroidRuntime(31841): Caused by: java.lang.IllegalAccessError: Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'Ka$a' (declaration of 'com.amplifyframework.datastore.sync
engine.SubscriptionProcessor' appears in /data/app/com.app.myapp-x3nLa4_rfpjjcJ4Lg_N67g==/base.apk)
E/AndroidRuntime(31841):        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.l(Unknown Source:41)
E/AndroidRuntime(31841):        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.m(Unknown Source:0)
E/AndroidRuntime(31841):        at com.amplifyframework.datastore.syncengine.S0.a(Unknown Source:11)
E/AndroidRuntime(31841):        at Ka.p(Unknown Source:10)
E/AndroidRuntime(31841):        at f9.e(Unknown Source:5)
E/AndroidRuntime(31841):        at La.p(Unknown Source:17)
E/AndroidRuntime(31841):        at f9.e(Unknown Source:5)
E/AndroidRuntime(31841):        at Xa$b.run(Unknown Source:6)
E/AndroidRuntime(31841):        at k9$a.run(Unknown Source:9)
E/AndroidRuntime(31841):        ... 7 more
```

I am using the following configurations:
```
amplify_flutter: ^0.2.2
amplify_datastore: ^0.2.2
amplify_auth_cognito: ^0.2.2
amplify_api: ^0.2.2
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (8 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by HuiSF** [comment]
Hi @santhoshraje thanks for reporting this issue. This looks like an issue that happened within amplify-android.
I tried release build (amplify-flutter datastore example app) running in x64 Android emulator, everything went well for me.

Looking at amply-android issues, similar issues were reported, and they seem to be related to network conditions and number of models to be subscribed. Does any of [these issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+The+exception+could+not+be+delivered+to+the+consumer+because+it+has+already+canceled%2Fdisposed+the+flow+or+the+exception+has+nowhere+to+go+to+begin+with+is%3Aclosed) similar to your setup?

**Comment by santhoshraje** [comment]
Hi @HuiSF thanks for the reply. I am currently running my app on a physical device. I have a stable network connection to the device and only have one model that I am subscribed to. 

I did notice that in my code if I comment out the amplify API part I don't get this error. I am not sure why this is so. But I need that for the real time functionality in my app.

```
    await Amplify.addPlugins([
      AmplifyDataStore(modelProvider: ModelProvider.instance),
      // AmplifyAPI(),
      AmplifyAuthCognito()
    ]);
```

**Comment by santhoshraje** [comment]
To investigate the issue, I created a new amplify project with the same model and a new flutter project:

```
import 'package:flutter/material.dart';
// Amplify Flutter Packages
import 'package:amplify_flutter/amplify.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:amplify_api/amplify_api.dart';
// Generated in previous step
import 'models/ModelProvider.dart';
import 'amplifyconfiguration.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _amplifyConfigured = false;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _configureAmplify();

  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
    );
  }

  void _configureAmplify() async {

    final AmplifyDataStore _dataStorePlugin = AmplifyDataStore(modelProvider: ModelProvider.instance);

    final AmplifyAPI _apiPlugin = AmplifyAPI();

    await Amplify.addPlugins([_dataStorePlugin, _apiPlugin]);

    await Amplify.configure(amplifyconfig);

    Amplify.DataStore.observe(User.classType).listen((event) {
      print(event);
    });

  }
}
```
The `observer` part of this code gives me the following error when I run it in release mode:

```
E/flutter (28322): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(DataStoreException, Translating platform exception failed. Please take a look at
E/flutter (28322): https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
E/flutter (28322): match your scenario, and file an issue with the details of the bug if there isn't., {recoverySuggestion: Retry., underlyingException: DataStoreException{message=Timed out while starting to obser
ve storage changes., cause=java.lang.RuntimeException: DataStoreException{message=Error in querying the model., cause=DataStoreException{message=Invalid SQL statement: SELECT `PendingMutation$PersistentRecord`.`id
` AS `PendingMutation$PersistentRecord_id`, `PendingMutation$PersistentRecord`.`containedModelClassName` AS `PendingMutation$PersistentRecord_containedModelClassName`, `PendingMutation$PersistentRecord`.`contained
ModelId` AS `PendingMutation$PersistentRecord_containedModelId`, `PendingMutation$PersistentRecord`.`serializedMutationData` AS `PendingMutation$PersistentRecord_serializedMutationData` FROM `PendingMutation$Persi
stentRecord`;, cause=android.database.sqlite.SQLiteException: no such table: PendingMutation$PersistentRecord (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT `PendingMutation$PersistentRecord`.`id` AS `Pen
dingMutation$PersistentRecord_id`, `PendingMutation$PersistentRecord`.`containedModelClassName` AS `PendingMutation$PersistentRecord_containedModelClassName`, `PendingMutation$PersistentRecord`.`containedModelId`
AS `PendingMutation$PersistentRecord_containedModelId`, `PendingMutation$PersistentRecord`.`serializedMutationData` AS `PendingMutation$PersistentRecord_serializedMutationData` FROM `PendingMutation$PersistentReco
rd`;, (OS error - 0:Success), recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at
E/flutter (28322): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that
E/flutter (28322): match your scenario, and file an issue with the details of the bug if there isn't.}, recoverySuggestion=See attached exception for details.}, recoverySuggestion=There is a possibility that there
 is a bug if this error persists. Please take a look at
E/flutter (28322): https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that
E/flutter (28322): match your scenario, and file an issue with the details of the bug if there isn't.}, message: Failed to start DataStore.}, null)
E/flutter (28322):
```

**Comment by HuiSF** [comment]
```
cause=android.database.sqlite.SQLiteException: no such table:
```

From this error it looks like the DataStore wasn't able to correctly create tables in local SQLite DB. Could you try to delete the App from you device and reinstall, restart again? (Or invoke `Amplify.DataStore.clear()` which will delete and recreated local DB tables.)

**Comment by santhoshraje** [comment]
Thanks @HuiSF `Amplify.DataStore.clear()` clear worked for the second issue that I posted. Any ideas for the first issue? I have a deadline for this app and still cant seem to get it to work

**Comment by HuiSF** [comment]
@santhoshraje After using `Amplify.DataStore.clear()` were you able to subscribe all models and was it running correctly with your new project?

**Comment by dnys1** [comment]
This has been more properly addressed in version 0.2.8 - it should be possible to set `minifyEnabled` and `shrinkResources` to true again, and no Proguard files should be needed for DataStore or its dependencies.

**Comment by graphicbeacon** [comment]
Thanks for your recommendations there @santhoshraje https://github.com/aws-amplify/amplify-flutter/issues/828#issuecomment-905963525 and @jahid-hasan-polash for confirming it works

In my case it worked when I added the following lines to my android/app/build.gradle

```gradle
buildTypes {
    release {
        // TODO: Add your own signing config for the release build.
        // Signing with the debug keys for now, so `flutter run --release` works.
        signingConfig signingConfigs.debug
        minifyEnabled false // <---- Added this line
        shrinkResources false // <---- Added this line
    }
}
```

**Comment by dnys1** [comment]
Hey @graphicbeacon - are you saying the 0.2.8 update doesn't work for you unless you set `shrinkResources` to true? Are you getting the same error as above? `Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'Ka$a'`

**Comment by AzharRaeisi** [comment]
Hi there, non of above solution worked for me

**Comment by Jordan-Nelson** [comment]
@AzharRaeisi - Can you share your `/android/build.gradle` file so that I can see what version of kotlin and gradle is being used in your project?
