### ISSUE TITLE
[Authentication] Don't require the app to check if it's a first time running the app before checking auth session

### ISSUE THREAD

**Issue by dander11** [aws-amplify/amplify-flutter#848]
I was told to make a feature request so that we don't have to manually check if we can call fetchAuthSession. Bug information taken from here: https://github.com/aws-amplify/amplify-flutter/issues/733

 ### Describe the bug
 At app startup, I run
 
 ```dart
 await Amplify.Auth.fetchAuthSession(
   options: CognitoSessionOptions(getAWSCredentials: true),
 ) as CognitoAuthSession`
 ```
 
 to get info about the logged user that I need to initialize some other objects. If there is no logged user I catch the exception without letting it propagate.
 
 Well, when I start the app for the first time, `fetchAuthSession` prompts a dialog to launch the WebView for login (**yet, I'd not expect this behavior**)
 
 If I dismiss the dialog, and later try to sign in with
 
 ```dart
 Amplify.Auth.signInWithWebUI(provider: AuthProvider.google)
 ```
 
 I get this:
 
 ```
 There is already a user which is signed in. Please log out the user before calling showSignIn
 #0      AmplifyAuthCognitoMethodChannel.signInWithWebUI (package:amplify_auth_cognito/method_channel_auth_cognito.dart:298:7) <asynchronous suspension>
 #1      AmplifyAuthCognito.signInWithWebUI (package:amplify_auth_cognito/amplify_auth_cognito.dart:119:17) <asynchronous suspension>
 ```
 
 It's impossible that there is a signed-in user, because I have just created a fresh new user pool and identity.
 
 ### To Reproduce
 Unfortunately I don't have a "test app" to provide you with.. but if you have one just do:
 
 1. Fresh install an app that runs `Amplify.Auth.fetchAuthSession` at startup (catching exceptions in case there is no signed-in user)
 2. Dismiss the alert dialog
 3. Try to login with `Amplify.Auth.signInWithWebUI`
 
 ### Expected behavior
 I'd expect no sign-in dialog from `Amplify.Auth.fetchAuthSession`
 
 ### Screenshots
 Here is a video of the alert dialog prompting at startup.
 _Sorry for the cold start, you can see the dialog at 0:11._
 
  screen_recording.mov 
 ### Platform
 Amplify Flutter current supports iOS and Android. This issue is reproducible in (check all that apply):
 ✅ iOS
 ❌ Android
 
 The issue **does not occur on Android** where I get the expected behavior: that is, the `fetchAuthSession` fails because there is no signed-in user (even if the exception message reads `Your session has expired.`) and after I can sign-in without problems.
 
 ```
 D/AWSMobileClient(27940): Inspecting user state details
 D/AWSMobileClient(27940): Inspecting user state details
 D/AWSMobileClient(27940): waitForSignIn: userState:SIGNED_OUT
 W/AWSMobileClient(27940): getCredentials: Failed to getCredentials from Cognito Identity
 W/AWSMobileClient(27940): com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: d2460303-7044-4d9e-8cd8-84d6da3d4251)
 W/AWSMobileClient(27940): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
 W/AWSMobileClient(27940): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
 W/AWSMobileClient(27940): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
 W/AWSMobileClient(27940): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
 W/AWSMobileClient(27940): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
 W/AWSMobileClient(27940): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
 W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3923)
 W/AWSMobileClient(27940): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
 W/AWSMobileClient(27940): 	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
 W/AWSMobileClient(27940): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
 W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:397)
 W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:442)
 W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:439)
 W/AWSMobileClient(27940): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
 W/AWSMobileClient(27940): 	at java.lang.Thread.run(Thread.java:923)
 E/amplify:flutter:auth_cognito(27940): SessionExpiredException
 E/amplify:flutter:auth_cognito(27940): SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
 E/amplify:flutter:auth_cognito(27940): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareCognitoSessionFailure(AuthCognito.kt:559)
 E/amplify:flutter:auth_cognito(27940): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:353)
 E/amplify:flutter:auth_cognito(27940): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:79)
 E/amplify:flutter:auth_cognito(27940): 	at com.amplifyframework.auth.cognito.MobileClientSessionAdapter$1.onError(MobileClientSessionAdapter.java:74)
 E/amplify:flutter:auth_cognito(27940): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:47)
 ```
 
 Output of `flutter doctor -v`
 ### Smartphone (please complete the following information):
 * Device: iPhone 12 simulator
 * OS: iOS 14.6

**Comment by haverchuck** [comment]
@dander11 - Thanks for logging this issue. Unfortunately the .mov you posted doesn't seem to be working (the file name is just text). When you say that the fetchAuthSession launches a dialog, do you mean something that you've built, or the standard iOS webview alert (see below)?

![image](https://user-images.githubusercontent.com/10621276/131745946-1853b2f0-2a44-45d6-a987-48ea253373eb.png)

**Comment by haverchuck** [comment]
https://github.com/aws-amplify/amplify-ios/issues/1410

**Comment by HuiSF** [comment]
Fix has been released, need to verify if still reproducible.

**Comment by Sunsiha** [comment]
any update on this ticket?

**Comment by Jordan-Nelson** [comment]
Hello all - This issue should be resolved in Amplify-Flutter v0.4.3 and later, as long as the version of `AWSCore` your app depends on is 2.27.2 or higher. You can find the version of `AWSCore` in your Podfile.lock. Look for a line that looks like:
```
- AWSCore (2.27.9)
```

If the version is not 2.27.2 or higher, you should be able to run `pod update Amplify AWSPluginsCore AmplifyPlugins` in your `/ios` dir to update to the latest version (currently 2.27.9).

With 2.27.2 and higher there is a check on initialization to see if the cached credentials are invalid for the current configuration, and if so, they are cleared.

If you are still experiencing this issue after verifying that you are on 2.27.9, please let me know.

**Comment by Jordan-Nelson** [comment]
Hello all - I am going to close this out since this was resolved in a previous version of amplify flutter. Please see the message above, and feel free to open a new issue if you are still experiencing any issues.
