### ISSUE TITLE
Token is not from a supported provider of this identity pool

### ISSUE THREAD

**Issue by sanjidbillah** [aws-amplify/amplify-flutter#851]
**Describe the bug**
This is ok with IOS , but i get execption from android

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[✔️] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```D/AWSMobileClient(30407): _federatedSignIn: Putting provider and token in store
D/AWSMobileClient(30407): Inspecting user state details
D/AWSMobileClient(30407): hasFederatedToken: false provider: cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_hZmNnEJLW
W/AWSMobileClient(30407): Failed to federate tokens during sign-in
W/AWSMobileClient(30407): java.lang.RuntimeException: Error in federating the token.
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1803)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1731)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1223)
W/AWSMobileClient(30407): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1020)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1208)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(30407): 	at java.lang.Thread.run(Thread.java:923)
W/AWSMobileClient(30407): Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Token is not from a supported provider of this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 6d72f8da-27b5-4e49-910d-ddaeada7562d)
W/AWSMobileClient(30407): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient(30407): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient(30407): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(30407): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient(30407): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3923)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:640)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:511)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1834)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1790)
W/AWSMobileClient(30407): 	... 7 more
W/InternalCallback(30407): Library attempted to call user callback twice, expected only once
D/AWSMobileClient(30407): Inspecting user state details
W/InternalCallback(30407): Library attempted to call user callback twice, expected only once
D/AWSMobileClient(30407): Inspecting user state details
D/AWSMobileClient(30407): waitForSignIn: userState:SIGNED_OUT
W/AWSMobileClient(30407): getCredentials: Failed to getCredentials from Cognito Identity
W/AWSMobileClient(30407): com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Token is not from a supported provider of this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 4146545d-26fe-48c8-9868-9d9b7a61d7fb)
W/AWSMobileClient(30407): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient(30407): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient(30407): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(30407): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient(30407): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3923)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:397)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:442)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:439)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
W/AWSMobileClient(30407): 	at java.lang.Thread.run(Thread.java:923)
I/flutter (30407): call herenull
D/AWSMobileClient(30407): Inspecting user state details
D/AWSMobileClient(30407): Inspecting user state details
D/AWSMobileClient(30407): waitForSignIn: userState:SIGNED_OUT
W/AWSMobileClient(30407): getCredentials: Failed to getCredentials from Cognito Identity
W/AWSMobileClient(30407): com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Token is not from a supported provider of this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: ad7cd6c4-e2f0-4355-925d-bee7c8e6d39f)
W/AWSMobileClient(30407): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient(30407): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient(30407): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(30407): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient(30407): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3923)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
W/AWSMobileClient(30407): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:397)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:442)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:439)
W/AWSMobileClient(30407): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
W/AWSMobileClient(30407): 	at java.lang.Thread.run(Thread.java:923)
W/oy.dev.custome(30407): Reducing the number of considered missed Gc histogram windows from 160 to 100
I/flutter (30407): sagsfalse
Reloaded 1 of 1791 libraries in 1,444ms.
```

</details>

<details>
<summary> amplifyConfiguration.dart file </summary>
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-southeast-1:2379c95e-98e3-4c33-b2da-*******",
                            "Region": "ap-southeast-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-southeast-1_h******",
                        "AppClientId": "31nno972i**********",
                        "Region": "ap-southeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}''';

</details>

**Comment by yonycherkos** [comment]
Hi @sanjidbillah, I have exactly the same issue. I have tried a lot to solve it with no luck. could please tell me how you solve this?

**Comment by sanjidbillah** [comment]
@yonycherkos  I added PoolId in AWS
