### ISSUE TITLE
Widget tests failed for amplify auth

### ISSUE THREAD

**Issue by Abhishek01039** [aws-amplify/amplify-flutter#909]
**Describe the bug**
Widget testing which is written by @Jordan-Nelson for amplify auth (https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_auth_cognito/example/integration_test) is failing.

**To Reproduce**
1. clone the project
2. run integration test using driver command `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/widget_testing/login_screen_test.dart`

**Expected behavior**
All tests should be passed.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[-] Android
[-] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.5.1 at /Users/abhishek/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/abhishek/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/abhishek/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.54.3)
    • VS Code at /Users/abhishek/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 mini (mobile) • D9CA119B-B70F-461F-B4E3-514AA31F5459 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 2 categories.
```

</details>

**Smartphone (please complete the following information):**
 - Device: iphone 12
 - OS: iOS 14.3

Error logs:

<details>

```
abhishek@abhisheks-mbp Flutter % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/widget_testing/login_screen_test.dart       
Running "flutter pub get" in Flutter...                          1,148ms
Running pod install...                                              4.3s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         5.0s
Xcode build done.                                           34.1s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:63188/Kt4OYRRdlXI=/
VMServiceFlutterDriver: Isolate found with number: 1712477190525403
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
flutter: 00:00 +0: signIn (setUpAll)
VMServiceFlutterDriver: Connected to Flutter application.
flutter: 00:02 +1: signIn should signIn a user
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following UserNotConfirmedException was thrown running a test:
flutter: UserNotConfirmedException(message: User is not confirmed., recoverySuggestion: See attached
flutter: exception for more details, underlyingException: The operation couldn’t be completed.
flutter: (AmplifyPlugins.AWSCognitoAuthError error 1.))
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      AmplifyAuthCognitoMethodChannel.signIn (package:amplify_auth_cognito/method_channel_auth_cognito.dart:122:7)
flutter: <asynchronous suspension>
flutter: #1      AmplifyAuthCognito.signIn (package:amplify_auth_cognito/amplify_auth_cognito.dart:69:17)
flutter: <asynchronous suspension>
flutter: #2      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:40:11)
flutter: <asynchronous suspension>
flutter: #3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
flutter: <asynchronous suspension>
flutter: #4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
flutter: <asynchronous suspension>
flutter:
flutter: The test description was:
flutter:   should signIn a user
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:03 +1: signIn should signIn a user [E]
flutter:   Test failed. See exception logs above.
  The test description was: should signIn a user
flutter:
flutter: Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
flutter: 00:03 +1 -1: signIn should throw a UserNotConfirmedException with an incorrect password
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following TestFailure object was thrown running a test:
flutter:   Expected: <Instance of 'UserNotConfirmedException'>
flutter:   Actual: NotAuthorizedException:<NotAuthorizedException(message: Incorrect username or password.,
flutter: recoverySuggestion: Check whether the given values are correct and the user is authorized to perform
flutter: the operation., underlyingException: null)>
flutter:    Which: is not an instance of 'UserNotConfirmedException'
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #4      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:52:9)
flutter: <asynchronous suspension>
flutter: #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
flutter: <asynchronous suspension>
flutter: #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
flutter: <asynchronous suspension>
flutter:
flutter: This was caught by the test expectation on the following line:
flutter:   file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart line 52
flutter: The test description was:
flutter:   should throw a UserNotConfirmedException with an incorrect password
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:04 +1 -1: signIn should throw a UserNotConfirmedException with an incorrect password [E]
flutter:   Test failed. See exception logs above.
  The test description was: should throw a UserNotConfirmedException with an incorrect password
flutter:
flutter: Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
flutter: 00:04 +1 -2: signIn should throw a UserNotFoundException with a non-existent user
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following TestFailure object was thrown running a test:
flutter:   Expected: <Instance of 'UserNotFoundException'>
flutter:   Actual: NotAuthorizedException:<NotAuthorizedException(message: Incorrect username or password.,
flutter: recoverySuggestion: Check whether the given values are correct and the user is authorized to perform
flutter: the operation., underlyingException: null)>
flutter:    Which: is not an instance of 'UserNotFoundException'
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #4      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:63:9)
flutter: <asynchronous suspension>
flutter: #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
flutter: <asynchronous suspension>
flutter: #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
flutter: <asynchronous suspension>
flutter:
flutter: This was caught by the test expectation on the following line:
flutter:   file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart line 63
flutter: The test description was:
flutter:   should throw a UserNotFoundException with a non-existent user
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:06 +1 -2: signIn should throw a UserNotFoundException with a non-existent user [E]
flutter:   Test failed. See exception logs above.
  The test description was: should throw a UserNotFoundException with a non-existent user
flutter:
flutter: Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
flutter: 00:06 +1 -3: signIn should throw an InvalidStateException if a user is already signed in
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following UserNotConfirmedException was thrown running a test:
flutter: UserNotConfirmedException(message: User is not confirmed., recoverySuggestion: See attached
flutter: exception for more details, underlyingException: The operation couldn’t be completed.
flutter: (AmplifyPlugins.AWSCognitoAuthError error 1.))
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      AmplifyAuthCognitoMethodChannel.signIn (package:amplify_auth_cognito/method_channel_auth_cognito.dart:122:7)
flutter: <asynchronous suspension>
flutter: #1      AmplifyAuthCognito.signIn (package:amplify_auth_cognito/amplify_auth_cognito.dart:69:17)
flutter: <asynchronous suspension>
flutter: #2      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:72:7)
flutter: <asynchronous suspension>
flutter: #3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
flutter: <asynchronous suspension>
flutter: #4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
flutter: <asynchronous suspension>
flutter:
flutter: The test description was:
flutter:   should throw an InvalidStateException if a user is already signed in
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:07 +1 -3: signIn should throw an InvalidStateException if a user is already signed in [E]
flutter:   Test failed. See exception logs above.
  The test description was: should throw an InvalidStateException if a user is already signed in
flutter:
flutter: Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
flutter: 00:07 +1 -4: signIn (tearDownAll)
flutter: 00:07 +2 -4: signOut should sign a user out
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following UserNotConfirmedException was thrown running a test:
flutter: UserNotConfirmedException(message: User is not confirmed., recoverySuggestion: See attached
flutter: exception for more details, underlyingException: The operation couldn’t be completed.
flutter: (AmplifyPlugins.AWSCognitoAuthError error 1.))
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      AmplifyAuthCognitoMethodChannel.signIn (package:amplify_auth_cognito/method_channel_auth_cognito.dart:122:7)
flutter: <asynchronous suspension>
flutter: #1      AmplifyAuthCognito.signIn (package:amplify_auth_cognito/amplify_auth_cognito.dart:69:17)
flutter: <asynchronous suspension>
flutter: #2      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:104:7)
flutter: <asynchronous suspension>
flutter: #3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
flutter: <asynchronous suspension>
flutter: #4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
flutter: <asynchronous suspension>
flutter:
flutter: The test description was:
flutter:   should sign a user out
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:08 +2 -4: signOut should sign a user out [E]
flutter:   Test failed. See exception logs above.
  The test description was: should sign a user out
flutter:
flutter: Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
flutter: 00:08 +2 -5: signOut should not throw even if there is no user to sign out
flutter: 00:12 +3 -5: (tearDownAll)
flutter: Warning: integration_test plugin was not detected.

If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.

If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:

https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
flutter: 00:12 +4 -5: Some tests failed.
Failure Details:
Failure in method: should signIn a user
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following UserNotConfirmedException was thrown running a
test:
UserNotConfirmedException(message: User is not confirmed.,
recoverySuggestion: See attached exception for more details,
underlyingException: The operation couldn’t be completed.
(AmplifyPlugins.AWSCognitoAuthError error 1.))

When the exception was thrown, this was the stack:
#0      AmplifyAuthCognitoMethodChannel.signIn (package:amplify_auth_cognito/method_channel_auth_cognito.dart:122:7)
<asynchronous suspension>
#1      AmplifyAuthCognito.signIn (package:amplify_auth_cognito/amplify_auth_cognito.dart:69:17)
<asynchronous suspension>
#2      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:40:11)
<asynchronous suspension>
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
<asynchronous suspension>

The test description was:
  should signIn a user
═════════════════════════════════════════════════════════════════

end of failure 1


Failure in method: should throw a UserNotConfirmedException with an incorrect password
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: <Instance of 'UserNotConfirmedException'>
  Actual: NotAuthorizedException:<NotAuthorizedException(message:
Incorrect username or password., recoverySuggestion: Check
whether the given values are correct and the user is authorized
to perform the operation., underlyingException: null)>
   Which: is not an instance of 'UserNotConfirmedException'

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:52:9)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
<asynchronous suspension>

This was caught by the test expectation on the following line:
  file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart line 52
The test description was:
  should throw a UserNotConfirmedException with an incorrect
  password
═════════════════════════════════════════════════════════════════

end of failure 2


Failure in method: should throw a UserNotFoundException with a non-existent user
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: <Instance of 'UserNotFoundException'>
  Actual: NotAuthorizedException:<NotAuthorizedException(message:
Incorrect username or password., recoverySuggestion: Check
whether the given values are correct and the user is authorized
to perform the operation., underlyingException: null)>
   Which: is not an instance of 'UserNotFoundException'

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:63:9)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
<asynchronous suspension>

This was caught by the test expectation on the following line:
  file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart line 63
The test description was:
  should throw a UserNotFoundException with a non-existent user
═════════════════════════════════════════════════════════════════

end of failure 3


Failure in method: should throw an InvalidStateException if a user is already signed in
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following UserNotConfirmedException was thrown running a
test:
UserNotConfirmedException(message: User is not confirmed.,
recoverySuggestion: See attached exception for more details,
underlyingException: The operation couldn’t be completed.
(AmplifyPlugins.AWSCognitoAuthError error 1.))

When the exception was thrown, this was the stack:
#0      AmplifyAuthCognitoMethodChannel.signIn (package:amplify_auth_cognito/method_channel_auth_cognito.dart:122:7)
<asynchronous suspension>
#1      AmplifyAuthCognito.signIn (package:amplify_auth_cognito/amplify_auth_cognito.dart:69:17)
<asynchronous suspension>
#2      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:72:7)
<asynchronous suspension>
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
<asynchronous suspension>

The test description was:
  should throw an InvalidStateException if a user is already
  signed in
═════════════════════════════════════════════════════════════════

end of failure 4


Failure in method: should sign a user out
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following UserNotConfirmedException was thrown running a
test:
UserNotConfirmedException(message: User is not confirmed.,
recoverySuggestion: See attached exception for more details,
underlyingException: The operation couldn’t be completed.
(AmplifyPlugins.AWSCognitoAuthError error 1.))

When the exception was thrown, this was the stack:
#0      AmplifyAuthCognitoMethodChannel.signIn (package:amplify_auth_cognito/method_channel_auth_cognito.dart:122:7)
<asynchronous suspension>
#1      AmplifyAuthCognito.signIn (package:amplify_auth_cognito/amplify_auth_cognito.dart:69:17)
<asynchronous suspension>
#2      main.<anonymous closure>.<anonymous closure> (file:///Users/abhishek/Downloads/Flutter/integration_test/widget_testing/login_screen_test.dart:104:7)
<asynchronous suspension>
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
<asynchronous suspension>

The test description was:
  should sign a user out
═════════════════════════════════════════════════════════════════

end of failure 5
Failed to stop app
```
</details>

**Comment by Jordan-Nelson** [comment]
Hi @Abhishek01039 - Thanks for taking the time to open the issue.

From looking at the logs, there is a UserNotConfirmedException being thrown after login. The integration test suite requires setting up auto confirmation. The contributing doc has [a section on provisioning resources](https://github.com/aws-amplify/amplify-flutter/blob/main/CONTRIBUTING.md#provision-resources-for-integration-tests) for integration tests that has the steps required to set up auto confirmation.

Let me know if you have any questions.

**Comment by Abhishek01039** [comment]
Hello @Jordan-Nelson 
Thank for your detail answer and docs.

`amplify update auth` will create a new user pool if we write the exact same answer as explain there?
