### ISSUE TITLE
NullPointer Exception on DataStore Delete of Object with Relations 

### ISSUE THREAD

**Issue by ianfmc** [aws-amplify/amplify-flutter#972]
**Describe the bug**
A NullPointerException is thrown when trying to delete models with a relationship.

**To Reproduce**

1. Create the following Schema

```
type Contact @model @auth(rules: [{allow: owner}]) @key(fields: ["email"], name: "contactByEmail", queryField: "contactByEmail") {
  id: ID!
  name: String!
  email: String!
  relationship: String
  groups: [ContactGroup] @connection(name: "byContact", fields: ["id"])
}

type Group @model @auth(rules: [{allow: owner}]) @key(fields: ["name"], name: "groupByName", queryField: "groupByName") {
  id: ID!
  name: String!
  contacts: [ContactGroup]! @connection(name: "byGroup", fields: ["id"])
}

type ContactGroup @model @auth(rules: [{allow: owner}]) @key(name: "byContact", fields: ["contactId", "groupId"], queryField: "groupsByContact") @key(name: "byGroup", fields: ["groupId", "contactId"], queryField: "contactsByGroup") {
  id: ID!
  contactId: ID!
  groupId: ID!
  contact: Contact! @connection(fields: ["contactId"])
  group: Group! @connection(fields: ["groupId"])
}
```
2. Save the model:
```
  void onAddNewContactPressed() async {
    final groupWithEveryContact = await Amplify.DataStore.query(Group.classType,
        where: Group.NAME.eq('ALL'));

    try {
      Contact newContact = new Contact(
          name: nameController.text,
          email: emailController.text,
          groups: List<ContactGroup>.empty(growable: false));
      await Amplify.DataStore.save(newContact);
      print('Saved: ${newContact.toString()}');
      final newContactGroupItem = new ContactGroup(
          contact: newContact, group: groupWithEveryContact[0]);
      await Amplify.DataStore.save(newContactGroupItem);
      print('Saved: ${newContactGroupItem.toString()}');

      Navigator.pushNamed(context, '/main');
    } catch (e) {
      print(e);
    }
  }
```
3. Delete the Model
```
 void _removeContactItem(Contact item) async {
    final contact = (await Amplify.DataStore.query(Contact.classType,
        where: Contact.ID.eq(item.id)))[0];
    SnackBar snackBar = SnackBar(
        content: Text('Delete is Currently Unavailable'),
        duration: Duration(seconds: 3),
        action: SnackBarAction(label: 'OK', onPressed: () {}));
    ScaffoldMessenger.of(context).showSnackBar(snackBar);

    // To Do: waiting for fix to delete with hasOne
    //
    await Amplify.DataStore.delete(contact);
  }
```
**Expected behavior**
The model should be deleted. There should not be an exception thrown.

**Actual behavior**
```
E/amplify:flutter:datastore(31150): DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference, recoverySuggestion=See attached exception for details.}
E/amplify:flutter:datastore(31150): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:542)
E/amplify:flutter:datastore(31150): 	at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12)
E/amplify:flutter:datastore(31150): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/amplify:flutter:datastore(31150): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:flutter:datastore(31150): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:datastore(31150): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:datastore(31150): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:datastore(31150): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelAssociation.getTargetName()' on a null object reference
E/amplify:flutter:datastore(31150): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.recurseTree(SQLiteModelTree.java:125)
E/amplify:flutter:datastore(31150): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.descendantsOf(SQLiteModelTree.java:87)
E/amplify:flutter:datastore(31150): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:510)
E/amplify:flutter:datastore(31150): 	... 6 more
```

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android. This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Works when called from Angular web-based application**

**Comment by ianfmc** [comment]
Out of the office, Hui. Will try to on Monday!

**Comment by ianfmc** [comment]
Changed the @connection decorator from 'name' to 'keyName.' 

Works
